-- تعديل Procedure SALARY_DUES_TB_LIST لترتيب البيانات حسب الموظف
-- يتم ترتيب البيانات حسب الموظف ثم الشهر ثم نوع الدفع ثم SERIAL

CREATE OR REPLACE PROCEDURE SALARY_DUES_TB_LIST (
    INSQL       IN VARCHAR2,
    OFFSET      NUMBER,
    ROW         NUMBER,
    REF_CUR_OUT OUT SYS_REFCURSOR,
    MSG_OUT     OUT VARCHAR2
) AS
    XSQL VARCHAR2(4000);
BEGIN
    XSQL := '
    SELECT * FROM (
        SELECT M.*,
               EMP_PKG.GET_EMP_NAME(M.EMP_NO) EMP_NO_NAME,
               SETTING_PKG.GCC_BRANCHES_TB_GET_NAME(EMP_PKG.GET_EMP_BRANCH(M.EMP_NO)) AS BRANCH_NAME,
               SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(537, M.PAY_TYPE) PAY_TYPE_NAME,
               SALARYFORM.GET_EMP_TOTAL_DUE(M.EMP_NO) TOTAL_DUE,
               SALARYFORM.GET_EMP_TOTAL_PAID_ALL(M.EMP_NO) TOTAL_PAID,
               SALARYFORM.GET_EMP_TOTAL_BALANCE(M.EMP_NO) TOTAL_BALANCE,
               ROW_NUMBER() OVER (ORDER BY M.EMP_NO, M.THE_MONTH, M.PAY_TYPE, M.SERIAL DESC) RN
          FROM SALARY_DUES_TB M ' || NVL(INSQL, '') || '
    )
    WHERE RN BETWEEN ' || (OFFSET + 1) || ' AND ' || ROW || '
    ORDER BY RN';

    OPEN REF_CUR_OUT FOR XSQL;
    MSG_OUT := '1';

EXCEPTION
    WHEN OTHERS THEN
        MSG_OUT := SQLERRM;
END SALARY_DUES_TB_LIST;
/
