<?php
/**
 * Created by PhpStorm.
 * User: mkilani
 * Date: 15/12/14
 * Time: 08:53 ص
 */

$img_url= base_url('assets/images');
$welcome_url= base_url('welcome');
?>

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="generator" content="CoffeeCup HTML Editor (www.coffeecup.com)">
<meta name="dcterms.created" content="Sun, 14 Dec 2014 18:45:08 GMT">
<meta name="description" content="">
<meta name="keywords" content="">
<title>GEDCo</title>
<style>
    /* Default CSS */
    /* Generated by the CoffeeCup HTML Editor - www.coffeecup.com */

    body {width:760px; margin:0 auto;}

    #f{ }


    #finance {
        margin-bottom: 10px;
        padding-bottom: 10px;
    }
    #hexagon {
        background-image: url('<?=$img_url?>/url.png');
        background-repeat: no-repeat;
        width:80px;
        float:right;

    }

    #financeText {
        float: right;
        margin-top: 30px;
        margin-right : 30px;
        text-align: left;
        font-family: "Adobe Arabic";
        font-size: 20px;
        font-weight: bold;
    }


    #admin {
        margin-bottom:10px;
        padding-bottom:20px;
        height: 59px;
    }
    #adminBut {
        background-image: url('<?=$img_url?>/url.png');
        background-repeat: no-repeat;
        width:80px;
        float:right;

    }
    #adminText {
        float: right;
        margin-top: 30px;
        margin-right : 30px;
        text-align: left;
        font-family: "Adobe Arabic";
        font-size: 20px;
        font-weight: bold;
    }


    #tech {
        margin-bottom:10px;
        padding-bottom:20px;

    }
    #tecbut {
        background-image: url('<?=$img_url?>/url.png');
        background-repeat: no-repeat;
        width:80px;
        float:right;

    }
    #tectext {
        float: right;
        margin-top: 30px;
        margin-right : 30px;
        text-align: left;
        font-family: "Adobe Arabic";
        font-size: 20px;
        font-weight: bold;
    }


    #header{
        background-color: #192533;
        height: 114px;
        border-top-left-radius: 1em;
        border-top-right-radius: 1em;
        border : solid 2px #192533;
        background-image: url('<?=$img_url?>/Untitled-2 copy.JPG');
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
    #header img{
        width:758px;
        height: 112px;
        border-top-left-radius: 1em;
        border-top-right-radius: 1em;

    }
    #mMain{height:400px; border :solid 2px #192533;
        direction: rtl;
    }
    #Footer{
        background-color: #192533;
        height: 40px;
        border : solid 2px #192533;
        border-bottom-right-radius: 1em;
        border-bottom-left-radius: 1em;
        font-family: "Adobe Arabic";
        color: #FFFFFF;
        font-size: medium;
        font-weight: bold;
        vertical-align: middle;
        text-align: center;
    }

    #contant {
        padding: 40px;
        margin: 10px;
    }


    #adminBut {
        background-image: url('<?=$img_url?>/url-copy.png');
        background-repeat: no-repeat;
    }
    #tecbut {
        background-image: url('<?=$img_url?>/url-copy2.png');
        background-repeat: no-repeat;
    }
    /*
    #hexagon:hover {
     background-color: #192533;
        background-image: linear-gradient(top, #fafafa, #ddd);
    }*/

    .a_demo_four {
        width: 80px;
        height: 80px;
        position: relative;
        font-family: 'Open Sans', sans-serif;
        font-size:12px;
        text-decoration:none;
        color:#fff;
        position:relative;


        background-image: linear-gradient(bottom, rgb(44,160,202) 0%, rgb(62,184,229) 100%);
        background-image: -o-linear-gradient(bottom, rgb(44,160,202) 0%, rgb(62,184,229) 100%);
        background-image: -moz-linear-gradient(bottom, rgb(44,160,202) 0%, rgb(62,184,229) 100%);
        background-image: -webkit-linear-gradient(bottom, rgb(44,160,202) 0%, rgb(62,184,229) 100%);
        background-image: -ms-linear-gradient(bottom, rgb(44,160,202) 0%, rgb(62,184,229) 100%);
        background-image: -webkit-gradient(
            linear,
            left bottom,
            left top,
            color-stop(0, rgb(44,160,202)),
            color-stop(1, rgb(62,184,229))
        );
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        -o-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: inset 0px 0px 0px #192533, 0px 3px 0px 0px #192533, 0px 5px 5px #192533;
        -moz-box-shadow: inset 0px 0px 0px #192533, 0px 3px 0px 0px #192533, 0px 5px 5px #192533;
        -o-box-shadow: inset 0px 0px 0px #192533, 0px 3px 0px 0px #192533, 0px 5px 5px #192533;
        box-shadow: inset 0px 0px 0px #192533, 0px 3px 0px 0px #192533, 0px 5px 5px #192533;
    }

    .a_demo_four:active {
        top:3px;
        background-image: linear-gradient(bottom, rgb(62,184,229) 0%, rgb(44,160,202) 100%);
        background-image: -o-linear-gradient(bottom, rgb(62,184,229) 0%, rgb(44,160,202) 100%);
        background-image: -moz-linear-gradient(bottom, rgb(62,184,229) 0%, rgb(44,160,202) 100%);
        background-image: -webkit-linear-gradient(bottom, rgb(62,184,229) 0%, rgb(44,160,202) 100%);
        background-image: -ms-linear-gradient(bottom, rgb(62,184,229) 0%, rgb(44,160,202) 100%);
        background-image: -webkit-gradient(
            linear,
            left bottom,
            left top,
            color-stop(0, rgb(62,184,229)),
            color-stop(1, rgb(44,160,202))
        );
        /*-webkit-box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #156785, 0px 5px 3px #999;
        -moz-box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #156785, 0px 5px 3px #999;
        -o-box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #156785, 0px 5px 3px #999;
        box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #156785, 0px 5px 3px #999;*/
    }

    .clear {
        height:10px;
        clear:both;

    }

</style>

<!--[if IE]>
<script>
    /*
     HTML5 Shiv v3.7.0 | @afarkas @jdalton @jon_neal @rem | MIT/GPL2 Licensed
     */
    (function(l,f){function m(){var a=e.elements;return"string"==typeof a?a.split(" "):a}function i(a){var b=n[a[o]];b||(b={},h++,a[o]=h,n[h]=b);return b}function p(a,b,c){b||(b=f);if(g)return b.createElement(a);c||(c=i(b));b=c.cache[a]?c.cache[a].cloneNode():r.test(a)?(c.cache[a]=c.createElem(a)).cloneNode():c.createElem(a);return b.canHaveChildren&&!s.test(a)?c.frag.appendChild(b):b}function t(a,b){if(!b.cache)b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag();
        a.createElement=function(c){return!e.shivMethods?b.createElem(c):p(c,a,b)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+m().join().replace(/[\w\-]+/g,function(a){b.createElem(a);b.frag.createElement(a);return'c("'+a+'")'})+");return n}")(e,b.frag)}function q(a){a||(a=f);var b=i(a);if(e.shivCSS&&!j&&!b.hasCSS){var c,d=a;c=d.createElement("p");d=d.getElementsByTagName("head")[0]||d.documentElement;c.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>";
        c=d.insertBefore(c.lastChild,d.firstChild);b.hasCSS=!!c}g||t(a,b);return a}var k=l.html5||{},s=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,r=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,j,o="_html5shiv",h=0,n={},g;(function(){try{var a=f.createElement("a");a.innerHTML="<xyz></xyz>";j="hidden"in a;var b;if(!(b=1==a.childNodes.length)){f.createElement("a");var c=f.createDocumentFragment();b="undefined"==typeof c.cloneNode||
        "undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}g=b}catch(d){g=j=!0}})();var e={elements:k.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==k.shivCSS,supportsUnknownElements:g,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:q,createElement:p,createDocumentFragment:function(a,b){a||(a=f);
        if(g)return a.createDocumentFragment();for(var b=b||i(a),c=b.frag.cloneNode(),d=0,e=m(),h=e.length;d<h;d++)c.createElement(e[d]);return c}};l.html5=e;q(f)})(this,document);
</script>
<![endif]-->
<style type="text/css">

</style>
</head>
<body>

<div id="f">
    <div id="header">

        <img  src="<?=$img_url?>/Untitled-2%20copy.JPG" /></div>
    <div id="mMain">

        <div id="contant">
            <a href="<?=$welcome_url?>" >
            <div id="finance"><div id="hexagon" class="a_demo_four" ></div>
                <div id="financeText">النظام المالي</div>
                <div class="clear"></div>
            </a>
            </div>

            <div id="admin">
                <div id="adminBut" class="a_demo_four" ></div>
                <div id="adminText">النظام الاداري</div>
                <div class="clear"></div>


            </div>
            <div id="tech"> <div id="tecbut" class="a_demo_four" ></div>

                <div id="tectext">النظام الفني</div>
                <div class="clear"></div>

            </div>

        </div>

    </div>
    <div id="Footer">

        <p style="height: 23px">جميع الحقوق محفوظة ©  شركة توزيع كهرباء محافظات غزة 2014</p>
    </div>


</div>
</body>
</html>
