<?php
/**
 * Created by PhpStorm.
 * User: ashikhali
 * Date: 9/9/2021
 * Time: 9:42 AM
 */

class Workfield extends MY_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('root/rmodel');
        $this->load->model('workfield_model');
        $this->load->model('settings/gcc_branches_model');
        $this->load->model('settings/constant_details_model');
        $this->rmodel->package = 'WORKFIELD_PKG';
        $this->workfield_model->package = 'WORKFIELD_PKG';
    }

    function reports(){
        $this->_lookup($data);
        $data['title']='تقارير التحصيل الميداني';
        $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['user_type'] = $this->constant_details_model->get_list(491);
        $data['content']='workfield_reports_index';
        $this->load->view('template/template',$data);
    }

    function _lookup(&$data)
    {
        $this->_loadDatePicker(); // TODO: Change the autogenerated stub
        add_css('jquery.dataTables.css');
        add_js('jquery.dataTables.js');
        add_css('sweetalert2/sweetalert2.min.css');
        add_js('sweetalert2/sweetalert2.all.min.js');
        add_css('select2_metro_rtl.css');
        add_js('select2.min.js');
        $data['user_branch'] = $this->user->branch;
        $data['branches'] = $this->gcc_branches_model->get_all();
        $this->_generate_std_urls($data, true, true);
    }

    /******** start general_functions region *********/
    function UpdateBill()
    {
        $data_arr = array(
            array('name' => 'SER_IN', 'value' => $this->p_ser, 'type' => '', 'length' => -1),
            array('name' => 'NO_IN', 'value' => $this->p_no, 'type' => '', 'length' => -1),
            array('name' => 'NAME_IN', 'value' => $this->p_name, 'type' => '', 'length' => -1),
            array('name' => 'IDENTITY_IN', 'value' => $this->p_identity, 'type' => '', 'length' => -1),
            array('name' => 'ADDRESS_IN', 'value' => $this->p_address, 'type' => '', 'length' => -1),
            array('name' => 'MOBILE_IN', 'value' => $this->p_mobile, 'type' => '', 'length' => -1),
        );
        $rs = $this->rmodel->update('UPDATE_BILL', $data_arr);
        $this->return_json($rs);
    }

    function public_sub_info()
    {
        $id = $this->input->post('id');
        $result =$this->rmodel->get('SUBSCRIBER_INFO_GET', $id);
        $this->output->set_content_type('application/json');
        $this->output->set_output(json_encode($result));
    }

    function BillDetails($id)
    {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {
            $this->_lookup($data);
            $bill = $this->workfield_model->get('GET_BILL', $id);
            $data["bill"] = count($bill) > 0 ? $bill[0] : null;
            $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
            $data['content'] = 'workfield_bills_show';
            $this->load->view('template/view', $data);
        }
    }
    /******** end general_functions region *********/

    /******** start user_satge region *********/
    function Users()
    {
        $this->_lookup($data);
        $data["users"] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['title'] = 'برنامج التحصيل الميداني :: قائمة مندوبي التحصيل';
        $data['content'] = 'workfield_users_index';
        $this->load->view('template/template', $data);
    }

    function userPassword($id)
    {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {
            $this->_lookup($data);
            $user = $this->workfield_model->get('GET_USER_PASSWORD', $id);
            $data["user"] = count($user) > 0 ? $user[0] : null;
            $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
            $data['content'] = 'workfield_user_show';
            $this->load->view('template/view', $data);
        }
    }

    function userData($id)
    {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {
            $this->_lookup($data);
            $user = $this->workfield_model->get('GET_USER_DATA', $id);
            $data["user"] = count($user) > 0 ? $user[0] : null;
            $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
            $data['content'] = 'workfield_user_data_show';
            $this->load->view('template/view', $data);
        }
    }

    function addNewUser()
    {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {
            $this->_lookup($data);
            $data['emp_no_cons'] = $this->rmodel->get('EVA_EMPS_STRUCTURE_CHILD_GET', 0);
            $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
            $data['content'] = 'workfield_add_user_data_show';
            $this->load->view('template/view', $data);
        }
    }

    function public_get_user_data()
    {
        $user_no = $this->input->post('user_no');
        $result =$this->rmodel->get('USER_INFO_GET', $user_no);
        $this->output->set_content_type('application/json');
        $this->output->set_output(json_encode($result));
    }

    public function generate_password(){
        $alphabet = '1234567890';
        $pass = array(); //remember to declare $pass as an array
        $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
        for ($i = 0; $i < 8; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass); //turn the array into a string
    }

    function insertUser() {
        if($_SERVER['REQUEST_METHOD'] == 'POST'){
            $password = $this->generate_password();
            $data_arr = array(
                array('name' => 'TYPE_IN', 'value' => $this->p_user_type, 'type' => '', 'length' => -1),
                array('name' => 'NO_IN', 'value' => $this->p_user_no, 'type' => '', 'length' => -1),
                array('name' => 'NAME_IN', 'value' => $this->p_user_name, 'type' => '', 'length' => -1),
                array('name' => 'PASSWORD_IN', 'value' => $password, 'type' => '', 'length' => -1),
                array('name' => 'MOBILE_IN', 'value' => $this->p_user_mobile, 'type' => '', 'length' => -1),
            );
            $result = $this->rmodel->insert('INSERT_USER', $data_arr);

            if(intval($result) <= 0){
                $this->print_error(' لم يتم الحفظ الجدول الاساسي '.'<br>'.$result);
            }else{
                $user="Auto-APPS-SMS";
                $password_app="2118058";
                $sender="GEDCO";
                $message='رقم المحصل: '.$this->p_user_no.'  كلمة المرور: '.$password;
                $message = urlencode($message);

                $url="https://im-server.gedco.ps:8005/apis/v1/SendSms?&message=".$message."&user=".$user."&password=".$password_app."&sender=".$sender."&mobile=".$this->p_user_mobile ;
                $ret= $this->getHtml($url);
                echo 1;
            }
        } //end if post
    }

    function updatePassword()
    {
        $password = $this->generate_password();
        $data_arr = array(
            array('name' => 'NO_IN', 'value' => $this->p_id, 'type' => '', 'length' => -1),
            array('name' => 'PASSWORD_IN', 'value' => $password, 'type' => '', 'length' => -1),
        );

        if(strlen($password) >= 8){
            $rs = $this->rmodel->update('UPDATE_PASSWORD', $data_arr);

            $user="Auto-APPS-SMS";
            $password_app="2118058";
            $sender="GEDCO";
            $message='رقم المحصل: '.$this->p_id.'  كلمة المرور: '.$password;
            $result_mobile = $this->rmodel->get('USER_MOBILE_GET',$this->p_id);
            $message = urlencode($message);

            $mob = "0".$result_mobile[0]["MOBILE"];
            $url="https://im-server.gedco.ps:8005/apis/v1/SendSms?&message=".$message."&user=".$user."&password=".$password_app."&sender=".$sender."&mobile=".$mob ;
            $ret= $this->getHtml($url);

            $this->return_json($rs);

        } else {
            $this->return_json(array('status' => 0, 'error' => 'حدث خطأ'));
        }
    }

    function updateData()
    {
        $data_arr = array(
            array('name' => 'NO_IN', 'value' => $this->p_ser, 'type' => '', 'length' => -1),
            array('name' => 'MOBILE_IN', 'value' => $this->p_user_mobile, 'type' => '', 'length' => -1),
        );

        $rs = $this->rmodel->update('UPDATE_DATA', $data_arr);
        $this->return_json($rs);
    }

    function getHtml($url, $post = null) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);

        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 0);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);

        if(!empty($post)) {
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        }
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;
    }

    function UpdateAccount()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => '', 'length' => -1),
            array('name' => 'INCOME_ACCOUNT_IN', 'value' => $this->p_income_account, 'type' => '', 'length' => -1)
        );
        $rs = $this->rmodel->update('UPDATE_USER_ACCOUNT_ID', $data_arr);
        $this->return_json($rs);
    }
    /******** end user_satge region *********/

    /******** start first_satge region *********/
    function first_stage_get_page($date = null)
    {
        $this->_lookup($data);
        if($date == null){
            $new_date = str_replace("/", "", $this->p_collect_date);
            $data["date"] = $this->p_collect_date;
        } else {
            $new_date = str_replace("/", "", $date);
            $data["date"] = $date;
        }
        $data["date"] = $new_date;
        $data["comp_date"] = "";
        $data['title'] = 'برنامج التحصيل الميداني :: قائمة مندوبي التحصيل - سندات تحصيل';

        if($this->p_user_type == 1) {
            $data["users"] = $this->workfield_model->getTwoColumn('GET_ALL_BILLS_USERS', $new_date, $this->p_user_no);
            $this->load->view('workfield_first_stage_get_page', $data);
        } else if ($this->p_user_type == 2){
            $from_date = str_replace("/","", $this->p_company_date);
            $data["date"] = date("Ymd");
            $data["comp_date"] = $from_date;
            $data["users"] = $this->workfield_model->getTwoColumn('GET_ALL_BILLS_COMPANIES', $from_date,$this->p_company);
            $this->load->view('workfield_first_stage_get_page', $data);
        } else {

        }

    }

    function first_satge()
    {
        $this->_lookup($data);
        $data['title'] = 'برنامج التحصيل الميداني ::   استلام سندات التحصيل ';
        $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['companies'] = $this->workfield_model->getData('GET_ALL_COMPANIES');
        $data['user_type'] = $this->constant_details_model->get_list(491);
        $data['content'] = 'workfield_first_satge_index';
        $this->load->view('template/template', $data);
    }

    function update_document()
    {
        $data_arr = array(
            array('name' => 'TELLER_SERIAL_IN', 'value' => $this->p_teller_serial, 'type' => '', 'length' => -1),
            array('name' => 'RECORD_NO_IN', 'value' => $this->p_record_no, 'type' => '', 'length' => -1),
        );

        $rs = $this->rmodel->update('UPDATE_DOCUMENT', $data_arr);

        $this->return_json($rs);
    }

    function first_satge_adopt($id = 0, $check = 0, $date = 0, $teller = 0)
    {
        $this->_lookup($data);
        add_css('sweetalert2/sweetalert2.min.css');
        add_js('sweetalert2/sweetalert2.all.min.js');
        $data['user_id'] = $id;
        $data['user_date'] = $date;
        $data['user_type'] = 1;
        $data["user"] = $this->workfield_model->get('GET_USER', $id);
        $data["teller"] = $teller;

        //Already done
        if($check == 2 || $check == 4 || $check == 6) {
            $data['bank_doc_value'] = $this->workfield_model->getMsg_ID('GET_BANK_DOC_USER_TELLER', $teller);
            $data['bank_doc'] =  $this->workfield_model->get('GET_BANK_DOC_USER', $date);
            $data['operation'] = $this->workfield_model->getMsg_ID('GET_OPERATION_NO_TELLER', $teller);
            $data["bills"] = $this->workfield_model->getThreeColumn('GET_BILLS_BY_USER_WELL_ADOPT', $id, $date, $teller);
        } else {
            $data['bank_doc'] =  $this->workfield_model->get('GET_BANK_DOC_USER', $date);
            $data['operation'] = $this->workfield_model->getMSG('GET_OPERATION_NO_BY_USER');
            $data["bills"] = $this->workfield_model->getThreeColumn('GET_BILLS_BY_USER_TO_ADOPT', $id, $date, $teller);
        }
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
        $data['content'] = 'workfield_first_satge_adopt';
        $this->load->view('template/template', $data);
    }

    function first_satge_comp($id = 0, $check = 0, $date = 0, $teller = 0, $comp_date = 0)
    {
        $this->_lookup($data);
        add_css('sweetalert2/sweetalert2.min.css');
        add_js('sweetalert2/sweetalert2.all.min.js');
        $data['user_id'] = $id;
        $data['user_date'] = $date;
        $data['comp_date'] = $comp_date;
        $data['user_type'] = 2;
        $data["user"] = $this->workfield_model->get('GET_USER', $id);
        $data["teller"] = $teller;

        //Already done
        if($check == 2 || $check == 4 || $check == 6) {
            $data['bank_doc_value'] = $this->workfield_model->getMsg_ID('GET_BANK_DOC_USER_TELLER', $teller);
            $data['bank_doc'] =  $this->workfield_model->get('GET_BANK_DOC_USER', $date);
            $data['operation'] = $this->workfield_model->getMsg_ID('GET_OPERATION_NO_TELLER', $teller);
            $data["bills"] = $this->workfield_model->getThreeColumn('GET_BILLS_BY_COMP_WELL_ADOPT', $id, $comp_date, $teller);
        } else {
            $data['bank_doc'] =  $this->workfield_model->get('GET_BANK_DOC_USER', $date);
            $data['operation'] = $this->workfield_model->getMSG('GET_OPERATION_NO_BY_USER');
            $data["bills"] = $this->workfield_model->getThreeColumn('GET_BILLS_BY_COMP_TO_ADOPT', $id, $comp_date,$teller);
        }
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
        $data['content'] = 'workfield_first_satge_adopt';
        $this->load->view('template/template', $data);
    }

    function Adopt()
    {
        $arr = array();
        foreach ($this->p_ids as $id) {
            array_push($arr, $id);
        }
        $bank_doc =  $this->p_bank_doc;
        $operation = $this->workfield_model->getMSG('GET_OPERATION_NO_BY_USER');
        if($bank_doc == null || strlen($bank_doc) < 2){
            echo -1;
        } elseif ($operation == 0 || $operation == null) {
            echo -2;
        } else {
            $data_arr = array(
                array('name' => 'IDS_IN', 'value' => $this->p_ids, 'type' => SQLT_CHR, 'length' => -1),
                //array('name' => 'ID_IN', 'value' => $arr[$x], 'type' => '', 'length' => -1),
                array('name' => 'BANK_DOCUMENT', 'value' => $bank_doc, 'type' => '', 'length' => -1),
                array('name' => 'OPERATION', 'value' => $operation, 'type' => '', 'length' => -1)
            );
            $rs = $this->rmodel->update('ADOPT_BILL', $data_arr);
            echo $rs;
        }
    }
    /******** end first_satge region *********/

    /******** start user_operation region *********/
    function user_operation()
    {
        $data['title'] = 'أرقام عمليات موظفين التيلر';
        $data['emp_no_cons'] = $this->rmodel->get('EVA_EMPS_STRUCTURE_CHILD_GET', 0);
        $data['content'] = 'workfield_user_operation';
        $this->_lookup($data);
        $this->load->view('template/template', $data);
    }

    function get_operation_no(){
        $emp_no = $this->p_emp_no;
        $result= $this->workfield_model->getMsg_ID('GET_OPERATION_NO', $emp_no);
        echo $result;
    }

    function update_operation_no()
    {
        $data_arr = array(
            array('name' => 'EMP_NO', 'value' => $this->p_emp_no, 'type' => '', 'length' => -1),
            array('name' => 'OPERATION_NO', 'value' => $this->p_operation_no, 'type' => '', 'length' => -1)
        );
        $rs = $this->rmodel->update('UPDATE_OPERATION_NO', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    /******** end user_operation region *********/

    /******** start canceled_stage region *********/
    function canceled_stage()
    {
        $this->_lookup($data);
        $data['title'] = 'برنامج التحصيل الميداني :: سندات التحصيل الملغية ';
        $data['content'] = 'workfield_canceled_stage_index';
        $this->load->view('template/template', $data);
    }

    function canceled_stage_get_page()
    {
        $this->_lookup($data);
        $new_date = str_replace("/", "", $this->p_collect_date);
        $data["users"] = $this->workfield_model->get('GET_CANCELED_BILLS', $new_date);
        $data["date"] = $new_date;
        $data['title'] = 'برنامج التحصيل الميداني :: سندات التحصيل الملغية ';
        $this->load->view('workfield_canceled_stage_page', $data);
    }

    function canceled_bills($id = 0, $date= 0)
    {
        $this->_lookup($data);
        $data["user"] = $this->workfield_model->get('GET_USER', $id);
        $data["bills"] = $this->workfield_model->getTwoColumn('GET_CANCELED_BILLS_BY_USER', $id, $date);
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
        $data['content'] = 'workfield_canceled_stage_show';
        $this->load->view('template/template', $data);
    }

    function CancelBill()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
            array('name' => 'NOTE_IN', 'value' => $this->p_text, 'type' => SQLT_CHR, 'length' => -1)
        );

        $rs = $this->rmodel->update('CANCEL_BILL', $data_arr);
        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    function CancelBillAdopt()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
            array('name' => 'ADOPT', 'value' => $this->p_adopt, 'type' => SQLT_CHR, 'length' => -1),
            array('name' => 'NOTE_IN', 'value' => $this->p_text, 'type' => SQLT_CHR, 'length' => -1)
        );

        $rs = $this->rmodel->update('CANCEL_BILL_ADOPT', $data_arr);
        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    function AddNote()
    {
        $data_arr = array(
            array('name' => 'SER_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
             array('name' => 'NOTE_IN', 'value' => $this->p_text, 'type' => SQLT_CHR, 'length' => -1)
        );

        $rs = $this->rmodel->update('UBILL_TB_ADD_NOTE', $data_arr);
        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    function adoptCancelBill()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
        );
        $rs = $this->rmodel->update('ADOPT_CANCEL_BILL', $data_arr);
        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    function CancelAdoptBill()   {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
        );
        $rs = $this->rmodel->update('CANCEL_ADOPT_BILL', $data_arr);
        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    /******** end canceled_stage region *********/

    /******** start supervision_stage region *********/
    function supervision_stage()
    {
        $this->_lookup($data);
        //$data["users"] = $this->workfield_model->get('GET_TO_ADOPT_SUPERVISOR', date('Ymd'));
        $data['title'] = 'برنامج التحصيل الميداني ::  الترحيل على الفواتير  ';
        $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['user_type'] = $this->constant_details_model->get_list(491);
        $data['companies'] = $this->workfield_model->getData('GET_ALL_COMPANIES');
        $data['content'] = 'workfield_supervision_stage_index';
        $this->load->view('template/template', $data);
    }

    function supervision_stage_get_page($date = null)
    {
        $this->_lookup($data);
        if($date == null){
            $new_date = str_replace("/", "", $this->p_collect_date);
            $data["date"] = $this->p_collect_date;
        } else {
            $new_date = str_replace("/", "", $date);
            $data["date"] = $date;
        }
        $data['title'] = 'برنامج التحصيل الميداني ::  الترحيل على الفواتير  ';
        $data['new_date'] =$new_date;
        $data['user_type'] = $this->p_user_type;
        if($this->p_user_type != ""){
            if($this->p_user_type == 1){
                $data["users"] = $this->workfield_model->getTwoColumn('GET_TO_ADOPT_SUPERVISOR', $new_date, $this->p_user_type);
                $this->load->view('workfield_supervision_stage_page', $data);
            } else{
                $from_date = str_replace("/","", $this->p_company_date);
                $data["date"] = date("Ymd");
                $data["comp_date"] = $from_date;
                $data["users"] = $this->workfield_model->getTwoColumn('GET_TO_ADOPT_SUPERVISOR_COMP', $from_date, $this->p_user_type);
                $this->load->view('workfield_supervision_stage_page', $data);
            }

        } else {
            $this->print_error("يرجى اختيار نوع المحصل");
        }
    }

    function supervision_adopt()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_ids, 'type' => '', 'length' => -1),
            array('name' => 'DATE_IN', 'value' => $this->p_date, 'type' => '', 'length' => -1)
        );

        if($this->p_type == 1){
            $rs = $this->rmodel->update('ADOPT_SUPERVISOR', $data_arr);
        } else {
            $rs = $this->rmodel->update('ADOPT_SUPERVISOR_COMP', $data_arr);
        }

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }
    /******** end supervision_stage region *********/

    /******** start close_stage region *********/
    function close_stage()
    {
        $this->_lookup($data);
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات التحصيل المعتمدة ';
        $data['content'] = 'workfield_close_stage_index';
        $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['companies'] = $this->workfield_model->getData('GET_ALL_COMPANIES');
        $data['user_type'] = $this->constant_details_model->get_list(491);
        $this->load->view('template/template', $data);
    }

    function close_stage_get_page($date = null)
    {
        $this->_lookup($data);
        if($date == null){
            $new_date = str_replace("/", "", $this->p_collect_date);
            $data["date"] = $this->p_collect_date;
        } else {
            $new_date = str_replace("/", "", $date);
            $data["date"] = $date;
        }
        $data["close_date"] = $new_date;
        $data["comp_date"] = "";
        $data["user_type"] = $this->p_user_type;
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات التحصيل المعتمدة ';
        if($this->p_user_type == 1) {
            $data["users"] = $this->workfield_model->getThreeColumn('GET_ALL_ADOPT_USERS', $new_date, $this->p_user_no, $this->p_user_type);
            $this->load->view('workfield_close_stage_page', $data);
        } else if($this->p_user_type == 2){
            $from_date = str_replace("/","", $this->p_company_date);
            $data["date"] = date("Ymd");
            $data["comp_date"] = $from_date;
            $data["users"] = $this->workfield_model->getThreeColumn('GET_ALL_ADOPT_COMP', $from_date, $this->p_company, $this->p_user_type);
            $this->load->view('workfield_close_stage_page', $data);
        } else {
        }

    }

    function update_daily_financial()
    {
        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => '', 'length' => -1),
            array('name' => 'TOTAL_VAL_IN', 'value' => $this->p_total_val, 'type' => '', 'length' => -1),
            array('name' => 'INCOME_VAL_IN', 'value' => $this->p_income_val, 'type' => '', 'length' => -1),
            array('name' => 'TELLER_SERIAL_IN', 'value' => $this->p_teller_serial, 'type' => '', 'length' => -1),
        );
        $rs = $this->rmodel->update('UPDATE_FINANCIAL_POS_DATA', $data_arr);

        $this->return_json($rs);
    }

    function transfer()
    {
        $data_arr = array(
            //array('name' => 'IDS_IN', 'value' => array(), 'type' => SQLT_CHR, 'length' => -1)
            array('name' => 'ID', 'value' => $this->p_id , 'type' => '', 'length' => -1),
            array('name' => 'DATE', 'value' => $this->p_date , 'type' => '', 'length' => -1),
            array('name' => 'TELLER_SERIAL', 'value' => $this->p_teller_serial , 'type' => '', 'length' => -1)
        );
        if($this->p_type == 1 ){
            $rs = $this->rmodel->update('TRANSFER_BILL', $data_arr);
        } else {
            $rs = $this->rmodel->update('TRANSFER_BILL_COMP', $data_arr);
        }

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }




    /******** end close_stage region *********/

    /********* start public functions ********/

    function back_stage()
    {
        $data_arr = array(
            array('name' => 'TELLER_SERIAL_IN', 'value' => $this->p_teller_serial, 'type' => '', 'length' => -1),
            array('name' => 'TYPE_IN', 'value' => $this->p_type, 'type' => '', 'length' => -1),
        );
        $rs = $this->rmodel->update('BACK_STAGE', $data_arr);

        $this->return_json($rs);
    }

    /********* end public functions ********/

    function public_get_users_by_branch($branch = 0)
    {
        $branch = $this->input->post('no') ? $this->input->post('no') : $branch;
        $arr = $this->workfield_model->get_user_by_branch($branch);

        echo json_encode($arr);

    }

    function public_get_users_by_user_type($user_type = 0)
    {
        $user_type = $this->input->post('no') ? $this->input->post('no') : $user_type;
        $arr = $this->workfield_model->public_get_users_by_user_type($user_type);

        echo json_encode($arr);
    }


    /********* start devices functions ********/

    function devices()
    {
        $this->_lookup($data);
        $data['title'] = 'برنامج التحصيل الميداني :: الأجهزة ';
        $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
        $data['devices'] = $this->workfield_model->getData('GET_ALL_DEVICES');
        $data['devices_name'] = $this->workfield_model->getData('GET_DEVICES_NAME');
        $data['content'] = 'workfield_devices_index';
        $this->load->view('template/template', $data);
    }

    function devices_get_page($date = null)
    {
        $this->_lookup($data);
        $this->load->library('pagination');
        $new_received_date = str_replace("/", "", $this->p_received_date);
        $new_delivery_date = str_replace("/", "", $this->p_delivery_date);
        $where_sql= " and 1= 1 ";
        $where_sql_count= " where 1= 1 ";
        $where_sql.= ($new_received_date!= null)? " and to_char(m.received_date,'YYYYMMDD') >= '{$new_received_date}' " : '';
        $where_sql.= ($new_delivery_date!= null)? " and to_char(m.delivery_date,'YYYYMMDD') <= '{$new_delivery_date}' " : '';
        $where_sql.= ($this->p_user_no!= null)? " and m.user_no = '{$this->p_user_no}' " : '';
        $where_sql.= ($this->p_device!= null)? " and m.device_ser = '{$this->p_device}' " : '';

        $config['base_url'] = base_url($this->PAGE_URL);
        $count_rs =  $this->get_table_count('ams.DEVICES '.$where_sql_count);
        $config['use_page_numbers'] = TRUE;
        $config['total_rows'] = count($count_rs)? $count_rs[0]['NUM_ROWS']:0 ;
        $config['per_page'] = $this->page_size;
        $config['num_links'] = 20;
        $config['cur_page']= $this->p_page;
        $config['full_tag_open'] = '<div class="pagination-container"><ul class="pagination">';
        $config['full_tag_close'] = '</ul></div>';
        $config['first_tag_open'] = $config['last_tag_open']= $config['next_tag_open']= $config['prev_tag_open'] = $config['num_tag_open'] = '<li>';
        $config['first_tag_close'] = $config['last_tag_close']= $config['next_tag_close']= $config['prev_tag_close'] = $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><span><b>';
        $config['cur_tag_close'] = "</b></span></li>";

        $this->pagination->initialize($config);

        $offset = ((($this->p_page-1) * $config['per_page']) );
        $row = (($this->p_page * $config['per_page'])  );

        $data['page_rows'] = $this->rmodel->getList('DEVICES_LIST', $where_sql, $offset , $row );

        $data['offset']=$offset+1;
        $data['page']=$this->p_page;

        $data['title'] = 'برنامج التحصيل الميداني ::اجهزة التحصيل ';
        $this->load->view('workfield_devices_get_page', $data);
    }

    function change_status_device()
    {
        $data_arr = array(
            //array('name' => 'IDS_IN', 'value' => array(), 'type' => SQLT_CHR, 'length' => -1)
            array('name' => 'ID', 'value' => $this->p_id , 'type' => '', 'length' => -1),
            array('name' => 'STATUS', 'value' => $this->p_status , 'type' => '', 'length' => -1)
        );

        $rs = $this->rmodel->update('UPDATE_DEVICE_STATUS', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    function receive_device()
    {
        $data_arr = array(
            //array('name' => 'IDS_IN', 'value' => array(), 'type' => SQLT_CHR, 'length' => -1)
            array('name' => 'ID', 'value' => $this->p_id , 'type' => '', 'length' => -1)
        );

        $rs = $this->rmodel->update('RECEIVE_DEVICE', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }
    }

    /*function device_delivery()
    {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {
            $this->_lookup($data);
            $data['users'] = $this->workfield_model->getData('GET_ALL_USERS');
            $data['devices'] = $this->workfield_model->getData('GET_AVAILABLE_DEVICES');
            $data['title'] = 'برنامج التحصيل الميداني ::  تسليم جهاز  ';
            $data['content'] = 'workfield_device_delivery_show';
            $this->load->view('template/view', $data);
        }
    }*/

    function deviceDelivery()
    {
        $data_arr = array(
            array('name' => 'USER_NO_IN', 'value' => $this->p_user_modal, 'type' => '', 'length' => -1),
            array('name' => 'DEVICE_NO_IN', 'value' => $this->p_device_modal, 'type' => '', 'length' => -1),
        );
        $rs = $this->rmodel->insert('DEVICE_HISTORY_TB_INSERT', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }

    }

    function public_get_devices()
    {
        $result =$this->workfield_model->getData('GET_AVAILABLE_DEVICES');
        $this->output->set_content_type('application/json');
        $this->output->set_output(json_encode($result));
    }
    function public_get_all_devices()
    {
        $result =$this->workfield_model->getData('GET_ALL_DEVICES');
        $this->output->set_content_type('application/json');
        $this->output->set_output(json_encode($result));
    }

    function public_get_devices_name()
    {
        $result =$this->workfield_model->getData('GET_DEVICES');
        $this->output->set_content_type('application/json');
        $this->output->set_output(json_encode($result));
    }

    function create_device()
    {
        $data_arr = array(
            array('name' => 'DEVICE_NO_IN', 'value' => $this->p_device_no_modal, 'type' => '', 'length' => -1),
        );
        $rs = $this->rmodel->insert('DEVICES_TB_INSERT', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));
        }

    }




    /********* end devices functions ********/

}