<?php
/**
 * Created by PhpStorm.
 * User: abarakat
 * Date: 9/9/2021
 * Time: 9:42 AM
 */

class Workfield extends MY_Controller
{

    public function __construct()
    {
        parent::__construct();
        $this->load->model('root/rmodel');
        $this->rmodel->package = 'WORKFIELD_PKG';


    }

    function _lookup(&$data)
    {
        $this->_loadDatePicker(); // TODO: Change the autogenerated stub

        add_css('jquery.dataTables.css');
        add_js('jquery.dataTables.js');


        $this->_generate_std_urls($data, true, true);
    }

    function Users()
    {
        $this->_lookup($data);
        $data["users"] = $this->rmodel->getData('GET_ALL_USERS');
        $data['title'] = 'برنامج التحصيل الميداني :: قائمة مناديب التحصيل';
        $data['content'] = 'workfield_users_index';
        $this->load->view('template/template', $data);
    }


    function BillsUsers()
    {
        $this->_lookup($data);
        $data["users"] = $this->rmodel->getData('GET_ALL_BILLS_USERS');
        $data['title'] = 'برنامج التحصيل الميداني :: قائمة مناديب التحصيل - سندات تحصيل';
        $data['content'] = 'workfield_bills_users_index';
        $this->load->view('template/template', $data);
    }

    function CanceledBillsUsers()
    {
        $this->_lookup($data);
        $data["users"] = $this->rmodel->getData('GET_ALL_CANCELED_BILLS_USERS');
        $data['title'] = 'برنامج التحصيل الميداني :: قائمة مناديب التحصيل - سندات الملغى';
        $data['content'] = 'workfield_canceled_bills_users_index';
        $this->load->view('template/template', $data);
    }

    function Bills($id = 0)
    {
        $this->_lookup($data);

        add_css('sweetalert2/sweetalert2.min.css');
        add_js('sweetalert2/sweetalert2.all.min.js');


        $data["user"] = $this->rmodel->get('GET_USER', $id);
        $data["bills"] = $this->rmodel->get('GET_ALL_BILLS_BY_USER', $id);
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
        $data['content'] = 'workfield_bills_index';
        $this->load->view('template/template', $data);
    }

    function CancelBills($id = 0)
    {
        $this->_lookup($data);

        add_css('sweetalert2/sweetalert2.min.css');
        add_js('sweetalert2/sweetalert2.all.min.js');


        $data["user"] = $this->rmodel->get('GET_USER', $id);
        $data["bills"] = $this->rmodel->get('GET_CANNCELED_BILLS_BY_USER', $id);
        $data['title'] = 'برنامج التحصيل الميداني ::  سندات تحصيل ';
        $data['content'] = 'workfield_canceled_bills_index';
        $this->load->view('template/template', $data);
    }


    function UpdateAccount()
    {

        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => '', 'length' => -1),
            array('name' => 'ACCOUNT_IN', 'value' => $this->p_account, 'type' => '', 'length' => -1),
            array('name' => 'INCOME_ACCOUNT_IN', 'value' => $this->p_income_account, 'type' => '', 'length' => -1)
        );

        $rs = $this->rmodel->update('UPDATE_USER_ACCOUNT_ID', $data_arr);

        $this->return_json($rs);

    }

    function Transfer()
    {

        $arr = array();

        foreach ($this->p_ids as $id) {
            array_push($arr, $id);
        }

        $data_arr = array(
            array('name' => 'IDS_IN', 'value' => $this->p_ids, 'type' => SQLT_CHR, 'length' => -1)
        );

        $rs = $this->rmodel->update('TRANSFER_BILL', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));

        }
        //$this->return_json($rs);

    }

    function CancelBill()
    {

        $data_arr = array(
            array('name' => 'ID_IN', 'value' => $this->p_id, 'type' => SQLT_CHR, 'length' => -1),
            array('name' => 'NOTE_IN', 'value' => $this->p_text, 'type' => SQLT_CHR, 'length' => -1)
        );

        $rs = $this->rmodel->update('CANCEL_BILL', $data_arr);

        if (intval($rs) > 0) {
            $this->return_json(array('status' => 1));
        } else {
            $this->return_json(array('status' => 0, 'error' => $rs));

        }

    }

    function UpdateBill()
    {

        $data_arr = array(
            array('name' => 'SER_IN', 'value' => $this->p_ser, 'type' => '', 'length' => -1),
            array('name' => 'NO_IN', 'value' => $this->p_no, 'type' => '', 'length' => -1),
            array('name' => 'NAME_IN', 'value' => $this->p_name, 'type' => '', 'length' => -1),
            array('name' => 'IDENTITY_IN', 'value' => $this->p_identity, 'type' => '', 'length' => -1),
            array('name' => 'ADDRESS_IN', 'value' => $this->p_address, 'type' => '', 'length' => -1),
            array('name' => 'MOBILE_IN', 'value' => $this->p_mobile, 'type' => '', 'length' => -1),
        );


        $rs = $this->rmodel->update('UPDATE_BILL', $data_arr);

        $this->return_json($rs);
    }

    function BillDetails($id)
    {

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {

        } else {

            $this->_lookup($data);

            $bill = $this->rmodel->get('GET_BILL', $id);
            $data["bill"] = count($bill) > 0 ? $bill[0] : null;
            $data['title'] = 'تفاصيل السند ';
            $data['content'] = 'workfield_bills_show';
            $this->load->view('template/view', $data);
        }
    }
}