CREATE OR REPLACE PACKAGE GFC_PAK.DISBURSEMENT_PKG AS

  -- ============================================================
  -- Constants
  -- ============================================================
  C_REQ_TYPE_FULL_SALARY    CONSTANT NUMBER := 1;
  C_REQ_TYPE_PART_SALARY    CONSTANT NUMBER := 2;
  C_REQ_TYPE_LUMP_SUM       CONSTANT NUMBER := 3;
  C_REQ_TYPE_MONTHLY_DUES   CONSTANT NUMBER := 4;  -- دفعة مستحقات حسب الشهر
  C_REQ_TYPE_BENEFITS       CONSTANT NUMBER := 5;  -- صرف استحقاقات وإضافات (بدون تأثير على SALARY_DUES)

  C_REQ_STATUS_DRAFT             CONSTANT NUMBER := 0;
  C_REQ_STATUS_APPROVED          CONSTANT NUMBER := 1;
  C_REQ_STATUS_PAID              CONSTANT NUMBER := 2;
  C_REQ_STATUS_PARTIAL_APPROVED  CONSTANT NUMBER := 3;
  C_REQ_STATUS_PARTIAL_PAID      CONSTANT NUMBER := 4;
  C_REQ_STATUS_CANCELLED         CONSTANT NUMBER := 9;

  C_CALC_PERCENT            CONSTANT NUMBER := 1;
  C_CALC_FIXED              CONSTANT NUMBER := 2;

  C_LINE_ADD                CONSTANT NUMBER := 1;
  C_LINE_DED                CONSTANT NUMBER := 2;

  C_DUES_PAYTYPE_SALARY_CONV CONSTANT NUMBER := 12;
  C_DUES_PAYTYPE_PAYMENT     CONSTANT NUMBER := 8;

  C_SALARY_CON_DUES          CONSTANT NUMBER := 323;
  C_CONSTANT_GROUP_DUES      CONSTANT NUMBER := 48;

  -- ============================================================
  -- Public: must be in spec for SQL usage
  -- ============================================================
  FUNCTION EMP_HAS_MONTHLY_SALARY (P_EMP_NO NUMBER, P_THE_MONTH NUMBER) RETURN NUMBER;
  FUNCTION GET_BANK_NAME (P_BANK_NO NUMBER) RETURN VARCHAR2;
  FUNCTION GET_MASTER_BANK_NAME (P_EMP_NO NUMBER) RETURN VARCHAR2;
  FUNCTION GET_CONSTANT_NAME (P_CON_NO NUMBER) RETURN VARCHAR2;

  PROCEDURE GET_BENEFIT_ITEMS (
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );
  FUNCTION GET_DUES_TYPE_NAME (P_PAY_TYPE NUMBER) RETURN VARCHAR2;

  -- ============================================================
  -- Bank Helper
  -- ============================================================
  FUNCTION GET_EMP_BANK_NAME (P_EMP_NO NUMBER) RETURN VARCHAR2;
  FUNCTION GET_EMP_IS_ACTIVE (P_EMP_NO NUMBER) RETURN NUMBER;

  -- الحالة المركّبة للعرض: 1=فعّال, 0=متقاعد, 2=متوفى, 4=حساب مغلق
  -- لو P_THE_MONTH NULL ⮕ الحالة الحالية (DATA.EMPLOYEES + PAYMENT_ACCOUNTS_TB)
  -- لو P_THE_MONTH مُحدّد ⮕ الحالة التاريخية (DATA.EMPLOYEES_MONTH + INACTIVE_FROM_MONTH)
  FUNCTION GET_EMP_DISPLAY_STATUS (
      P_EMP_NO    NUMBER,
      P_THE_MONTH NUMBER DEFAULT NULL
  ) RETURN NUMBER;

  -- مطابقة معادلة SALARYFORM.GET_VAL_ADD_DED القديمة لنوع 2
  -- ترجع المبلغ اللي يتصرف للموظف (CAPPED)
  -- بدون أي تأثير على ADD_AND_DED (backup/restore تلقائي)
  FUNCTION CALC_PART_SALARY_LEGACY (
      P_EMP_NO    NUMBER,
      P_THE_MONTH NUMBER,
      P_RATE      NUMBER,
      P_L_VALUE   NUMBER,
      P_H_VALUE   NUMBER
  ) RETURN NUMBER;

  -- ============================================================
  -- Balance Functions
  -- ============================================================
  FUNCTION GET_EMP_NET_SALARY      (P_EMP_NO NUMBER, P_THE_MONTH NUMBER) RETURN NUMBER;

  FUNCTION GET_EMP_DUES_BASE      (P_EMP_NO NUMBER) RETURN NUMBER;
  FUNCTION GET_EMP_DUES_ADD       (P_EMP_NO NUMBER) RETURN NUMBER;
  FUNCTION GET_EMP_DUES_DED       (P_EMP_NO NUMBER) RETURN NUMBER;
  FUNCTION GET_EMP_DUES_RESERVED  (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER;
  FUNCTION GET_EMP_DUES_PAID      (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER;
  FUNCTION GET_EMP_DUES_AVAILABLE (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER;

  -- ============================================================
  -- Shared Helpers (public — used by DISBURSEMENT_BATCH_PKG)
  -- ============================================================
  PROCEDURE SYNC_MASTER_AMOUNT (P_REQ_ID NUMBER);
  FUNCTION  CALC_MASTER_STATUS (P_REQ_ID NUMBER) RETURN NUMBER;
  PROCEDURE LOG_ACTION (P_REQ_ID NUMBER, P_ACTION VARCHAR2, P_OLD_STATUS NUMBER, P_NEW_STATUS NUMBER, P_NOTE VARCHAR2 DEFAULT NULL);

  -- ============================================================
  -- Master CRUD
  -- ============================================================
  PROCEDURE PAYMENT_REQ_INSERT (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      P_PAY_TYPE NUMBER DEFAULT NULL, P_ENTRY_DATE DATE DEFAULT NULL,
      P_NOTE VARCHAR2,
      -- 🆕 شهر فلتر اختياري — للنوع 3
      P_FILTER_MONTH NUMBER DEFAULT NULL,
      P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE PAYMENT_REQ_UPDATE (
      P_REQ_ID NUMBER, P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      P_PAY_TYPE NUMBER DEFAULT NULL,
      P_NOTE VARCHAR2,
      -- 🆕 شهر فلتر اختياري — للنوع 3
      P_FILTER_MONTH NUMBER DEFAULT NULL,
      P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE PAYMENT_REQ_APPROVE (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_PAY     (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_CANCEL  (P_REQ_ID NUMBER, P_CANCEL_NOTE VARCHAR2 DEFAULT 'Cancelled', P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_DELETE (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2);

  -- ============================================================
  -- Detail CRUD
  -- ============================================================
  PROCEDURE DETAIL_INSERT (
      P_REQ_ID NUMBER, P_EMP_NO NUMBER, P_REQ_AMOUNT NUMBER,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE DETAIL_UPDATE (
      P_DETAIL_ID NUMBER, P_REQ_AMOUNT NUMBER,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  );

  -- تعيين override توزيع لسطر معين (قبل الاحتساب فقط)
  -- P_PROVIDER_TYPE: NULL=افتراضي, 1=بنك فقط, 2=محفظة فقط
  -- P_ACC_ID: حساب محدد (يطغى على PROVIDER_TYPE)
  PROCEDURE DETAIL_SET_OVERRIDE (
      P_DETAIL_ID      NUMBER,
      P_PROVIDER_TYPE  NUMBER,
      P_ACC_ID         NUMBER,
      P_MSG_OUT        OUT VARCHAR2
  );

  PROCEDURE DETAIL_DELETE (P_DETAIL_ID NUMBER, P_MSG_OUT OUT VARCHAR2);

  PROCEDURE DETAIL_APPROVE (P_DETAIL_IDS VARCHAR2, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE DETAIL_PAY     (P_DETAIL_IDS VARCHAR2, P_MSG_OUT OUT VARCHAR2);

  PROCEDURE DETAIL_LIST (
      P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );

  -- ============================================================
  -- Batch Lookup (for list views)
  -- ============================================================
  FUNCTION GET_DETAIL_BATCH_ID (P_DETAIL_ID NUMBER) RETURN NUMBER;
  FUNCTION GET_DETAIL_BATCH_NO (P_DETAIL_ID NUMBER) RETURN VARCHAR2;
  FUNCTION GET_REQ_BATCH_ID    (P_REQ_ID NUMBER) RETURN NUMBER;
  FUNCTION GET_REQ_BATCH_NO    (P_REQ_ID NUMBER) RETURN VARCHAR2;

  -- ============================================================
  -- Queries
  -- ============================================================
  PROCEDURE PAYMENT_REQ_GET  (P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_LOG_LIST (P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_LIST (P_INSQL VARCHAR2, P_OFFSET NUMBER, P_PAGE_SIZE NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_LIST_MASTER (P_INSQL VARCHAR2, P_OFFSET NUMBER, P_PAGE_SIZE NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2);

  PROCEDURE PAYMENT_REQ_SUMMARY_GET (P_EMP_NO NUMBER, P_THE_MONTH NUMBER DEFAULT NULL, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2);

  PROCEDURE PAYMENT_REQ_TOTALS        (P_INSQL VARCHAR2, REF_CUR_OUT OUT SYS_REFCURSOR, MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_TOTALS_BRANCH (P_INSQL VARCHAR2, REF_CUR_OUT OUT SYS_REFCURSOR, MSG_OUT OUT VARCHAR2);

  -- ============================================================
  -- Batch Operations
  -- ============================================================
  PROCEDURE PAYMENT_REQ_APPROVE_BATCH (P_THE_MONTH NUMBER, P_REQ_IDS VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2);
  PROCEDURE PAYMENT_REQ_PAY_BATCH     (P_THE_MONTH NUMBER, P_REQ_IDS VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2);

  -- Batch operations moved to DISBURSEMENT_BATCH_PKG

  -- ============================================================
  -- Bulk (create master + N details)
  -- ============================================================
  PROCEDURE PAYMENT_REQ_BULK_PREVIEW (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER, P_REQ_AMOUNT NUMBER,
      P_PAY_TYPE NUMBER, P_SAL_FROM NUMBER DEFAULT NULL, P_SAL_TO NUMBER DEFAULT NULL,
      P_BRANCH_NO NUMBER DEFAULT NULL,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      -- 🆕 فلتر شهر الاحتساب (اختياري — للنوع 3 فقط، بدون ربط مالي)
      -- ⚠️ مهم: لازم يكون قبل REF_CUR_OUT و MSG_OUT بسبب array_splice في general_get
      P_FILTER_MONTH NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE PAYMENT_REQ_BULK_CREATE (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER, P_REQ_AMOUNT NUMBER,
      P_PAY_TYPE NUMBER, P_SAL_FROM NUMBER DEFAULT NULL, P_SAL_TO NUMBER DEFAULT NULL,
      P_BRANCH_NO NUMBER DEFAULT NULL,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      P_NOTE VARCHAR2 DEFAULT NULL,
      P_MSG_OUT OUT VARCHAR2,
      -- 🆕 فلتر شهر الاحتساب (اختياري — للنوع 3)
      P_FILTER_MONTH NUMBER DEFAULT NULL
  );

  -- ============================================================
  -- Reports
  -- ============================================================
  PROCEDURE PAYMENT_REQ_REPORT (
      P_MONTH_FROM NUMBER, P_MONTH_TO NUMBER DEFAULT NULL,
      P_BRANCH_NO NUMBER DEFAULT NULL, P_REQ_TYPE NUMBER DEFAULT NULL, P_STATUS NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );

  -- 🆕 معلومات أساسية + الحالة المركّبة (1/0/2/4) لكشف الحساب
  PROCEDURE GET_EMP_INFO (
      P_EMP_NO       NUMBER,
      P_REF_CUR_OUT  OUT SYS_REFCURSOR,
      P_MSG_OUT      OUT VARCHAR2
  );

  PROCEDURE EMP_STATEMENT (
      P_EMP_NO NUMBER, P_MONTH_FROM NUMBER DEFAULT NULL, P_MONTH_TO NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );

  -- ============================================================
  -- Month Status (for check_month_status)
  -- ============================================================
  PROCEDURE GET_MONTH_STATUS (
      P_THE_MONTH NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  );

  -- ============================================================
  -- Duplicate Checks
  -- ============================================================
  PROCEDURE CHECK_DUPLICATE_REQUEST (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE CHECK_DUPLICATE_EMP (
      P_EMP_NO NUMBER, P_REQ_ID NUMBER,
      P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE DETAIL_PREVIEW_SINGLE (
      P_REQ_ID NUMBER, P_EMP_NO NUMBER, P_REQ_AMOUNT NUMBER DEFAULT 0,
      P_MSG_OUT OUT VARCHAR2
  );

  PROCEDURE PAYMENT_REQ_UNAPPROVE (P_REQ_ID NUMBER, P_NOTE VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2);

  -- Batch History/Cancel/Reverse moved to DISBURSEMENT_BATCH_PKG

END DISBURSEMENT_PKG;
/
/
