CREATE OR REPLACE PACKAGE BODY GFC_PAK.DISBURSEMENT_PKG AS

  -- ============================================================
  -- Private Helpers
  -- ============================================================

  FUNCTION GET_DEFAULT_MONTH RETURN NUMBER IS
  BEGIN RETURN TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMM')); END;

  FUNCTION BUILD_REQUEST_NO (P_REQ_ID NUMBER) RETURN VARCHAR2 IS
  BEGIN RETURN 'PR-' || LPAD(P_REQ_ID, 5, '0');
  EXCEPTION WHEN OTHERS THEN RETURN TO_CHAR(P_REQ_ID); END;

  FUNCTION GET_EMP_BANK_NAME (P_EMP_NO NUMBER) RETURN VARCHAR2 IS
    V_NAME VARCHAR2(50);
  BEGIN
    SELECT B.NAME INTO V_NAME
      FROM DATA.EMPLOYEES E
      JOIN DATA.BANKS B ON B.NO = E.BANK
     WHERE E.NO = P_EMP_NO;
    RETURN V_NAME;
  EXCEPTION WHEN OTHERS THEN RETURN NULL;
  END;

  FUNCTION GET_EMP_IS_ACTIVE (P_EMP_NO NUMBER) RETURN NUMBER IS
    V NUMBER;
  BEGIN
    SELECT IS_ACTIVE INTO V FROM DATA.EMPLOYEES WHERE NO = P_EMP_NO;
    RETURN NVL(V, 0);
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0; END;

  FUNCTION EMP_HAS_MONTHLY_SALARY (P_EMP_NO NUMBER, P_THE_MONTH NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT COUNT(1) INTO V FROM DATA.EMPLOYEES_MONTH WHERE NO = P_EMP_NO AND THE_MONTH = P_THE_MONTH;
    RETURN CASE WHEN V > 0 THEN 1 ELSE 0 END;
  EXCEPTION WHEN OTHERS THEN RETURN 0; END;

  FUNCTION GET_BANK_NAME (P_BANK_NO NUMBER) RETURN VARCHAR2 IS
    V VARCHAR2(200);
  BEGIN
    SELECT NAME INTO V FROM DATA.BANKS WHERE NO = P_BANK_NO AND ROWNUM = 1;
    RETURN V;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  -- اسم البنك الرئيسي: EMPLOYEES.MASTER_BANKS_EMAIL → MASTER_BANKS_EMAIL.B_NAME
  -- P_EMP_NO: رقم الموظف (مش رقم البنك)
  FUNCTION GET_MASTER_BANK_NAME (P_EMP_NO NUMBER) RETURN VARCHAR2 IS
    V_MB_NO NUMBER; V_NAME VARCHAR2(200);
  BEGIN
    SELECT MASTER_BANKS_EMAIL INTO V_MB_NO FROM DATA.EMPLOYEES WHERE NO = P_EMP_NO AND ROWNUM = 1;
    IF V_MB_NO IS NULL OR V_MB_NO = 0 THEN RETURN NULL; END IF;
    SELECT B_NAME INTO V_NAME FROM DATA.MASTER_BANKS_EMAIL WHERE B_NO = V_MB_NO AND ROWNUM = 1;
    RETURN V_NAME;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; WHEN OTHERS THEN RETURN NULL;
  END;

  -- بنود الاستحقاقات (DATA.CONSTANT مع IS_ADD=1 AND IS_CONSTANT=2)
  PROCEDURE GET_BENEFIT_ITEMS (
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT C.NO, C.NAME FROM DATA.CONSTANT C
       WHERE C.IS_ADD = 1 AND C.IS_CONSTANT = 2
       ORDER BY C.NO;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;

  FUNCTION GET_CONSTANT_NAME (P_CON_NO NUMBER) RETURN VARCHAR2 IS
    V VARCHAR2(200);
  BEGIN
    SELECT NAME INTO V FROM DATA.CONSTANT WHERE NO = P_CON_NO AND ROWNUM = 1;
    RETURN V;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION GET_DUES_TYPE_NAME (P_PAY_TYPE NUMBER) RETURN VARCHAR2 IS
    V VARCHAR2(200);
  BEGIN
    SELECT TYPE_NAME INTO V FROM GFC.SALARY_DUES_TYPES_TB WHERE TYPE_ID = P_PAY_TYPE AND ROWNUM = 1;
    RETURN V;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION GET_DUES_TYPE_LINE (P_PAY_TYPE NUMBER) RETURN NUMBER IS
    V NUMBER;
  BEGIN
    SELECT LINE_TYPE INTO V FROM GFC.SALARY_DUES_TYPES_TB WHERE TYPE_ID = P_PAY_TYPE AND NVL(IS_ACTIVE,1) = 1;
    RETURN V;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION IS_DUES_TYPE_LEAF (P_PAY_TYPE NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT COUNT(1) INTO V FROM GFC.SALARY_DUES_TYPES_TB WHERE PARENT_ID = P_PAY_TYPE AND NVL(IS_ACTIVE,1) = 1;
    RETURN CASE WHEN V > 0 THEN 0 ELSE 1 END;
  EXCEPTION WHEN OTHERS THEN RETURN 0; END;

  PROCEDURE SYNC_MASTER_AMOUNT (P_REQ_ID NUMBER) IS
  BEGIN
    UPDATE GFC.PAYMENT_REQ_TB SET REQ_AMOUNT = (
      SELECT NVL(SUM(REQ_AMOUNT), 0) FROM GFC.PAYMENT_REQ_DETAIL_TB
       WHERE REQ_ID = P_REQ_ID AND DETAIL_STATUS <> C_REQ_STATUS_CANCELLED
    ) WHERE REQ_ID = P_REQ_ID;
  END;

  -- حساب حالة الماستر من حالات الديتيل
  FUNCTION CALC_MASTER_STATUS (P_REQ_ID NUMBER) RETURN NUMBER IS
    V_TOTAL NUMBER; V_DRAFT NUMBER; V_APPROVED NUMBER; V_PAID NUMBER; V_CANCELLED NUMBER; V_BATCH NUMBER;
    V_ACTIVE NUMBER;
  BEGIN
    SELECT COUNT(1),
           COUNT(CASE WHEN DETAIL_STATUS = C_REQ_STATUS_DRAFT THEN 1 END),
           COUNT(CASE WHEN DETAIL_STATUS = C_REQ_STATUS_APPROVED THEN 1 END),
           COUNT(CASE WHEN DETAIL_STATUS = C_REQ_STATUS_PAID THEN 1 END),
           COUNT(CASE WHEN DETAIL_STATUS = C_REQ_STATUS_CANCELLED THEN 1 END),
           COUNT(CASE WHEN DETAIL_STATUS = C_REQ_STATUS_PARTIAL_PAID THEN 1 END)
      INTO V_TOTAL, V_DRAFT, V_APPROVED, V_PAID, V_CANCELLED, V_BATCH
      FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID;

    V_ACTIVE := V_TOTAL - V_CANCELLED;

    IF V_ACTIVE = 0 THEN RETURN C_REQ_STATUS_DRAFT; END IF;

    -- كل الفعّالين مصروفين
    IF V_PAID = V_ACTIVE THEN RETURN C_REQ_STATUS_PAID; END IF;

    -- في مصروفين فعلياً (PAID=2) + غيرهم = مصروف جزئي
    IF V_PAID > 0 THEN RETURN C_REQ_STATUS_PAID; END IF;

    -- كل أو بعض الفعّالين محتسبين (بدفعة) = محتسب
    IF V_BATCH > 0 THEN RETURN C_REQ_STATUS_PARTIAL_PAID; END IF;

    -- كلهم معتمدين
    IF V_APPROVED = V_ACTIVE THEN RETURN C_REQ_STATUS_APPROVED; END IF;

    -- يوجد مسودة + معتمدين = معتمد جزئي
    IF V_APPROVED > 0 THEN RETURN C_REQ_STATUS_PARTIAL_APPROVED; END IF;

    -- كلهم مسودة
    RETURN C_REQ_STATUS_DRAFT;
  END;

  -- ============================================================
  -- LOG — تسجيل كل عملية بجدول PAYMENT_REQ_LOG_TB
  -- ============================================================
  PROCEDURE LOG_ACTION (
      P_REQ_ID NUMBER, P_ACTION VARCHAR2,
      P_OLD_STATUS NUMBER, P_NEW_STATUS NUMBER,
      P_NOTE VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    INSERT INTO GFC.PAYMENT_REQ_LOG_TB (
        LOG_ID, REQ_ID, ACTION, OLD_STATUS, NEW_STATUS,
        ACTION_USER, ACTION_DATE, NOTE, EMP_COUNT, TOTAL_AMOUNT
    ) VALUES (
        PAYMENT_REQ_LOG_SEQ.NEXTVAL, P_REQ_ID, P_ACTION,
        P_OLD_STATUS, P_NEW_STATUS,
        USER_PKG.GET_USER_ID, SYSDATE, SUBSTR(P_NOTE, 1, 500),
        (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID),
        (SELECT NVL(SUM(REQ_AMOUNT),0) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID)
    );
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  -- ============================================================
  -- PREPARE_REQUEST_VALUES — حساب المبالغ حسب نوع الطلب
  -- ============================================================
  PROCEDURE PREPARE_REQUEST_VALUES (
      P_EMP_NO NUMBER, P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER,
      P_REQ_AMOUNT NUMBER, P_PAY_TYPE NUMBER,
      P_DUES_AMOUNT NUMBER, P_EXCLUDE_REQ_ID NUMBER,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      O_THE_MONTH OUT NUMBER, O_REQ_AMOUNT OUT NUMBER, O_PAY_TYPE OUT NUMBER,
      O_DUES_AMOUNT OUT NUMBER, O_LIMIT_FLAG OUT VARCHAR2, O_MSG OUT VARCHAR2
  ) IS
    V_MONTH NUMBER; V_DUE_AVAIL NUMBER;
    V_AMOUNT NUMBER; V_323 NUMBER; V_CALC NUMBER;
  BEGIN
    O_MSG := NULL; O_LIMIT_FLAG := NULL;
    V_MONTH := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
    O_THE_MONTH := V_MONTH; O_REQ_AMOUNT := 0; O_PAY_TYPE := NULL;
    O_DUES_AMOUNT := 0;

    IF P_EMP_NO IS NULL THEN O_MSG := 'رقم الموظف مطلوب'; RETURN; END IF;
    IF P_REQ_TYPE NOT IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM, C_REQ_TYPE_MONTHLY_DUES, C_REQ_TYPE_BENEFITS) THEN O_MSG := 'نوع الطلب غير صحيح'; RETURN; END IF;

    -- منع التكرار: نوع 1 و 2 و 4 بيتنافسو على نفس البند (323) — لا يسمح بأكثر من طلب نشط لنفس الموظف + الشهر
    IF P_REQ_TYPE IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_MONTHLY_DUES) THEN
      DECLARE V_EX_CNT NUMBER;
      BEGIN
        SELECT COUNT(1) INTO V_EX_CNT
          FROM GFC.PAYMENT_REQ_DETAIL_TB D
          JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
         WHERE D.EMP_NO = P_EMP_NO
           AND M.THE_MONTH = V_MONTH
           AND M.REQ_TYPE IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_MONTHLY_DUES)
           AND M.STATUS <> C_REQ_STATUS_CANCELLED
           AND D.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED
           AND (P_EXCLUDE_REQ_ID IS NULL OR M.REQ_ID <> P_EXCLUDE_REQ_ID);
        IF V_EX_CNT > 0 THEN
          O_MSG := 'الموظف موجود مسبقاً في طلب صرف راتب نشط لنفس الشهر';
          RETURN;
        END IF;
      END;
    END IF;

    IF P_REQ_TYPE = C_REQ_TYPE_FULL_SALARY THEN
      IF EMP_HAS_MONTHLY_SALARY(P_EMP_NO, V_MONTH) <> 1 THEN O_MSG := 'لم يتم احتساب الراتب'; RETURN; END IF;
      BEGIN
        SELECT NVL(SUM(S.VALUE), 0) INTO V_AMOUNT
          FROM DATA.SALARY S WHERE S.EMP_NO = P_EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_MONTH;
      EXCEPTION WHEN OTHERS THEN V_AMOUNT := 0; END;
      IF V_AMOUNT <= 0 THEN O_MSG := 'لا يوجد مستحقات (بند 323) لهذا الشهر'; RETURN; END IF;
      V_DUE_AVAIL := GET_EMP_DUES_AVAILABLE(P_EMP_NO, P_EXCLUDE_REQ_ID);
      IF V_AMOUNT > V_DUE_AVAIL THEN O_MSG := 'المبلغ يتجاوز رصيد المستحقات. المتاح=' || TO_CHAR(V_DUE_AVAIL); RETURN; END IF;
      O_REQ_AMOUNT := V_AMOUNT; O_DUES_AMOUNT := V_AMOUNT;
      O_PAY_TYPE := NVL(P_PAY_TYPE, C_DUES_PAYTYPE_SALARY_CONV);
      RETURN;
    END IF;

    IF P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN
      IF EMP_HAS_MONTHLY_SALARY(P_EMP_NO, V_MONTH) <> 1 THEN O_MSG := 'لم يتم احتساب الراتب'; RETURN; END IF;
      IF P_CALC_METHOD NOT IN (C_CALC_PERCENT, C_CALC_FIXED) THEN O_MSG := 'طريقة الاحتساب غير صحيحة'; RETURN; END IF;

      -- قيمة بند 323
      BEGIN
        SELECT NVL(SUM(S.VALUE), 0) INTO V_323
          FROM DATA.SALARY S WHERE S.EMP_NO = P_EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_MONTH;
      EXCEPTION WHEN OTHERS THEN V_323 := 0; END;
      IF V_323 <= 0 THEN O_MSG := 'لا يوجد مستحقات (بند 323) لهذا الشهر'; RETURN; END IF;

      IF P_CALC_METHOD = C_CALC_PERCENT THEN
        IF NVL(P_PERCENT_VAL, 0) < 0 OR P_PERCENT_VAL > 100 THEN O_MSG := 'النسبة 0-100'; RETURN; END IF;
        V_CALC := ROUND(V_323 * P_PERCENT_VAL / 100, 2);
        V_AMOUNT := V_CALC;

        -- تطبيق الحدود (لو محددة) مع تسجيل LIMIT_FLAG
        IF P_L_VALUE IS NOT NULL AND V_CALC < P_L_VALUE THEN
          IF V_323 < P_L_VALUE THEN
            V_AMOUNT := V_323; -- ياخد كله (بند 323 أقل من الحد الأدنى)
            O_LIMIT_FLAG := 'CAP';
          ELSE
            V_AMOUNT := P_L_VALUE; -- يرتفع للحد الأدنى
            O_LIMIT_FLAG := 'MIN';
          END IF;
        END IF;
        IF P_H_VALUE IS NOT NULL AND V_CALC > P_H_VALUE THEN
          V_AMOUNT := P_H_VALUE; -- ينزل للحد الأعلى
          O_LIMIT_FLAG := 'MAX';
        END IF;
      ELSE
        IF NVL(P_REQ_AMOUNT, 0) <= 0 THEN O_MSG := 'المبلغ يجب أن يكون أكبر من صفر'; RETURN; END IF;
        V_AMOUNT := P_REQ_AMOUNT;
      END IF;

      -- نوع 2: المبلغ لا يتجاوز بند 323 (مش المحفظة)
      V_AMOUNT := LEAST(V_AMOUNT, V_323);
      IF V_AMOUNT <= 0 THEN O_MSG := 'لا يوجد مبلغ للصرف'; RETURN; END IF;
      O_REQ_AMOUNT := V_AMOUNT; O_DUES_AMOUNT := V_AMOUNT;
      O_PAY_TYPE := NVL(P_PAY_TYPE, C_DUES_PAYTYPE_SALARY_CONV);
      RETURN;
    END IF;

    IF P_REQ_TYPE = C_REQ_TYPE_LUMP_SUM THEN
      -- نوع 3: دفعة من المستحقات العام — نسبة أو مبلغ ثابت
      V_DUE_AVAIL := GET_EMP_DUES_AVAILABLE(P_EMP_NO, P_EXCLUDE_REQ_ID);
      IF V_DUE_AVAIL <= 0 THEN O_MSG := 'لا يوجد رصيد مستحقات متاح'; RETURN; END IF;

      IF P_CALC_METHOD = C_CALC_PERCENT THEN
        -- نسبة من رصيد المستحقات
        IF NVL(P_PERCENT_VAL, 0) <= 0 OR P_PERCENT_VAL > 100 THEN O_MSG := 'النسبة 1-100'; RETURN; END IF;
        V_AMOUNT := ROUND(V_DUE_AVAIL * P_PERCENT_VAL / 100, 2);
      ELSE
        -- مبلغ ثابت
        IF NVL(P_REQ_AMOUNT, 0) <= 0 THEN O_MSG := 'المبلغ يجب أن يكون أكبر من صفر'; RETURN; END IF;
        V_AMOUNT := P_REQ_AMOUNT;
      END IF;

      IF V_AMOUNT > V_DUE_AVAIL THEN V_AMOUNT := V_DUE_AVAIL; END IF;
      O_REQ_AMOUNT := V_AMOUNT; O_DUES_AMOUNT := V_AMOUNT;
      O_PAY_TYPE := NVL(P_PAY_TYPE, C_DUES_PAYTYPE_PAYMENT);
      RETURN;
    END IF;

    IF P_REQ_TYPE = C_REQ_TYPE_MONTHLY_DUES THEN
      -- نوع 4: المتبقي من بند 323 للشهر المحدد
      IF EMP_HAS_MONTHLY_SALARY(P_EMP_NO, V_MONTH) <> 1 THEN O_MSG := 'لم يتم احتساب الراتب'; RETURN; END IF;
      BEGIN
        SELECT NVL(SUM(S.VALUE), 0) INTO V_323
          FROM DATA.SALARY S WHERE S.EMP_NO = P_EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_MONTH;
      EXCEPTION WHEN OTHERS THEN V_323 := 0; END;
      IF V_323 <= 0 THEN O_MSG := 'لا يوجد مستحقات (بند 323) لهذا الشهر'; RETURN; END IF;

      -- حساب المصروف من نوع 1 و 2 لنفس الشهر
      BEGIN
        SELECT NVL(SUM(D.REQ_AMOUNT), 0) INTO V_CALC
          FROM GFC.PAYMENT_REQ_DETAIL_TB D
          JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
         WHERE D.EMP_NO = P_EMP_NO AND M.THE_MONTH = V_MONTH
           AND M.REQ_TYPE IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_MONTHLY_DUES)
           AND M.STATUS <> C_REQ_STATUS_CANCELLED
           AND D.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED
           AND (P_EXCLUDE_REQ_ID IS NULL OR M.REQ_ID <> P_EXCLUDE_REQ_ID);
      EXCEPTION WHEN OTHERS THEN V_CALC := 0;
      END;
      V_CALC := V_323 - V_CALC;  -- المتبقي = بند 323 - المصروف
      IF V_CALC <= 0 THEN O_MSG := 'لا يوجد متبقي — تم صرف كامل بند 323 (' || TO_CHAR(V_323) || ')'; RETURN; END IF;

      IF NVL(P_REQ_AMOUNT, 0) > 0 THEN
        V_AMOUNT := LEAST(P_REQ_AMOUNT, V_CALC);  -- مبلغ يدوي مع سقف المتبقي
      ELSE
        V_AMOUNT := V_CALC;  -- كل المتبقي
      END IF;

      V_DUE_AVAIL := GET_EMP_DUES_AVAILABLE(P_EMP_NO, P_EXCLUDE_REQ_ID);
      IF V_AMOUNT > V_DUE_AVAIL THEN O_MSG := 'يتجاوز رصيد المستحقات. المتاح=' || TO_CHAR(V_DUE_AVAIL); RETURN; END IF;

      O_REQ_AMOUNT := V_AMOUNT; O_DUES_AMOUNT := V_AMOUNT;
      O_PAY_TYPE := NVL(P_PAY_TYPE, C_DUES_PAYTYPE_SALARY_CONV);
      RETURN;
    END IF;

    IF P_REQ_TYPE = C_REQ_TYPE_BENEFITS THEN
      -- نوع 5: صرف استحقاقات وإضافات (بدون تأثير على SALARY_DUES)
      IF NVL(P_REQ_AMOUNT, 0) <= 0 THEN O_MSG := 'المبلغ يجب أن يكون أكبر من صفر'; RETURN; END IF;
      O_REQ_AMOUNT := P_REQ_AMOUNT;
      O_DUES_AMOUNT := 0;  -- بدون تأثير على المستحقات
      O_PAY_TYPE := P_PAY_TYPE;
      RETURN;
    END IF;

    O_MSG := 'بيانات الطلب غير صحيحة';
  EXCEPTION WHEN OTHERS THEN O_MSG := SQLERRM;
  END PREPARE_REQUEST_VALUES;


  -- ============================================================
  -- Balance Functions
  -- ============================================================

  FUNCTION GET_EMP_NET_SALARY (P_EMP_NO NUMBER, P_THE_MONTH NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(A.NET_SALARY, 0) INTO V FROM DATA.ADMIN A WHERE A.EMP_NO = P_EMP_NO AND A.MONTH = P_THE_MONTH;
    RETURN V;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0; END;

  FUNCTION GET_EMP_DUES_BASE (P_EMP_NO NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(VALUE), 0) INTO V FROM DATA.SALARY
     WHERE EMP_NO = P_EMP_NO AND CON_NO IN (SELECT NO FROM DATA.CONSTANT WHERE CON_G = C_CONSTANT_GROUP_DUES);
    RETURN V;
  EXCEPTION WHEN OTHERS THEN RETURN 0; END;

  FUNCTION GET_EMP_DUES_ADD (P_EMP_NO NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(M.PAY), 0) INTO V
      FROM GFC.SALARY_DUES_TB M JOIN GFC.SALARY_DUES_TYPES_TB T ON T.TYPE_ID = M.PAY_TYPE
     WHERE M.EMP_NO = P_EMP_NO AND NVL(M.STATUS,1) = 1 AND NVL(T.IS_ACTIVE,1) = 1 AND T.LINE_TYPE = C_LINE_ADD;
    RETURN V;
  EXCEPTION WHEN OTHERS THEN RETURN 0; END;

  FUNCTION GET_EMP_DUES_DED (P_EMP_NO NUMBER) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(M.PAY), 0) INTO V
      FROM GFC.SALARY_DUES_TB M JOIN GFC.SALARY_DUES_TYPES_TB T ON T.TYPE_ID = M.PAY_TYPE
     WHERE M.EMP_NO = P_EMP_NO AND NVL(M.STATUS,1) = 1 AND NVL(T.IS_ACTIVE,1) = 1 AND T.LINE_TYPE = C_LINE_DED;
    RETURN V;
  EXCEPTION WHEN OTHERS THEN RETURN 0; END;

  FUNCTION GET_EMP_DUES_RESERVED (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(D.DUES_AMOUNT), 0) INTO V
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
     WHERE D.EMP_NO = P_EMP_NO
       AND D.DETAIL_STATUS IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_PAID)  -- محجوز = معتمد + محتسب (المسودة مش محجوز، المصروف راح على جدول المستحقات)
       AND M.STATUS <> C_REQ_STATUS_CANCELLED
       AND (P_EXCLUDE_REQ_ID IS NULL OR M.REQ_ID <> P_EXCLUDE_REQ_ID);
    RETURN V;
  END;

  FUNCTION GET_EMP_DUES_PAID (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER IS
    V NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(D.DUES_AMOUNT), 0) INTO V
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
     WHERE D.EMP_NO = P_EMP_NO
       AND D.DETAIL_STATUS = C_REQ_STATUS_PAID
       AND M.STATUS <> C_REQ_STATUS_CANCELLED
       AND (P_EXCLUDE_REQ_ID IS NULL OR M.REQ_ID <> P_EXCLUDE_REQ_ID);
    RETURN V;
  END;

  FUNCTION GET_EMP_DUES_AVAILABLE (P_EMP_NO NUMBER, P_EXCLUDE_REQ_ID NUMBER DEFAULT NULL) RETURN NUMBER IS
  BEGIN
    -- المتاح = أساسي + إضافات - خصومات (من SALARY_DUES_TB) - محجوز (معتمد فقط)
    -- المسودة: مش محجوز
    -- المعتمد: محجوز (لسا ما ترحّل)
    -- المصروف: مش محجوز (ترحّل لـ SALARY_DUES_TB كخصم — بينطرح عبر GET_EMP_DUES_DED)
    RETURN GREATEST(GET_EMP_DUES_BASE(P_EMP_NO)
       + GET_EMP_DUES_ADD(P_EMP_NO)
       - GET_EMP_DUES_DED(P_EMP_NO)
       - GET_EMP_DUES_RESERVED(P_EMP_NO, P_EXCLUDE_REQ_ID), 0);
  END;


  -- ============================================================
  -- Master CRUD
  -- ============================================================

  PROCEDURE PAYMENT_REQ_INSERT (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      P_PAY_TYPE NUMBER DEFAULT NULL, P_ENTRY_DATE DATE DEFAULT NULL,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ID NUMBER; V_NO VARCHAR2(50); V_USER NUMBER; V_DUP NUMBER;
    V_MONTH NUMBER := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
  BEGIN
    IF P_REQ_TYPE NOT IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM, C_REQ_TYPE_MONTHLY_DUES, C_REQ_TYPE_BENEFITS) THEN P_MSG_OUT := 'نوع الطلب غير صحيح'; RETURN; END IF;

    -- فحص تكرار: طلب من نفس النوع لنفس الشهر (أنواع 2,3,5 مستثناة — يسمح بأكثر من طلب)
    IF P_REQ_TYPE NOT IN (C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM, C_REQ_TYPE_BENEFITS) THEN
      SELECT COUNT(1) INTO V_DUP FROM GFC.PAYMENT_REQ_TB
       WHERE THE_MONTH = V_MONTH AND REQ_TYPE = P_REQ_TYPE AND STATUS <> C_REQ_STATUS_CANCELLED;
      IF V_DUP > 0 THEN
        P_MSG_OUT := 'يوجد طلب مفتوح من نفس النوع لنفس الشهر (' || TO_CHAR(V_MONTH) || ')';
        RETURN;
      END IF;
    END IF;

    V_ID   := PAYMENT_REQ_SEQ.NEXTVAL;
    V_NO   := BUILD_REQUEST_NO(V_ID);
    V_USER := USER_PKG.GET_USER_ID;

    INSERT INTO GFC.PAYMENT_REQ_TB (
        REQ_ID, REQ_NO, THE_MONTH, REQ_TYPE,
        CALC_METHOD, PERCENT_VAL, L_VALUE, H_VALUE, PAY_TYPE, REQ_AMOUNT,
        STATUS, NOTE, ENTRY_USER, ENTRY_DATE
    ) VALUES (
        V_ID, V_NO, V_MONTH, P_REQ_TYPE,
        CASE WHEN P_REQ_TYPE IN (C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM) THEN P_CALC_METHOD END,
        CASE WHEN P_REQ_TYPE IN (C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM) AND P_CALC_METHOD = C_CALC_PERCENT THEN P_PERCENT_VAL END,
        CASE WHEN P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN P_L_VALUE END,
        CASE WHEN P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN P_H_VALUE END,
        P_PAY_TYPE, 0, C_REQ_STATUS_DRAFT, P_NOTE, V_USER, NVL(P_ENTRY_DATE, SYSDATE)
    );

    LOG_ACTION(V_ID, 'CREATE', NULL, C_REQ_STATUS_DRAFT, P_NOTE);
    P_MSG_OUT := TO_CHAR(V_ID);
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_UPDATE (
      P_REQ_ID NUMBER, P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER,
      P_L_VALUE NUMBER DEFAULT NULL, P_H_VALUE NUMBER DEFAULT NULL,
      P_PAY_TYPE NUMBER DEFAULT NULL,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ST NUMBER; V_USER NUMBER;
    V_OLD_TYPE NUMBER; V_OLD_MONTH NUMBER;
    V_MONTH NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER;
    V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
    V_OK NUMBER := 0; V_ERR NUMBER := 0;
  BEGIN
    SELECT STATUS, REQ_TYPE, THE_MONTH INTO V_ST, V_OLD_TYPE, V_OLD_MONTH
      FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID FOR UPDATE NOWAIT;
    IF V_ST <> C_REQ_STATUS_DRAFT THEN P_MSG_OUT := 'التعديل للمسودة فقط'; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;

    -- تحديث الماستر
    UPDATE GFC.PAYMENT_REQ_TB SET
        THE_MONTH = NVL(P_THE_MONTH, THE_MONTH),
        REQ_TYPE = P_REQ_TYPE,
        CALC_METHOD = CASE WHEN P_REQ_TYPE IN (C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM) THEN P_CALC_METHOD END,
        PERCENT_VAL = CASE WHEN P_REQ_TYPE IN (C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM) AND P_CALC_METHOD = C_CALC_PERCENT THEN P_PERCENT_VAL END,
        L_VALUE = CASE WHEN P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN P_L_VALUE END,
        H_VALUE = CASE WHEN P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN P_H_VALUE END,
        PAY_TYPE = CASE WHEN P_PAY_TYPE IS NOT NULL THEN P_PAY_TYPE ELSE PAY_TYPE END,
        NOTE = P_NOTE, UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
     WHERE REQ_ID = P_REQ_ID;

    -- هل لازم نعيد حساب الموظفين؟
    IF V_OLD_TYPE <> P_REQ_TYPE THEN
      -- تغيير النوع → حذف كل الموظفين (البنية مختلفة)
      DELETE FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID;
      SYNC_MASTER_AMOUNT(P_REQ_ID);
      LOG_ACTION(P_REQ_ID, 'UPDATE_TYPE_CHANGE', V_ST, V_ST, 'نوع قديم=' || V_OLD_TYPE || ' جديد=' || P_REQ_TYPE || ' — تم حذف الموظفين');
      P_MSG_OUT := '2|تم تعديل النوع — الموظفين محذوفين ويجب إعادة إضافتهم';
      RETURN;
    END IF;

    -- نفس النوع — إعادة حساب المبالغ لكل موظف
    FOR D IN (SELECT DETAIL_ID, EMP_NO, REQ_AMOUNT, PAY_TYPE, DUES_AMOUNT
                FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID AND DETAIL_STATUS = C_REQ_STATUS_DRAFT)
    LOOP
      V_MSG := NULL;
      PREPARE_REQUEST_VALUES(D.EMP_NO, P_THE_MONTH, P_REQ_TYPE,
          P_CALC_METHOD, P_PERCENT_VAL, D.REQ_AMOUNT, D.PAY_TYPE,
          D.DUES_AMOUNT, P_REQ_ID, P_L_VALUE, P_H_VALUE,
          V_MONTH, V_AMT, V_PT, V_DA, V_LF, V_MSG);
      IF V_MSG IS NULL THEN
        UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
            REQ_AMOUNT = V_AMT, PAY_TYPE = V_PT, DUES_AMOUNT = V_DA, LIMIT_FLAG = V_LF
         WHERE DETAIL_ID = D.DETAIL_ID;
        V_OK := V_OK + 1;
      ELSE
        V_ERR := V_ERR + 1;
      END IF;
    END LOOP;

    SYNC_MASTER_AMOUNT(P_REQ_ID);
    LOG_ACTION(P_REQ_ID, 'UPDATE', V_ST, V_ST, 'OK=' || V_OK || ' ERR=' || V_ERR);

    IF V_ERR > 0 THEN
      P_MSG_OUT := '1|تم التعديل — ' || V_OK || ' موظف محدّث، ' || V_ERR || ' فشل';
    ELSE
      P_MSG_OUT := '1';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_APPROVE (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2) IS
    R GFC.PAYMENT_REQ_TB%ROWTYPE;
    V_USER NUMBER; V_OK NUMBER := 0; V_ERR NUMBER := 0;
    V_FAIL_LIST VARCHAR2(4000) := '';
    V_MONTH NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER;
    V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
    V_OLD_ST NUMBER; V_NEW_ST NUMBER;
  BEGIN
    SELECT * INTO R FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID FOR UPDATE NOWAIT;
    V_OLD_ST := R.STATUS;
    IF R.STATUS NOT IN (C_REQ_STATUS_DRAFT, C_REQ_STATUS_PARTIAL_APPROVED, C_REQ_STATUS_PARTIAL_PAID) THEN
      P_MSG_OUT := 'لا يمكن الاعتماد بهذه الحالة'; RETURN;
    END IF;
    V_USER := USER_PKG.GET_USER_ID;

    FOR D IN (SELECT * FROM GFC.PAYMENT_REQ_DETAIL_TB
               WHERE REQ_ID = P_REQ_ID AND DETAIL_STATUS = C_REQ_STATUS_DRAFT
               ORDER BY DETAIL_ID) LOOP
      V_MSG := NULL;
      PREPARE_REQUEST_VALUES(D.EMP_NO, R.THE_MONTH, R.REQ_TYPE,
          R.CALC_METHOD, R.PERCENT_VAL, D.REQ_AMOUNT, D.PAY_TYPE,
          D.DUES_AMOUNT, P_REQ_ID, R.L_VALUE, R.H_VALUE,
          V_MONTH, V_AMT, V_PT, V_DA, V_LF, V_MSG);
      IF V_MSG IS NOT NULL THEN
        V_ERR := V_ERR + 1;
        IF LENGTH(V_FAIL_LIST) < 3500 THEN
          V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ': ' || V_MSG || CHR(10);
        END IF;
      ELSE
        UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
            REQ_AMOUNT = V_AMT, PAY_TYPE = V_PT, DUES_AMOUNT = V_DA,
            LIMIT_FLAG = V_LF, DETAIL_STATUS = C_REQ_STATUS_APPROVED
         WHERE DETAIL_ID = D.DETAIL_ID;
        V_OK := V_OK + 1;
      END IF;
    END LOOP;

    IF V_OK = 0 AND V_ERR = 0 THEN P_MSG_OUT := 'لا يوجد موظفين بحاجة اعتماد'; RETURN; END IF;

    V_NEW_ST := CALC_MASTER_STATUS(P_REQ_ID);
    UPDATE GFC.PAYMENT_REQ_TB SET
        STATUS = V_NEW_ST,
        APPROVE_USER = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED) THEN V_USER ELSE APPROVE_USER END,
        APPROVE_DATE = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED) THEN SYSDATE ELSE APPROVE_DATE END,
        UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
     WHERE REQ_ID = P_REQ_ID;

    SYNC_MASTER_AMOUNT(P_REQ_ID);
    LOG_ACTION(P_REQ_ID, 'APPROVE_ALL', V_OLD_ST, V_NEW_ST, 'OK=' || V_OK || ' ERR=' || V_ERR);

    IF V_ERR > 0 AND V_OK > 0 THEN
      P_MSG_OUT := '1|تم اعتماد ' || V_OK || ' — فشل ' || V_ERR || ':' || CHR(10) || V_FAIL_LIST;
    ELSIF V_ERR > 0 THEN
      P_MSG_OUT := 'فشل اعتماد ' || V_ERR || ' موظف:' || CHR(10) || V_FAIL_LIST;
    ELSE
      P_MSG_OUT := '1';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_PAY (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2) IS
    V_IDS VARCHAR2(32767) := '';
  BEGIN
    -- صرف كل الديتيل المعتمدين
    FOR D IN (SELECT DETAIL_ID FROM GFC.PAYMENT_REQ_DETAIL_TB
               WHERE REQ_ID = P_REQ_ID AND DETAIL_STATUS = C_REQ_STATUS_APPROVED) LOOP
      V_IDS := V_IDS || CASE WHEN V_IDS IS NOT NULL THEN ',' END || TO_CHAR(D.DETAIL_ID);
    END LOOP;
    IF V_IDS IS NULL THEN P_MSG_OUT := 'لا يوجد موظفين معتمدين للصرف'; RETURN; END IF;
    DETAIL_PAY(V_IDS, P_MSG_OUT);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_CANCEL (P_REQ_ID NUMBER, P_CANCEL_NOTE VARCHAR2 DEFAULT 'Cancelled', P_MSG_OUT OUT VARCHAR2) IS
    V_ST NUMBER; V_USER NUMBER; V_BATCH_CNT NUMBER;
    V_REVERSED NUMBER := 0; V_DETAIL_NOTE VARCHAR2(4000) := '';
  BEGIN
    SELECT STATUS INTO V_ST FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID FOR UPDATE NOWAIT;
    IF V_ST = C_REQ_STATUS_CANCELLED THEN P_MSG_OUT := 'الطلب ملغي مسبقا'; RETURN; END IF;

    -- فحص: مش محتسب بدفعة نشطة
    SELECT COUNT(1) INTO V_BATCH_CNT
      FROM GFC.PAYMENT_BATCH_LINK_TB L
      JOIN GFC.PAYMENT_BATCH_TB B ON B.BATCH_ID = L.BATCH_ID
      JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
     WHERE D.REQ_ID = P_REQ_ID AND B.STATUS <> 9;
    IF V_BATCH_CNT > 0 THEN P_MSG_OUT := 'الطلب محتسب ضمن دفعة — يجب فك الاحتساب أولاً'; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;

    -- عكس المصروف من دفتر المستحقات (كل ديتيل فيه قيد فعّال)
    FOR D IN (SELECT D.DETAIL_ID, D.EMP_NO, D.POST_SERIAL_DUES, D.DETAIL_STATUS, D.REQ_AMOUNT
                FROM GFC.PAYMENT_REQ_DETAIL_TB D
               WHERE D.REQ_ID = P_REQ_ID
                 AND D.POST_SERIAL_DUES IS NOT NULL
                 AND D.DETAIL_STATUS = C_REQ_STATUS_PAID)
    LOOP
      UPDATE GFC.SALARY_DUES_TB SET STATUS = 0, CANCEL_USER = V_USER, CANCEL_DATE = SYSDATE,
          CANCEL_NOTE = SUBSTR(P_CANCEL_NOTE, 1, 200)
       WHERE SERIAL = D.POST_SERIAL_DUES AND NVL(STATUS,1) = 1;
      IF SQL%ROWCOUNT > 0 THEN
        V_REVERSED := V_REVERSED + 1;
        V_DETAIL_NOTE := V_DETAIL_NOTE || 'EMP=' || D.EMP_NO || ' SER=' || D.POST_SERIAL_DUES || ' AMT=' || D.REQ_AMOUNT || '; ';
      END IF;
    END LOOP;

    -- إلغاء كل الديتيل + مسح POST_SERIAL_DUES
    UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
        DETAIL_STATUS = C_REQ_STATUS_CANCELLED,
        POST_SERIAL_DUES = NULL
     WHERE REQ_ID = P_REQ_ID
       AND DETAIL_STATUS <> C_REQ_STATUS_CANCELLED;

    UPDATE GFC.PAYMENT_REQ_TB SET
        STATUS = C_REQ_STATUS_CANCELLED,
        CANCEL_USER = V_USER, CANCEL_DATE = SYSDATE,
        CANCEL_NOTE = SUBSTR(P_CANCEL_NOTE, 1, 200),
        UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
     WHERE REQ_ID = P_REQ_ID;

    SYNC_MASTER_AMOUNT(P_REQ_ID);
    LOG_ACTION(P_REQ_ID, 'CANCEL', V_ST, C_REQ_STATUS_CANCELLED,
        P_CANCEL_NOTE || CASE WHEN V_REVERSED > 0 THEN ' | عكس ' || V_REVERSED || ' قيد: ' || SUBSTR(V_DETAIL_NOTE, 1, 300) END);
    P_MSG_OUT := '1';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_DELETE (P_REQ_ID NUMBER, P_MSG_OUT OUT VARCHAR2) IS
    V_ST NUMBER; V_CNT NUMBER; V_BATCH_CNT NUMBER;
  BEGIN
    SELECT STATUS INTO V_ST FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID FOR UPDATE NOWAIT;

    IF V_ST IN (C_REQ_STATUS_PAID, C_REQ_STATUS_PARTIAL_PAID) THEN
      P_MSG_OUT := 'لا يمكن حذف طلب فيه مصروفين — استخدم الإلغاء';
      RETURN;
    END IF;

    -- فحص: مش محتسب بدفعة نشطة
    SELECT COUNT(1) INTO V_BATCH_CNT
      FROM GFC.PAYMENT_BATCH_LINK_TB L
      JOIN GFC.PAYMENT_BATCH_TB B ON B.BATCH_ID = L.BATCH_ID
      JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
     WHERE D.REQ_ID = P_REQ_ID AND B.STATUS <> 9;
    IF V_BATCH_CNT > 0 THEN P_MSG_OUT := 'الطلب محتسب ضمن دفعة — يجب فك الاحتساب أولاً'; RETURN; END IF;

    LOG_ACTION(P_REQ_ID, 'DELETE', V_ST, NULL);

    -- حذف ربط الدفعات (الملغية) قبل حذف الديتيل
    DELETE FROM GFC.PAYMENT_BATCH_LINK_TB WHERE DETAIL_ID IN (
        SELECT DETAIL_ID FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID
    );
    DELETE FROM GFC.PAYMENT_REQ_LOG_TB WHERE REQ_ID = P_REQ_ID;
    DELETE FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = P_REQ_ID;
    V_CNT := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID;

    P_MSG_OUT := '1|' || TO_CHAR(V_CNT);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- Detail CRUD
  -- ============================================================

  PROCEDURE DETAIL_INSERT (
      P_REQ_ID NUMBER, P_EMP_NO NUMBER, P_REQ_AMOUNT NUMBER,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ST NUMBER; V_TYPE NUMBER; V_CALC NUMBER; V_PCT NUMBER; V_MONTH NUMBER;
    V_MASTER_PT NUMBER; V_LV NUMBER; V_HV NUMBER;
    V_USER NUMBER; V_ID NUMBER;
    V_MONTH2 NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER; V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
    V_EX NUMBER := 0;
  BEGIN
    SELECT STATUS, REQ_TYPE, CALC_METHOD, PERCENT_VAL, THE_MONTH, PAY_TYPE, L_VALUE, H_VALUE
      INTO V_ST, V_TYPE, V_CALC, V_PCT, V_MONTH, V_MASTER_PT, V_LV, V_HV
      FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID;

    IF V_ST NOT IN (C_REQ_STATUS_DRAFT, C_REQ_STATUS_PARTIAL_APPROVED, C_REQ_STATUS_PARTIAL_PAID) THEN
      P_MSG_OUT := 'لا يمكن إضافة موظف بهذه الحالة'; RETURN;
    END IF;

    SELECT COUNT(1) INTO V_EX FROM GFC.PAYMENT_REQ_DETAIL_TB
     WHERE REQ_ID = P_REQ_ID AND EMP_NO = P_EMP_NO;
    IF V_EX > 0 THEN P_MSG_OUT := 'الموظف موجود مسبقا في هذا الطلب'; RETURN; END IF;

    -- فحص تكرار: الموظف في طلب آخر من نفس النوع لنفس الشهر
    V_EX := 0;
    SELECT COUNT(1) INTO V_EX FROM GFC.PAYMENT_REQ_DETAIL_TB D
     JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
     WHERE D.EMP_NO = P_EMP_NO AND D.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED
       AND M.STATUS <> C_REQ_STATUS_CANCELLED
       AND M.THE_MONTH = V_MONTH AND M.REQ_TYPE = V_TYPE
       AND M.REQ_ID <> P_REQ_ID;
    IF V_EX > 0 THEN P_MSG_OUT := 'الموظف موجود في طلب آخر من نفس النوع لنفس الشهر'; RETURN; END IF;

    PREPARE_REQUEST_VALUES(P_EMP_NO, V_MONTH, V_TYPE,
        V_CALC, V_PCT, P_REQ_AMOUNT, V_MASTER_PT,
        NULL, P_REQ_ID, V_LV, V_HV,
        V_MONTH2, V_AMT, V_PT, V_DA, V_LF, V_MSG);
    IF V_MSG IS NOT NULL THEN P_MSG_OUT := V_MSG; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;
    V_ID   := PAYMENT_REQ_DETAIL_SEQ.NEXTVAL;

    INSERT INTO GFC.PAYMENT_REQ_DETAIL_TB (
        DETAIL_ID, REQ_ID, EMP_NO, REQ_AMOUNT, DUES_AMOUNT,
        PAY_TYPE, LIMIT_FLAG, DETAIL_STATUS, NOTE, ENTRY_DATE, ENTRY_USER
    ) VALUES (
        V_ID, P_REQ_ID, P_EMP_NO, V_AMT, V_DA,
        V_PT, V_LF, C_REQ_STATUS_DRAFT, P_NOTE, SYSDATE, V_USER
    );

    SYNC_MASTER_AMOUNT(P_REQ_ID);
    -- تحديث حالة الماستر (إضافة مسودة لطلب جزئي)
    IF V_ST <> C_REQ_STATUS_DRAFT THEN
      DECLARE V_NEW_ST NUMBER;
      BEGIN
        V_NEW_ST := CALC_MASTER_STATUS(P_REQ_ID);
        UPDATE GFC.PAYMENT_REQ_TB SET
            STATUS = V_NEW_ST,
            UPDATE_USER = USER_PKG.GET_USER_ID, UPDATE_DATE = SYSDATE
         WHERE REQ_ID = P_REQ_ID;
      END;
    END IF;
    LOG_ACTION(P_REQ_ID, 'ADD_EMP', NULL, NULL, 'EMP_NO=' || TO_CHAR(P_EMP_NO) || ' AMT=' || TO_CHAR(V_AMT));
    P_MSG_OUT := TO_CHAR(V_ID);
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE DETAIL_UPDATE (
      P_DETAIL_ID NUMBER, P_REQ_AMOUNT NUMBER,
      P_NOTE VARCHAR2, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_REQ_ID NUMBER; V_EMP_NO NUMBER; V_ST NUMBER;
    V_TYPE NUMBER; V_CALC NUMBER; V_PCT NUMBER; V_MONTH NUMBER; V_LV NUMBER; V_HV NUMBER;
    V_MONTH2 NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER; V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
  BEGIN
    SELECT D.REQ_ID, D.EMP_NO, M.STATUS, M.REQ_TYPE, M.CALC_METHOD, M.PERCENT_VAL, M.THE_MONTH, M.L_VALUE, M.H_VALUE
      INTO V_REQ_ID, V_EMP_NO, V_ST, V_TYPE, V_CALC, V_PCT, V_MONTH, V_LV, V_HV
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
     WHERE D.DETAIL_ID = P_DETAIL_ID FOR UPDATE OF D.DETAIL_ID NOWAIT;

    IF V_ST <> C_REQ_STATUS_DRAFT THEN P_MSG_OUT := 'التعديل للمسودة فقط'; RETURN; END IF;

    PREPARE_REQUEST_VALUES(V_EMP_NO, V_MONTH, V_TYPE,
        V_CALC, V_PCT, P_REQ_AMOUNT, NULL,
        NULL, V_REQ_ID, V_LV, V_HV,
        V_MONTH2, V_AMT, V_PT, V_DA, V_LF, V_MSG);
    IF V_MSG IS NOT NULL THEN P_MSG_OUT := V_MSG; RETURN; END IF;

    UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
        REQ_AMOUNT = V_AMT, DUES_AMOUNT = V_DA,
        PAY_TYPE = V_PT, LIMIT_FLAG = V_LF, NOTE = P_NOTE
     WHERE DETAIL_ID = P_DETAIL_ID;

    SYNC_MASTER_AMOUNT(V_REQ_ID);
    P_MSG_OUT := '1';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'السجل غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE DETAIL_DELETE (P_DETAIL_ID NUMBER, P_MSG_OUT OUT VARCHAR2) IS
    V_REQ_ID NUMBER; V_EMP_NO NUMBER; V_DS NUMBER; V_MS NUMBER;
    V_USER NUMBER; V_SERIAL NUMBER; V_NEW_ST NUMBER;
  BEGIN
    SELECT D.REQ_ID, D.EMP_NO, D.DETAIL_STATUS, D.POST_SERIAL_DUES, M.STATUS
      INTO V_REQ_ID, V_EMP_NO, V_DS, V_SERIAL, V_MS
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
     WHERE D.DETAIL_ID = P_DETAIL_ID;

    -- الملغى مسبقاً
    IF V_DS = C_REQ_STATUS_CANCELLED THEN P_MSG_OUT := 'الموظف ملغى مسبقاً'; RETURN; END IF;

    -- الماستر ملغى بالكامل
    IF V_MS = C_REQ_STATUS_CANCELLED THEN P_MSG_OUT := 'الطلب ملغى'; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;

    -- مسودة: حذف فعلي
    IF V_DS = C_REQ_STATUS_DRAFT THEN
      DELETE FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE DETAIL_ID = P_DETAIL_ID;
      SYNC_MASTER_AMOUNT(V_REQ_ID);
      V_NEW_ST := CALC_MASTER_STATUS(V_REQ_ID);
      UPDATE GFC.PAYMENT_REQ_TB SET STATUS = V_NEW_ST, UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE WHERE REQ_ID = V_REQ_ID;
      LOG_ACTION(V_REQ_ID, 'REMOVE_EMP', V_MS, V_NEW_ST, 'EMP_NO=' || TO_CHAR(V_EMP_NO) || ' (حذف)');
      P_MSG_OUT := '1';
      RETURN;
    END IF;

    -- معتمد: إلغاء الاعتماد → يرجع مسودة
    IF V_DS = C_REQ_STATUS_APPROVED THEN
      UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET DETAIL_STATUS = C_REQ_STATUS_DRAFT WHERE DETAIL_ID = P_DETAIL_ID;
      V_NEW_ST := CALC_MASTER_STATUS(V_REQ_ID);
      UPDATE GFC.PAYMENT_REQ_TB SET STATUS = V_NEW_ST, UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE WHERE REQ_ID = V_REQ_ID;
      LOG_ACTION(V_REQ_ID, 'UNAPPROVE_EMP', V_MS, V_NEW_ST, 'EMP_NO=' || TO_CHAR(V_EMP_NO));
      P_MSG_OUT := '1';
      RETURN;
    END IF;

    -- مصروف: عكس القيد من دفتر المستحقات + إرجاع لمعتمد
    IF V_DS = C_REQ_STATUS_PAID THEN
      IF V_SERIAL IS NOT NULL THEN
        UPDATE GFC.SALARY_DUES_TB SET STATUS = 0, CANCEL_USER = V_USER, CANCEL_DATE = SYSDATE,
            CANCEL_NOTE = 'عكس من طلب ' || TO_CHAR(V_REQ_ID)
         WHERE SERIAL = V_SERIAL AND NVL(STATUS,1) = 1;
      END IF;
      UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET DETAIL_STATUS = C_REQ_STATUS_APPROVED, POST_SERIAL_DUES = NULL
       WHERE DETAIL_ID = P_DETAIL_ID;
      V_NEW_ST := CALC_MASTER_STATUS(V_REQ_ID);
      UPDATE GFC.PAYMENT_REQ_TB SET STATUS = V_NEW_ST, UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE WHERE REQ_ID = V_REQ_ID;
      LOG_ACTION(V_REQ_ID, 'UNPAY_EMP', V_MS, V_NEW_ST, 'EMP_NO=' || TO_CHAR(V_EMP_NO) || ' SERIAL=' || TO_CHAR(V_SERIAL));
      P_MSG_OUT := '1';
      RETURN;
    END IF;

    P_MSG_OUT := 'حالة غير معروفة';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'السجل غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- صرف جزئي: اعتماد موظفين محددين
  -- ============================================================
  PROCEDURE DETAIL_APPROVE (P_DETAIL_IDS VARCHAR2, P_MSG_OUT OUT VARCHAR2) IS
    R GFC.PAYMENT_REQ_TB%ROWTYPE;
    V_REQ_ID NUMBER := NULL; V_USER NUMBER;
    V_MONTH NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER; V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
    V_OK NUMBER := 0; V_ERR NUMBER := 0; V_FAIL_LIST VARCHAR2(4000) := '';
    V_OLD_ST NUMBER; V_NEW_ST NUMBER;
  BEGIN
    V_USER := USER_PKG.GET_USER_ID;

    FOR D IN (SELECT * FROM GFC.PAYMENT_REQ_DETAIL_TB
               WHERE INSTR(',' || P_DETAIL_IDS || ',', ',' || TO_CHAR(DETAIL_ID) || ',') > 0
               ORDER BY DETAIL_ID)
    LOOP
      -- تحقق أول مرة: كل الديتيل لازم من نفس الطلب
      IF V_REQ_ID IS NULL THEN
        V_REQ_ID := D.REQ_ID;
        SELECT * INTO R FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = V_REQ_ID FOR UPDATE NOWAIT;
        V_OLD_ST := R.STATUS;
        IF R.STATUS NOT IN (C_REQ_STATUS_DRAFT, C_REQ_STATUS_PARTIAL_APPROVED, C_REQ_STATUS_PARTIAL_PAID) THEN
          P_MSG_OUT := 'لا يمكن الاعتماد بهذه الحالة'; RETURN;
        END IF;
      ELSIF D.REQ_ID <> V_REQ_ID THEN
        P_MSG_OUT := 'كل الموظفين لازم من نفس الطلب'; RETURN;
      END IF;

      IF D.DETAIL_STATUS <> C_REQ_STATUS_DRAFT THEN
        V_ERR := V_ERR + 1;
        V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ' - ' || EMP_PKG.GET_EMP_NAME(D.EMP_NO) || ': حالة غير مسودة' || CHR(10);
      ELSE
        V_MSG := NULL;
        PREPARE_REQUEST_VALUES(D.EMP_NO, R.THE_MONTH, R.REQ_TYPE,
            R.CALC_METHOD, R.PERCENT_VAL, D.REQ_AMOUNT, D.PAY_TYPE,
            D.DUES_AMOUNT, V_REQ_ID, R.L_VALUE, R.H_VALUE,
            V_MONTH, V_AMT, V_PT, V_DA, V_LF, V_MSG);
        IF V_MSG IS NOT NULL THEN
          V_ERR := V_ERR + 1;
          V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ' - ' || EMP_PKG.GET_EMP_NAME(D.EMP_NO) || ': ' || V_MSG || CHR(10);
        ELSE
          UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
              REQ_AMOUNT = V_AMT, PAY_TYPE = V_PT, DUES_AMOUNT = V_DA,
              LIMIT_FLAG = V_LF, DETAIL_STATUS = C_REQ_STATUS_APPROVED
           WHERE DETAIL_ID = D.DETAIL_ID;
          V_OK := V_OK + 1;
        END IF;
      END IF;
    END LOOP;

    IF V_REQ_ID IS NULL THEN P_MSG_OUT := 'لم يتم العثور على سجلات'; RETURN; END IF;

    -- تحديث حالة الماستر
    V_NEW_ST := CALC_MASTER_STATUS(V_REQ_ID);
    UPDATE GFC.PAYMENT_REQ_TB SET
        STATUS = V_NEW_ST,
        APPROVE_USER = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED) THEN V_USER ELSE APPROVE_USER END,
        APPROVE_DATE = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED) THEN SYSDATE ELSE APPROVE_DATE END,
        UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
     WHERE REQ_ID = V_REQ_ID;

    SYNC_MASTER_AMOUNT(V_REQ_ID);
    LOG_ACTION(V_REQ_ID, 'APPROVE', V_OLD_ST, V_NEW_ST, 'OK=' || V_OK || ' ERR=' || V_ERR);

    IF V_ERR > 0 AND V_OK > 0 THEN
      P_MSG_OUT := '1|تم اعتماد ' || V_OK || ' موظف - فشل ' || V_ERR || ':' || CHR(10) || SUBSTR(V_FAIL_LIST, 1, 3000);
    ELSIF V_ERR > 0 THEN
      P_MSG_OUT := 'فشل اعتماد ' || V_ERR || ' موظف:' || CHR(10) || SUBSTR(V_FAIL_LIST, 1, 3500);
    ELSE
      P_MSG_OUT := '1';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- صرف جزئي: صرف موظفين محددين
  -- ============================================================
  PROCEDURE DETAIL_PAY (P_DETAIL_IDS VARCHAR2, P_MSG_OUT OUT VARCHAR2) IS
    R GFC.PAYMENT_REQ_TB%ROWTYPE;
    V_REQ_ID NUMBER := NULL; V_USER NUMBER; V_DUES_SERIAL NUMBER; V_LF VARCHAR2(3);
    V_MONTH NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER; V_MSG VARCHAR2(4000);
    V_OK NUMBER := 0; V_ERR NUMBER := 0; V_FAIL_LIST VARCHAR2(4000) := '';
    V_OLD_ST NUMBER; V_NEW_ST NUMBER;
  BEGIN
    V_USER := USER_PKG.GET_USER_ID;

    FOR D IN (SELECT * FROM GFC.PAYMENT_REQ_DETAIL_TB
               WHERE INSTR(',' || P_DETAIL_IDS || ',', ',' || TO_CHAR(DETAIL_ID) || ',') > 0
               ORDER BY DETAIL_ID)
    LOOP
      IF V_REQ_ID IS NULL THEN
        V_REQ_ID := D.REQ_ID;
        SELECT * INTO R FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = V_REQ_ID FOR UPDATE NOWAIT;
        V_OLD_ST := R.STATUS;
        IF R.STATUS NOT IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED, C_REQ_STATUS_PARTIAL_PAID) THEN
          P_MSG_OUT := 'الصرف للمعتمد فقط'; RETURN;
        END IF;
      ELSIF D.REQ_ID <> V_REQ_ID THEN
        P_MSG_OUT := 'كل الموظفين لازم من نفس الطلب'; RETURN;
      END IF;

      IF D.DETAIL_STATUS <> C_REQ_STATUS_APPROVED THEN
        V_ERR := V_ERR + 1;
        V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ' - ' || EMP_PKG.GET_EMP_NAME(D.EMP_NO) || ': حالة غير معتمد' || CHR(10);
      ELSE
        V_MSG := NULL;
        PREPARE_REQUEST_VALUES(D.EMP_NO, R.THE_MONTH, R.REQ_TYPE,
            R.CALC_METHOD, R.PERCENT_VAL, D.REQ_AMOUNT, D.PAY_TYPE,
            D.DUES_AMOUNT, V_REQ_ID, R.L_VALUE, R.H_VALUE,
            V_MONTH, V_AMT, V_PT, V_DA, V_LF, V_MSG);
        IF V_MSG IS NOT NULL THEN
          V_ERR := V_ERR + 1;
          V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ' - ' || EMP_PKG.GET_EMP_NAME(D.EMP_NO) || ': ' || V_MSG || CHR(10);
        ELSE
          -- نوع 5: بدون ترحيل لجدول المستحقات
          IF R.REQ_TYPE <> C_REQ_TYPE_BENEFITS THEN
            V_DUES_SERIAL := SALARY_DUES_TB_SEQ.NEXTVAL;
            INSERT INTO GFC.SALARY_DUES_TB (
                SERIAL, EMP_NO, THE_MONTH, PAY_TYPE, PAY, THE_DATE, NOTE, ENTRY_USER, STATUS
            ) VALUES (
                V_DUES_SERIAL, D.EMP_NO, V_MONTH, V_PT, V_DA, SYSDATE,
                SUBSTR('REQ_ID=' || TO_CHAR(V_REQ_ID) || ' D=' || TO_CHAR(D.DETAIL_ID) || ' - ' || NVL(D.NOTE, 'Payment'), 1, 200),
                V_USER, 1
            );
          ELSE
            V_DUES_SERIAL := NULL;
          END IF;
          UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
              REQ_AMOUNT = V_AMT, PAY_TYPE = V_PT, DUES_AMOUNT = V_DA,
              DETAIL_STATUS = C_REQ_STATUS_PAID, POST_SERIAL_DUES = V_DUES_SERIAL
           WHERE DETAIL_ID = D.DETAIL_ID;
          V_OK := V_OK + 1;
        END IF;
      END IF;
    END LOOP;

    IF V_REQ_ID IS NULL THEN P_MSG_OUT := 'لم يتم العثور على سجلات'; RETURN; END IF;

    V_NEW_ST := CALC_MASTER_STATUS(V_REQ_ID);
    UPDATE GFC.PAYMENT_REQ_TB SET
        STATUS = V_NEW_ST,
        PAY_USER = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_PAID, C_REQ_STATUS_PARTIAL_PAID) THEN V_USER ELSE PAY_USER END,
        PAY_DATE = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_PAID, C_REQ_STATUS_PARTIAL_PAID) THEN SYSDATE ELSE PAY_DATE END,
        UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
     WHERE REQ_ID = V_REQ_ID;

    SYNC_MASTER_AMOUNT(V_REQ_ID);
    LOG_ACTION(V_REQ_ID, 'PAY', V_OLD_ST, V_NEW_ST, 'OK=' || V_OK || ' ERR=' || V_ERR);

    IF V_ERR > 0 AND V_OK > 0 THEN
      P_MSG_OUT := '1|تم صرف ' || V_OK || ' موظف - فشل ' || V_ERR || ':' || CHR(10) || SUBSTR(V_FAIL_LIST, 1, 3000);
    ELSIF V_ERR > 0 THEN
      P_MSG_OUT := 'فشل صرف ' || V_ERR || ' موظف:' || CHR(10) || SUBSTR(V_FAIL_LIST, 1, 3500);
    ELSE
      P_MSG_OUT := '1';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE DETAIL_LIST (
      P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT D.DETAIL_ID, D.REQ_ID, D.EMP_NO,
             E.NAME AS EMP_NAME,
             EMP_PKG.GET_EMP_BRANCH_NAME(D.EMP_NO) AS BRANCH_NAME,
             D.REQ_AMOUNT, D.DUES_AMOUNT,
             D.PAY_TYPE, D.LIMIT_FLAG, D.DETAIL_STATUS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, D.DETAIL_STATUS) AS DETAIL_STATUS_NAME,
             CASE WHEN M.REQ_TYPE = C_REQ_TYPE_BENEFITS THEN GET_CONSTANT_NAME(D.PAY_TYPE) ELSE GET_DUES_TYPE_NAME(D.PAY_TYPE) END AS PAY_TYPE_NAME,
             D.POST_SERIAL_DUES, D.NOTE
        FROM GFC.PAYMENT_REQ_DETAIL_TB D
        JOIN DATA.EMPLOYEES E ON E.NO = D.EMP_NO
        JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
       WHERE D.REQ_ID = P_REQ_ID
       ORDER BY D.EMP_NO;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- Batch Lookup
  -- ============================================================
  FUNCTION GET_DETAIL_BATCH_ID (P_DETAIL_ID NUMBER) RETURN NUMBER IS
    V_ID NUMBER;
  BEGIN
    SELECT L.BATCH_ID INTO V_ID
    FROM GFC.PAYMENT_BATCH_LINK_TB L
    JOIN GFC.PAYMENT_BATCH_TB B ON B.BATCH_ID = L.BATCH_ID
    WHERE L.DETAIL_ID = P_DETAIL_ID AND B.STATUS <> 9 AND ROWNUM = 1;
    RETURN V_ID;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION GET_DETAIL_BATCH_NO (P_DETAIL_ID NUMBER) RETURN VARCHAR2 IS
    V_NO VARCHAR2(20);
  BEGIN
    SELECT B.BATCH_NO INTO V_NO
    FROM GFC.PAYMENT_BATCH_TB B
    JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.BATCH_ID = B.BATCH_ID
    WHERE L.DETAIL_ID = P_DETAIL_ID AND B.STATUS <> 9 AND ROWNUM = 1;
    RETURN V_NO;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION GET_REQ_BATCH_ID (P_REQ_ID NUMBER) RETURN NUMBER IS
    V_ID NUMBER;
  BEGIN
    SELECT MAX(L.BATCH_ID) INTO V_ID
    FROM GFC.PAYMENT_BATCH_LINK_TB L
    JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
    JOIN GFC.PAYMENT_BATCH_TB B ON B.BATCH_ID = L.BATCH_ID
    WHERE D.REQ_ID = P_REQ_ID AND B.STATUS <> 9;
    RETURN V_ID;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

  FUNCTION GET_REQ_BATCH_NO (P_REQ_ID NUMBER) RETURN VARCHAR2 IS
    V_ID NUMBER;
    V_NO VARCHAR2(20);
  BEGIN
    V_ID := GET_REQ_BATCH_ID(P_REQ_ID);
    IF V_ID IS NULL THEN RETURN NULL; END IF;
    SELECT BATCH_NO INTO V_NO FROM GFC.PAYMENT_BATCH_TB WHERE BATCH_ID = V_ID;
    RETURN V_NO;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;


  -- ============================================================
  -- Queries
  -- ============================================================

  PROCEDURE PAYMENT_REQ_LOG_LIST (P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT L.LOG_ID, L.REQ_ID, L.ACTION, L.OLD_STATUS, L.NEW_STATUS,
             TO_CHAR(L.ACTION_DATE, 'DD/MM/YYYY HH24:MI') AS ACTION_DATE,
             L.NOTE, L.EMP_COUNT, L.TOTAL_AMOUNT,
             USER_PKG.GET_USER_NAME(L.ACTION_USER) AS ACTION_USER_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, L.OLD_STATUS) AS OLD_STATUS_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, L.NEW_STATUS) AS NEW_STATUS_NAME
        FROM GFC.PAYMENT_REQ_LOG_TB L
       WHERE L.REQ_ID = P_REQ_ID
       ORDER BY L.ACTION_DATE DESC, L.LOG_ID DESC;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;

  PROCEDURE PAYMENT_REQ_GET (P_REQ_ID NUMBER, P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT M.*,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538, M.REQ_TYPE)    AS REQ_TYPE_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(540, M.CALC_METHOD) AS CALC_METHOD_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, M.STATUS)      AS STATUS_NAME,
             CASE WHEN M.REQ_TYPE = C_REQ_TYPE_BENEFITS THEN GET_CONSTANT_NAME(M.PAY_TYPE) ELSE GET_DUES_TYPE_NAME(M.PAY_TYPE) END AS PAY_TYPE_NAME,
             USER_PKG.GET_USER_NAME(M.ENTRY_USER) AS ENTRY_USER_NAME,
             USER_PKG.GET_USER_NAME(M.APPROVE_USER) AS APPROVE_USER_NAME,
             (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = M.REQ_ID) AS EMP_COUNT,
             (SELECT NVL(SUM(REQ_AMOUNT),0) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = M.REQ_ID) AS TOTAL_AMOUNT
        FROM GFC.PAYMENT_REQ_TB M
       WHERE M.REQ_ID = P_REQ_ID;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_LIST (P_INSQL VARCHAR2, P_OFFSET NUMBER, P_PAGE_SIZE NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2) IS
    XSQL VARCHAR2(32767);
  BEGIN
    XSQL := 'SELECT * FROM (
      SELECT
        M.REQ_ID, M.REQ_NO, M.THE_MONTH, M.REQ_TYPE, M.STATUS,
        TO_CHAR(M.ENTRY_DATE,''DD/MM/YYYY'') AS ENTRY_DATE, TO_CHAR(M.PAY_DATE,''DD/MM/YYYY'') AS PAY_DATE, M.NOTE AS MASTER_NOTE,
        SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538,M.REQ_TYPE) AS REQ_TYPE_NAME,
        SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541,M.STATUS) AS STATUS_NAME,
        D.DETAIL_ID, D.EMP_NO,
        EMP_PKG.GET_EMP_NAME(D.EMP_NO) AS EMP_NAME,
        EMP_PKG.GET_EMP_BRANCH_NAME(D.EMP_NO) AS BRANCH_NAME,
        D.REQ_AMOUNT,
        D.NOTE AS DETAIL_NOTE,
        DISBURSEMENT_PKG.GET_DETAIL_BATCH_ID(D.DETAIL_ID) AS BATCH_ID,
        DISBURSEMENT_PKG.GET_DETAIL_BATCH_NO(D.DETAIL_ID) AS BATCH_NO,
        DISBURSEMENT_PKG.GET_EMP_IS_ACTIVE(D.EMP_NO) AS IS_ACTIVE,
        ROW_NUMBER() OVER (ORDER BY M.REQ_ID DESC, D.EMP_NO) RN
      FROM GFC.PAYMENT_REQ_TB M
      JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
      WHERE 1=1 ' || NVL(P_INSQL,'') || '
    ) WHERE RN BETWEEN ' || TO_CHAR(P_OFFSET+1) || ' AND ' || TO_CHAR(P_OFFSET+P_PAGE_SIZE) || ' ORDER BY RN';
    OPEN P_REF_CUR_OUT FOR XSQL;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_LIST_MASTER (P_INSQL VARCHAR2, P_OFFSET NUMBER, P_PAGE_SIZE NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2) IS
    XSQL VARCHAR2(32767);
  BEGIN
    XSQL := 'SELECT * FROM (
      SELECT
        M.REQ_ID, M.REQ_NO, M.THE_MONTH, M.REQ_TYPE, M.STATUS,
        M.CALC_METHOD, M.PERCENT_VAL, M.REQ_AMOUNT,
        TO_CHAR(M.ENTRY_DATE,''DD/MM/YYYY'') AS ENTRY_DATE, TO_CHAR(M.PAY_DATE,''DD/MM/YYYY'') AS PAY_DATE, M.NOTE,
        SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538,M.REQ_TYPE) AS REQ_TYPE_NAME,
        SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541,M.STATUS) AS STATUS_NAME,
        USER_PKG.GET_USER_NAME(M.ENTRY_USER) AS ENTRY_USER_NAME,
        (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = M.REQ_ID) AS EMP_COUNT,
        (SELECT NVL(SUM(REQ_AMOUNT),0) FROM GFC.PAYMENT_REQ_DETAIL_TB WHERE REQ_ID = M.REQ_ID) AS TOTAL_AMOUNT,
        DISBURSEMENT_PKG.GET_REQ_BATCH_ID(M.REQ_ID) AS BATCH_ID,
        DISBURSEMENT_PKG.GET_REQ_BATCH_NO(M.REQ_ID) AS BATCH_NO,
        ROW_NUMBER() OVER (ORDER BY M.REQ_ID DESC) RN
      FROM GFC.PAYMENT_REQ_TB M
      WHERE 1=1 ' || NVL(P_INSQL,'') || '
    ) WHERE RN BETWEEN ' || TO_CHAR(P_OFFSET+1) || ' AND ' || TO_CHAR(P_OFFSET+P_PAGE_SIZE) || ' ORDER BY RN';
    OPEN P_REF_CUR_OUT FOR XSQL;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_SUMMARY_GET (P_EMP_NO NUMBER, P_THE_MONTH NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2) IS
    V NUMBER;
  BEGIN
    V := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
    OPEN P_REF_CUR_OUT FOR
      SELECT V AS THE_MONTH,
        EMP_HAS_MONTHLY_SALARY(P_EMP_NO, V)           AS SALARY_EXISTS,
        GET_EMP_NET_SALARY(P_EMP_NO, V)                AS NET_SALARY,
        GET_EMP_DUES_BASE(P_EMP_NO)                    AS DUES_BASE,
        GET_EMP_DUES_ADD(P_EMP_NO)                     AS DUES_ADD,
        GET_EMP_DUES_DED(P_EMP_NO)                     AS DUES_DED,
        GET_EMP_DUES_RESERVED(P_EMP_NO)                AS DUES_RESERVED,
        GET_EMP_DUES_PAID(P_EMP_NO)                    AS DUES_PAID,
        GET_EMP_DUES_AVAILABLE(P_EMP_NO)               AS DUES_AVAILABLE
      FROM DUAL;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_TOTALS (P_INSQL VARCHAR2, REF_CUR_OUT OUT SYS_REFCURSOR, MSG_OUT OUT VARCHAR2) IS
    V_CAN CONSTANT NUMBER := C_REQ_STATUS_CANCELLED;
    V_DRF CONSTANT NUMBER := C_REQ_STATUS_DRAFT;
    V_APP CONSTANT NUMBER := C_REQ_STATUS_APPROVED;
    V_PAD CONSTANT NUMBER := C_REQ_STATUS_PAID;
    V_T1  CONSTANT NUMBER := C_REQ_TYPE_FULL_SALARY;
    V_T2  CONSTANT NUMBER := C_REQ_TYPE_PART_SALARY;
    V_T3  CONSTANT NUMBER := C_REQ_TYPE_LUMP_SUM;
  BEGIN
    OPEN REF_CUR_OUT FOR
      'SELECT
        COUNT(1) AS CNT,
        NVL(SUM(D.REQ_AMOUNT), 0) AS TOTAL_AMOUNT,
        NVL(SUM(CASE WHEN M.STATUS <> '||V_CAN||' THEN D.REQ_AMOUNT END), 0) AS ACTIVE_AMOUNT,
        COUNT(CASE WHEN M.STATUS <> '||V_CAN||' THEN 1 END) AS ACTIVE_COUNT,
        NVL(SUM(CASE WHEN M.STATUS = '||V_CAN||' THEN D.REQ_AMOUNT END), 0) AS CANCELLED_AMOUNT,
        COUNT(CASE WHEN M.STATUS = '||V_CAN||' THEN 1 END) AS CANCELLED_COUNT,
        NVL(SUM(CASE WHEN M.REQ_TYPE='||V_T1||' AND M.STATUS<>'||V_CAN||' THEN D.REQ_AMOUNT END), 0) AS T1_AMOUNT,
        COUNT(CASE WHEN M.REQ_TYPE='||V_T1||' AND M.STATUS<>'||V_CAN||' THEN 1 END) AS T1_COUNT,
        NVL(SUM(CASE WHEN M.REQ_TYPE='||V_T2||' AND M.STATUS<>'||V_CAN||' THEN D.REQ_AMOUNT END), 0) AS T2_AMOUNT,
        COUNT(CASE WHEN M.REQ_TYPE='||V_T2||' AND M.STATUS<>'||V_CAN||' THEN 1 END) AS T2_COUNT,
        NVL(SUM(CASE WHEN M.REQ_TYPE='||V_T3||' AND M.STATUS<>'||V_CAN||' THEN D.REQ_AMOUNT END), 0) AS T3_AMOUNT,
        COUNT(CASE WHEN M.REQ_TYPE='||V_T3||' AND M.STATUS<>'||V_CAN||' THEN 1 END) AS T3_COUNT,
        NVL(SUM(CASE WHEN M.STATUS='||V_DRF||' THEN D.REQ_AMOUNT END), 0) AS S0_AMOUNT,
        COUNT(CASE WHEN M.STATUS='||V_DRF||' THEN 1 END) AS S0_COUNT,
        NVL(SUM(CASE WHEN M.STATUS='||V_APP||' THEN D.REQ_AMOUNT END), 0) AS S1_AMOUNT,
        COUNT(CASE WHEN M.STATUS='||V_APP||' THEN 1 END) AS S1_COUNT,
        NVL(SUM(CASE WHEN M.STATUS='||V_PAD||' THEN D.REQ_AMOUNT END), 0) AS S2_AMOUNT,
        COUNT(CASE WHEN M.STATUS='||V_PAD||' THEN 1 END) AS S2_COUNT
      FROM GFC.PAYMENT_REQ_TB M
      JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
      WHERE 1=1 ' || P_INSQL;
    MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_TOTALS_BRANCH (P_INSQL VARCHAR2, REF_CUR_OUT OUT SYS_REFCURSOR, MSG_OUT OUT VARCHAR2) IS
    V_CAN CONSTANT NUMBER := C_REQ_STATUS_CANCELLED;
    V_PAD CONSTANT NUMBER := C_REQ_STATUS_PAID;
  BEGIN
    OPEN REF_CUR_OUT FOR
      'SELECT
        B.BRANCH_NO,
        B.BRANCH_NAME,
        COUNT(DISTINCT B.REQ_ID) AS REQ_COUNT,
        NVL(SUM(B.REQ_AMOUNT), 0) AS REQ_AMOUNT,
        COUNT(DISTINCT CASE WHEN B.M_STATUS='||V_PAD||' THEN B.REQ_ID END) AS PAID_COUNT,
        NVL(SUM(CASE WHEN B.M_STATUS='||V_PAD||' THEN B.REQ_AMOUNT END), 0) AS PAID_AMOUNT
      FROM (
        SELECT M.REQ_ID, M.REQ_AMOUNT, M.STATUS AS M_STATUS,
               EMP_PKG.GET_EMP_BRANCH(D.EMP_NO) AS BRANCH_NO,
               SETTING_PKG.GCC_BRANCHES_TB_GET_NAME(EMP_PKG.GET_EMP_BRANCH(D.EMP_NO)) AS BRANCH_NAME
          FROM GFC.PAYMENT_REQ_TB M
          JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
         WHERE M.STATUS <> '||V_CAN||' ' || NVL(P_INSQL, '') || '
      ) B
      GROUP BY B.BRANCH_NO, B.BRANCH_NAME
      ORDER BY REQ_AMOUNT DESC';
    MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- Batch Operations
  -- ============================================================

  PROCEDURE PAYMENT_REQ_APPROVE_BATCH (P_THE_MONTH NUMBER, P_REQ_IDS VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2) IS
    V_OK NUMBER := 0; V_ERR NUMBER := 0; V_MSG VARCHAR2(4000);
  BEGIN
    FOR R IN (SELECT REQ_ID FROM GFC.PAYMENT_REQ_TB
              WHERE STATUS = C_REQ_STATUS_DRAFT AND THE_MONTH = P_THE_MONTH
              AND (P_REQ_IDS IS NULL OR INSTR(','||P_REQ_IDS||',', ','||TO_CHAR(REQ_ID)||',') > 0)
              ORDER BY REQ_ID)
    LOOP
      BEGIN
        V_MSG := NULL;
        PAYMENT_REQ_APPROVE(R.REQ_ID, V_MSG);
        IF V_MSG = '1' THEN V_OK := V_OK + 1;
        ELSE V_ERR := V_ERR + 1;
          BEGIN INSERT INTO GFC.PROCESS_LOG_TB (LOG_ID,EMP_NO,THE_MONTH,PROCESS_NAME,ERROR_MSG,LOG_DATE)
                VALUES (PROCESS_LOG_SEQ.NEXTVAL,0,P_THE_MONTH,'APPROVE_BATCH',SUBSTR(V_MSG,1,500),SYSDATE);
          EXCEPTION WHEN OTHERS THEN NULL; END;
        END IF;
      EXCEPTION WHEN OTHERS THEN V_ERR := V_ERR + 1; END;
    END LOOP;
    P_MSG_OUT := TO_CHAR(V_OK) || '|' || TO_CHAR(V_ERR);
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := '0|1|' || SUBSTR(SQLERRM,1,200);
  END;


  PROCEDURE PAYMENT_REQ_PAY_BATCH (P_THE_MONTH NUMBER, P_REQ_IDS VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2) IS
    V_OK NUMBER := 0; V_ERR NUMBER := 0; V_MSG VARCHAR2(4000);
  BEGIN
    FOR R IN (SELECT REQ_ID FROM GFC.PAYMENT_REQ_TB
              WHERE STATUS = C_REQ_STATUS_APPROVED AND THE_MONTH = P_THE_MONTH
              AND (P_REQ_IDS IS NULL OR INSTR(','||P_REQ_IDS||',', ','||TO_CHAR(REQ_ID)||',') > 0)
              ORDER BY REQ_ID)
    LOOP
      BEGIN
        V_MSG := NULL;
        PAYMENT_REQ_PAY(R.REQ_ID, V_MSG);
        IF V_MSG = '1' THEN V_OK := V_OK + 1;
        ELSE V_ERR := V_ERR + 1;
          BEGIN INSERT INTO GFC.PROCESS_LOG_TB (LOG_ID,EMP_NO,THE_MONTH,PROCESS_NAME,ERROR_MSG,LOG_DATE)
                VALUES (PROCESS_LOG_SEQ.NEXTVAL,0,P_THE_MONTH,'PAY_BATCH',SUBSTR(V_MSG,1,500),SYSDATE);
          EXCEPTION WHEN OTHERS THEN NULL; END;
        END IF;
      EXCEPTION WHEN OTHERS THEN V_ERR := V_ERR + 1; END;
    END LOOP;
    P_MSG_OUT := TO_CHAR(V_OK) || '|' || TO_CHAR(V_ERR);
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := '0|1|' || SUBSTR(SQLERRM,1,200);
  END;


  -- ============================================================
  -- Bulk Preview / Create (1 master + N details)
  -- ============================================================

  PROCEDURE PAYMENT_REQ_BULK_PREVIEW (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER, P_REQ_AMOUNT NUMBER,
      P_PAY_TYPE NUMBER, P_SAL_FROM NUMBER, P_SAL_TO NUMBER,
      P_BRANCH_NO NUMBER,
      P_L_VALUE NUMBER, P_H_VALUE NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_M NUMBER := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
    V_RA NUMBER := NULLIF(P_REQ_AMOUNT,-3);
    V_BR NUMBER := NULLIF(P_BRANCH_NO,-7);
    V_PCT NUMBER; V_LV NUMBER; V_HV NUMBER;
  BEGIN
    IF P_REQ_TYPE = C_REQ_TYPE_FULL_SALARY THEN
      OPEN P_REF_CUR_OUT FOR
        SELECT A.EMP_NO, EMP_PKG.GET_EMP_NAME(A.EMP_NO) EMP_NAME,
               EMP_PKG.GET_EMP_BRANCH_NAME(A.EMP_NO) BRANCH_NAME, A.NET_SALARY,
               NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                    WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) AS CON_323_AMOUNT,
               LEAST(
                 NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0),
                 GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL)
               ) AS CALC_AMOUNT,
               (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB D
                  JOIN GFC.PAYMENT_REQ_TB R ON R.REQ_ID = D.REQ_ID
                 WHERE D.EMP_NO = A.EMP_NO AND R.THE_MONTH = V_M
                   AND R.REQ_TYPE = P_REQ_TYPE AND R.STATUS <> C_REQ_STATUS_CANCELLED) AS HAS_EXISTING,
               CAST(NULL AS VARCHAR2(3)) AS LIMIT_FLAG,
               0 AS ALREADY_POSTED,
               GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL) AS SALARY_AVAILABLE,
               1 AS IS_CALCULATED,
               CASE
                 WHEN NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) <= 0 THEN
                   'لا يوجد مبلغ مستحقات (بند 323)'
                 WHEN GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL) <= 0 THEN
                   'لا يوجد رصيد مستحقات متاح (مصروف مسبقاً)'
                 ELSE NULL
               END AS SKIP_REASON
          FROM DATA.ADMIN A
         WHERE A.MONTH = V_M
           AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
         ORDER BY A.EMP_NO;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_LUMP_SUM THEN
      -- نوع 3: كل الموظفين اللي عندهم رصيد مستحقات — نسبة أو مبلغ ثابت
      V_PCT := NVL(NULLIF(P_PERCENT_VAL, -2), 0);
      OPEN P_REF_CUR_OUT FOR
        SELECT E.NO AS EMP_NO, E.NAME AS EMP_NAME,
               EMP_PKG.GET_EMP_BRANCH_NAME(E.NO) BRANCH_NAME, 0 AS NET_SALARY,
               GET_EMP_DUES_AVAILABLE(E.NO, NULL) AS CON_323_AMOUNT,
               -- حسب طريقة الاحتساب: 1=نسبة، 2=مبلغ ثابت
               CASE WHEN NULLIF(P_CALC_METHOD, -1) = C_CALC_PERCENT AND V_PCT > 0 THEN ROUND(GET_EMP_DUES_AVAILABLE(E.NO, NULL) * V_PCT / 100, 2)
                    WHEN V_RA IS NOT NULL THEN LEAST(V_RA, GET_EMP_DUES_AVAILABLE(E.NO, NULL))
                    ELSE GET_EMP_DUES_AVAILABLE(E.NO, NULL) END AS CALC_AMOUNT,
               (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB D
                  JOIN GFC.PAYMENT_REQ_TB R ON R.REQ_ID = D.REQ_ID
                 WHERE D.EMP_NO = E.NO AND R.THE_MONTH = V_M
                   AND R.REQ_TYPE = P_REQ_TYPE AND R.STATUS <> C_REQ_STATUS_CANCELLED) AS HAS_EXISTING,
               CAST(NULL AS VARCHAR2(3)) AS LIMIT_FLAG,
               0 AS ALREADY_POSTED,
               GET_EMP_DUES_AVAILABLE(E.NO, NULL) AS SALARY_AVAILABLE,
               CASE WHEN E.IS_ACTIVE = 1 THEN 1 ELSE 0 END AS IS_CALCULATED,
               CASE WHEN GET_EMP_DUES_AVAILABLE(E.NO, NULL) <= 0 THEN 'رصيد المستحقات صفر'
                    ELSE NULL END AS SKIP_REASON
          FROM DATA.EMPLOYEES E
         WHERE (GET_EMP_DUES_BASE(E.NO) + GET_EMP_DUES_ADD(E.NO) - GET_EMP_DUES_DED(E.NO)) > 0
           AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(E.NO) = V_BR)
         ORDER BY E.NO;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN
      V_PCT := NVL(NULLIF(P_PERCENT_VAL, -2), 100);
      V_LV  := NULLIF(P_L_VALUE, -8);
      V_HV  := NULLIF(P_H_VALUE, -9);

      OPEN P_REF_CUR_OUT FOR
        SELECT A.EMP_NO, EMP_PKG.GET_EMP_NAME(A.EMP_NO) EMP_NAME,
               EMP_PKG.GET_EMP_BRANCH_NAME(A.EMP_NO) BRANCH_NAME, A.NET_SALARY,
               NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                    WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) AS CON_323_AMOUNT,
               -- حساب المبلغ مع الحدود
               LEAST(
                 GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL),
                 CASE
                   -- النسبة أقل من الحد الأدنى
                   WHEN V_LV IS NOT NULL
                     AND ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                          WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2) < V_LV
                   THEN LEAST(V_LV, NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                          WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0))
                   -- النسبة أكبر من الحد الأعلى
                   WHEN V_HV IS NOT NULL
                     AND ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                          WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2) > V_HV
                   THEN V_HV
                   -- ضمن الحدود
                   ELSE ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                          WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2)
                 END
               ) AS CALC_AMOUNT,
               (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB D
                  JOIN GFC.PAYMENT_REQ_TB R ON R.REQ_ID = D.REQ_ID
                 WHERE D.EMP_NO = A.EMP_NO AND R.THE_MONTH = V_M
                   AND R.REQ_TYPE = P_REQ_TYPE AND R.STATUS <> C_REQ_STATUS_CANCELLED) AS HAS_EXISTING,
               -- LIMIT_FLAG للمعاينة
               CASE
                 WHEN V_LV IS NOT NULL
                   AND ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                        WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2) < V_LV
                   AND NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                        WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) < V_LV
                 THEN 'CAP'
                 WHEN V_LV IS NOT NULL
                   AND ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                        WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2) < V_LV
                 THEN 'MIN'
                 WHEN V_HV IS NOT NULL
                   AND ROUND(NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                        WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) * V_PCT / 100, 2) > V_HV
                 THEN 'MAX'
                 ELSE NULL
               END AS LIMIT_FLAG,
               1 AS ALREADY_POSTED,
               GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL) AS SALARY_AVAILABLE,
               1 AS IS_CALCULATED,
               CASE
                 WHEN NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) <= 0 THEN
                   'لا يوجد مستحقات (بند 323)'
                 WHEN GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL) <= 0 THEN
                   'لا يوجد رصيد مستحقات متاح'
                 ELSE NULL
               END AS SKIP_REASON
          FROM DATA.ADMIN A
         WHERE A.MONTH = V_M
           AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
         ORDER BY A.EMP_NO;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_MONTHLY_DUES THEN
      -- نوع 4: المتبقي من بند 323 للشهر
      OPEN P_REF_CUR_OUT FOR
        SELECT A.EMP_NO, EMP_PKG.GET_EMP_NAME(A.EMP_NO) EMP_NAME,
               EMP_PKG.GET_EMP_BRANCH_NAME(A.EMP_NO) BRANCH_NAME, A.NET_SALARY,
               NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                    WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) AS CON_323_AMOUNT,
               -- المتبقي = بند 323 - المصروف من 1,2,4
               GREATEST(
                 NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0)
                 - NVL((SELECT SUM(DD.REQ_AMOUNT) FROM GFC.PAYMENT_REQ_DETAIL_TB DD
                        JOIN GFC.PAYMENT_REQ_TB MM ON MM.REQ_ID = DD.REQ_ID
                       WHERE DD.EMP_NO = A.EMP_NO AND MM.THE_MONTH = V_M
                         AND MM.REQ_TYPE IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_MONTHLY_DUES)
                         AND MM.STATUS <> C_REQ_STATUS_CANCELLED
                         AND DD.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED), 0),
                 0
               ) AS CALC_AMOUNT,
               (SELECT COUNT(1) FROM GFC.PAYMENT_REQ_DETAIL_TB D
                  JOIN GFC.PAYMENT_REQ_TB R ON R.REQ_ID = D.REQ_ID
                 WHERE D.EMP_NO = A.EMP_NO AND R.THE_MONTH = V_M
                   AND R.REQ_TYPE = P_REQ_TYPE AND R.STATUS <> C_REQ_STATUS_CANCELLED) AS HAS_EXISTING,
               CAST(NULL AS VARCHAR2(3)) AS LIMIT_FLAG,
               1 AS ALREADY_POSTED,
               GET_EMP_DUES_AVAILABLE(A.EMP_NO, NULL) AS SALARY_AVAILABLE,
               1 AS IS_CALCULATED,
               CASE
                 WHEN NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) <= 0 THEN
                   'لا يوجد مستحقات (بند 323)'
                 WHEN NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
                      WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0)
                      - NVL((SELECT SUM(DD.REQ_AMOUNT) FROM GFC.PAYMENT_REQ_DETAIL_TB DD
                             JOIN GFC.PAYMENT_REQ_TB MM ON MM.REQ_ID = DD.REQ_ID
                            WHERE DD.EMP_NO = A.EMP_NO AND MM.THE_MONTH = V_M
                              AND MM.REQ_TYPE IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_MONTHLY_DUES)
                              AND MM.STATUS <> C_REQ_STATUS_CANCELLED
                              AND DD.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED), 0) <= 0 THEN
                   'تم صرف كامل بند 323'
                 ELSE NULL
               END AS SKIP_REASON
          FROM DATA.ADMIN A
         WHERE A.MONTH = V_M
           AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
         ORDER BY A.EMP_NO;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_BENEFITS THEN
      -- نوع 5: كل الموظفين المحتسبين (صرف بدون تأثير)
      OPEN P_REF_CUR_OUT FOR
        SELECT A.EMP_NO, EMP_PKG.GET_EMP_NAME(A.EMP_NO) EMP_NAME,
               EMP_PKG.GET_EMP_BRANCH_NAME(A.EMP_NO) BRANCH_NAME, A.NET_SALARY,
               0 AS CON_323_AMOUNT,
               NVL(V_RA, 0) AS CALC_AMOUNT,
               0 AS HAS_EXISTING,
               CAST(NULL AS VARCHAR2(3)) AS LIMIT_FLAG,
               0 AS ALREADY_POSTED,
               0 AS SALARY_AVAILABLE,
               1 AS IS_CALCULATED,
               CAST(NULL AS VARCHAR2(200)) AS SKIP_REASON
          FROM DATA.ADMIN A
         WHERE A.MONTH = V_M
           AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
         ORDER BY A.EMP_NO;

    ELSE
      OPEN P_REF_CUR_OUT FOR
        SELECT NULL AS EMP_NO, NULL AS EMP_NAME, NULL AS BRANCH_NAME,
               NULL AS NET_SALARY, NULL AS CON_323_AMOUNT, NULL AS CALC_AMOUNT, NULL AS HAS_EXISTING,
               NULL AS LIMIT_FLAG, NULL AS ALREADY_POSTED, NULL AS SALARY_AVAILABLE,
               NULL AS IS_CALCULATED, NULL AS SKIP_REASON
          FROM DUAL WHERE 1=0;
    END IF;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  PROCEDURE PAYMENT_REQ_BULK_CREATE (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_CALC_METHOD NUMBER, P_PERCENT_VAL NUMBER, P_REQ_AMOUNT NUMBER,
      P_PAY_TYPE NUMBER, P_SAL_FROM NUMBER, P_SAL_TO NUMBER,
      P_BRANCH_NO NUMBER,
      P_L_VALUE NUMBER, P_H_VALUE NUMBER,
      P_NOTE VARCHAR2,
      P_MSG_OUT OUT VARCHAR2
  ) IS
    V_M NUMBER := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
    V_RA NUMBER := NULLIF(P_REQ_AMOUNT,-3);
    V_BR NUMBER := NULLIF(P_BRANCH_NO,-7);
    V_PT NUMBER := NULLIF(P_PAY_TYPE,-4);
    V_NT VARCHAR2(500) := NULLIF(P_NOTE,'N/A');
    V_OK NUMBER := 0; V_SK NUMBER := 0; V_ER NUMBER := 0;
    V_MASTER_ID NUMBER; V_MSG VARCHAR2(4000); V_DET_MSG VARCHAR2(4000);
  BEGIN
    IF P_REQ_TYPE NOT IN (C_REQ_TYPE_FULL_SALARY, C_REQ_TYPE_PART_SALARY, C_REQ_TYPE_LUMP_SUM, C_REQ_TYPE_MONTHLY_DUES, C_REQ_TYPE_BENEFITS) THEN
      P_MSG_OUT := '0|0|0|0'; RETURN;
    END IF;

    PAYMENT_REQ_INSERT(V_M, P_REQ_TYPE, P_CALC_METHOD, P_PERCENT_VAL, P_L_VALUE, P_H_VALUE, V_PT, NULL, NVL(V_NT,'bulk'), V_MSG);
    IF NOT (V_MSG IS NOT NULL AND REGEXP_LIKE(V_MSG, '^\d+$')) THEN
      P_MSG_OUT := '0|0|0|1|' || NVL(V_MSG,'Failed to create master');
      RETURN;
    END IF;
    V_MASTER_ID := TO_NUMBER(V_MSG);

    IF P_REQ_TYPE = C_REQ_TYPE_FULL_SALARY THEN
      FOR R IN (SELECT A.EMP_NO FROM DATA.ADMIN A
                 WHERE A.MONTH = V_M AND A.NET_SALARY = 0
                   AND EXISTS (SELECT 1 FROM DATA.SALARY S WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M AND S.VALUE > 0)
                   AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
                 ORDER BY A.EMP_NO)
      LOOP
        BEGIN
          V_DET_MSG := NULL;
          DETAIL_INSERT(V_MASTER_ID, R.EMP_NO, V_RA, NVL(V_NT,'bulk'), V_DET_MSG);
          IF V_DET_MSG IS NOT NULL AND REGEXP_LIKE(V_DET_MSG, '^\d+$') THEN V_OK := V_OK + 1;
          ELSIF INSTR(V_DET_MSG, 'موجود مسبقا') > 0 THEN V_SK := V_SK + 1;
          ELSE V_ER := V_ER + 1;
            BEGIN INSERT INTO GFC.PROCESS_LOG_TB (LOG_ID,EMP_NO,THE_MONTH,PROCESS_NAME,ERROR_MSG,LOG_DATE)
                  VALUES (PROCESS_LOG_SEQ.NEXTVAL,R.EMP_NO,V_M,'BULK_CREATE',SUBSTR(V_DET_MSG,1,500),SYSDATE);
            EXCEPTION WHEN OTHERS THEN NULL; END;
          END IF;
        EXCEPTION WHEN OTHERS THEN V_ER := V_ER + 1; END;
      END LOOP;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_PART_SALARY THEN
      FOR R IN (SELECT A.EMP_NO FROM DATA.ADMIN A
                 WHERE A.MONTH = V_M AND A.NET_SALARY = 0
                   AND EXISTS (SELECT 1 FROM DATA.SALARY S WHERE S.EMP_NO = A.EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M AND S.VALUE > 0)
                   AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
                 ORDER BY A.EMP_NO)
      LOOP
        BEGIN
          V_DET_MSG := NULL;
          DETAIL_INSERT(V_MASTER_ID, R.EMP_NO, V_RA, NVL(V_NT,'bulk'), V_DET_MSG);
          IF V_DET_MSG IS NOT NULL AND REGEXP_LIKE(V_DET_MSG, '^\d+$') THEN V_OK := V_OK + 1;
          ELSIF INSTR(V_DET_MSG, 'موجود مسبقا') > 0 THEN V_SK := V_SK + 1;
          ELSE V_ER := V_ER + 1;
            BEGIN INSERT INTO GFC.PROCESS_LOG_TB (LOG_ID,EMP_NO,THE_MONTH,PROCESS_NAME,ERROR_MSG,LOG_DATE)
                  VALUES (PROCESS_LOG_SEQ.NEXTVAL,R.EMP_NO,V_M,'BULK_CREATE',SUBSTR(V_DET_MSG,1,500),SYSDATE);
            EXCEPTION WHEN OTHERS THEN NULL; END;
          END IF;
        EXCEPTION WHEN OTHERS THEN V_ER := V_ER + 1; END;
      END LOOP;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_LUMP_SUM THEN
      FOR R IN (SELECT E.NO AS EMP_NO FROM DATA.EMPLOYEES E
                 WHERE E.IS_ACTIVE = 1 AND GET_EMP_DUES_AVAILABLE(E.NO, NULL) > 0
                   AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(E.NO) = V_BR)
                 ORDER BY E.NO)
      LOOP
        BEGIN
          V_DET_MSG := NULL;
          DETAIL_INSERT(V_MASTER_ID, R.EMP_NO, V_RA, NVL(V_NT,'bulk'), V_DET_MSG);
          IF V_DET_MSG IS NOT NULL AND REGEXP_LIKE(V_DET_MSG, '^\d+$') THEN V_OK := V_OK + 1;
          ELSIF INSTR(V_DET_MSG, 'موجود مسبقا') > 0 THEN V_SK := V_SK + 1;
          ELSE V_ER := V_ER + 1;
            BEGIN INSERT INTO GFC.PROCESS_LOG_TB (LOG_ID,EMP_NO,THE_MONTH,PROCESS_NAME,ERROR_MSG,LOG_DATE)
                  VALUES (PROCESS_LOG_SEQ.NEXTVAL,R.EMP_NO,V_M,'BULK_CREATE',SUBSTR(V_DET_MSG,1,500),SYSDATE);
            EXCEPTION WHEN OTHERS THEN NULL; END;
          END IF;
        EXCEPTION WHEN OTHERS THEN V_ER := V_ER + 1; END;
      END LOOP;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_MONTHLY_DUES THEN
      -- نوع 4: الموظفين اللي عندهم متبقي من بند 323
      FOR R IN (SELECT A.EMP_NO FROM DATA.ADMIN A
                 WHERE A.MONTH = V_M
                   AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
                 ORDER BY A.EMP_NO)
      LOOP
        BEGIN
          V_DET_MSG := NULL;
          DETAIL_INSERT(V_MASTER_ID, R.EMP_NO, NVL(V_RA, 0), NVL(V_NT,'bulk'), V_DET_MSG);
          IF V_DET_MSG IS NOT NULL AND REGEXP_LIKE(V_DET_MSG, '^\d+$') THEN V_OK := V_OK + 1;
          ELSIF INSTR(V_DET_MSG, 'موجود') > 0 OR INSTR(V_DET_MSG, 'متبقي') > 0 THEN V_SK := V_SK + 1;
          ELSE V_ER := V_ER + 1; END IF;
        EXCEPTION WHEN OTHERS THEN V_ER := V_ER + 1; END;
      END LOOP;

    ELSIF P_REQ_TYPE = C_REQ_TYPE_BENEFITS THEN
      -- نوع 5: كل الموظفين المحتسبين
      FOR R IN (SELECT A.EMP_NO FROM DATA.ADMIN A
                 WHERE A.MONTH = V_M
                   AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(A.EMP_NO) = V_BR)
                 ORDER BY A.EMP_NO)
      LOOP
        BEGIN
          V_DET_MSG := NULL;
          DETAIL_INSERT(V_MASTER_ID, R.EMP_NO, V_RA, NVL(V_NT,'bulk'), V_DET_MSG);
          IF V_DET_MSG IS NOT NULL AND REGEXP_LIKE(V_DET_MSG, '^\d+$') THEN V_OK := V_OK + 1;
          ELSIF INSTR(V_DET_MSG, 'موجود') > 0 THEN V_SK := V_SK + 1;
          ELSE V_ER := V_ER + 1; END IF;
        EXCEPTION WHEN OTHERS THEN V_ER := V_ER + 1; END;
      END LOOP;
    END IF;

    P_MSG_OUT := TO_CHAR(V_MASTER_ID) || '|' || TO_CHAR(V_OK) || '|' || TO_CHAR(V_SK) || '|' || TO_CHAR(V_ER);
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := '0|0|0|1|' || SUBSTR(SQLERRM,1,200);
  END;


  -- ============================================================
  -- Month Status
  -- ============================================================

  PROCEDURE GET_MONTH_STATUS (
      P_THE_MONTH NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_M NUMBER := NVL(P_THE_MONTH, GET_DEFAULT_MONTH);
    V_CNT NUMBER := 0;
  BEGIN
    SELECT COUNT(1) INTO V_CNT FROM DATA.ADMIN WHERE MONTH = V_M AND ROWNUM = 1;

    OPEN P_REF_CUR_OUT FOR
      SELECT
        CASE WHEN V_CNT > 0 THEN 'admin' ELSE 'none' END AS SOURCE,
        NVL((SELECT COUNT(1) FROM DATA.ADMIN WHERE MONTH = V_M), 0) AS EMP_COUNT,
        NVL((SELECT SUM(NET_SALARY) FROM DATA.ADMIN WHERE MONTH = V_M), 0) AS TOTAL_NET,
        NVL((SELECT SUM(S.VALUE) FROM DATA.SALARY S
              WHERE S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_M), 0) AS TOTAL_323,
        NVL((SELECT SUM(D.DUES_AMOUNT) FROM GFC.PAYMENT_REQ_DETAIL_TB D
               JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
              WHERE M.THE_MONTH = V_M
                AND D.DETAIL_STATUS = C_REQ_STATUS_DRAFT
                AND M.STATUS <> C_REQ_STATUS_CANCELLED), 0) AS TOTAL_DRAFT,
        NVL((SELECT SUM(D.DUES_AMOUNT) FROM GFC.PAYMENT_REQ_DETAIL_TB D
               JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
              WHERE M.THE_MONTH = V_M
                AND D.DETAIL_STATUS = C_REQ_STATUS_APPROVED
                AND M.STATUS <> C_REQ_STATUS_CANCELLED), 0) AS TOTAL_APPROVED,
        NVL((SELECT SUM(D.DUES_AMOUNT) FROM GFC.PAYMENT_REQ_DETAIL_TB D
               JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
              WHERE M.THE_MONTH = V_M
                AND D.DETAIL_STATUS = C_REQ_STATUS_PAID
                AND M.STATUS <> C_REQ_STATUS_CANCELLED), 0) AS TOTAL_PAID,
        (SELECT COUNT(DISTINCT M.REQ_ID) FROM GFC.PAYMENT_REQ_TB M
           JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
          WHERE M.THE_MONTH = V_M
            AND M.STATUS <> C_REQ_STATUS_CANCELLED) AS REQ_COUNT
      FROM DUAL;

    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- تقرير شهري
  -- ============================================================
  PROCEDURE PAYMENT_REQ_REPORT (
      P_MONTH_FROM NUMBER, P_MONTH_TO NUMBER DEFAULT NULL,
      P_BRANCH_NO NUMBER DEFAULT NULL, P_REQ_TYPE NUMBER DEFAULT NULL, P_STATUS NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_MF NUMBER := P_MONTH_FROM;
    V_MT NUMBER := NVL(P_MONTH_TO, P_MONTH_FROM);
    V_BR NUMBER := NULLIF(P_BRANCH_NO, -1);
    V_RT NUMBER := NULLIF(P_REQ_TYPE, -1);
    V_ST NUMBER := NULLIF(P_STATUS, -1);
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT M.REQ_ID, M.REQ_NO, M.THE_MONTH, M.REQ_TYPE, M.STATUS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538, M.REQ_TYPE) AS REQ_TYPE_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, M.STATUS)   AS STATUS_NAME,
             D.DETAIL_ID, D.EMP_NO,
             EMP_PKG.GET_EMP_NAME(D.EMP_NO)        AS EMP_NAME,
             EMP_PKG.GET_EMP_BRANCH_NAME(D.EMP_NO) AS BRANCH_NAME,
             EMP_PKG.GET_EMP_BRANCH(D.EMP_NO)      AS BRANCH_NO,
             D.REQ_AMOUNT, D.DUES_AMOUNT, D.DETAIL_STATUS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, D.DETAIL_STATUS) AS DETAIL_STATUS_NAME,
             M.PAY_DATE, M.ENTRY_DATE
        FROM GFC.PAYMENT_REQ_TB M
        JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
       WHERE M.THE_MONTH BETWEEN V_MF AND V_MT
         AND (V_BR IS NULL OR EMP_PKG.GET_EMP_BRANCH(D.EMP_NO) = V_BR)
         AND (V_RT IS NULL OR M.REQ_TYPE = V_RT)
         AND (V_ST IS NULL OR M.STATUS = V_ST)
       ORDER BY M.THE_MONTH, M.REQ_ID, D.EMP_NO;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- كشف حساب موظف
  -- ============================================================
  PROCEDURE EMP_STATEMENT (
      P_EMP_NO NUMBER, P_MONTH_FROM NUMBER DEFAULT NULL, P_MONTH_TO NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT M.REQ_ID, M.REQ_NO, M.THE_MONTH, M.REQ_TYPE, M.STATUS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538, M.REQ_TYPE) AS REQ_TYPE_NAME,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, M.STATUS)   AS STATUS_NAME,
             D.DETAIL_ID, D.REQ_AMOUNT, D.DUES_AMOUNT, D.DETAIL_STATUS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(541, D.DETAIL_STATUS) AS DETAIL_STATUS_NAME,
             D.PAY_TYPE,
             GET_DUES_TYPE_NAME(D.PAY_TYPE) AS PAY_TYPE_NAME,
             D.POST_SERIAL_DUES, D.NOTE,
             M.PAY_DATE, M.ENTRY_DATE
        FROM GFC.PAYMENT_REQ_TB M
        JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.REQ_ID = M.REQ_ID
       WHERE D.EMP_NO = P_EMP_NO
         AND M.STATUS <> C_REQ_STATUS_CANCELLED
         AND (P_MONTH_FROM IS NULL OR M.THE_MONTH >= P_MONTH_FROM)
         AND (P_MONTH_TO   IS NULL OR M.THE_MONTH <= P_MONTH_TO)
       ORDER BY M.THE_MONTH DESC, M.REQ_ID DESC;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;



  -- ===========================================================
  -- CHECK_DUPLICATE_REQUEST
  -- Returns count of active requests with same month+type
  -- ===========================================================
  PROCEDURE CHECK_DUPLICATE_REQUEST (
      P_THE_MONTH NUMBER, P_REQ_TYPE NUMBER,
      P_MSG_OUT OUT VARCHAR2
  ) IS
    V_CNT NUMBER;
  BEGIN
    SELECT COUNT(1) INTO V_CNT FROM GFC.PAYMENT_REQ_TB
     WHERE THE_MONTH = P_THE_MONTH AND REQ_TYPE = P_REQ_TYPE
       AND STATUS <> C_REQ_STATUS_CANCELLED;
    P_MSG_OUT := TO_CHAR(V_CNT);
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := '0';
  END;

  -- ===========================================================
  -- CHECK_DUPLICATE_EMP
  -- Returns REQ_NO if employee exists in another active request
  -- of the same type/month, or '0' if clear
  -- ===========================================================
  PROCEDURE CHECK_DUPLICATE_EMP (
      P_EMP_NO NUMBER, P_REQ_ID NUMBER,
      P_MSG_OUT OUT VARCHAR2
  ) IS
    V_MONTH NUMBER; V_TYPE NUMBER; V_REQ_NO VARCHAR2(50);
  BEGIN
    SELECT THE_MONTH, REQ_TYPE INTO V_MONTH, V_TYPE
      FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID;

    BEGIN
      SELECT M.REQ_NO INTO V_REQ_NO
        FROM GFC.PAYMENT_REQ_DETAIL_TB D
        JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
       WHERE D.EMP_NO = P_EMP_NO
         AND D.DETAIL_STATUS <> C_REQ_STATUS_CANCELLED
         AND M.STATUS <> C_REQ_STATUS_CANCELLED
         AND M.THE_MONTH = V_MONTH AND M.REQ_TYPE = V_TYPE
         AND M.REQ_ID <> P_REQ_ID
         AND ROWNUM = 1;
      P_MSG_OUT := V_REQ_NO;
    EXCEPTION WHEN NO_DATA_FOUND THEN P_MSG_OUT := '0';
    END;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := '0';
    WHEN OTHERS THEN P_MSG_OUT := '0';
  END;


  -- ===========================================================
  -- DETAIL_PREVIEW_SINGLE
  -- Preview calculated amount for a single employee before insert
  -- Returns: "CALC_AMOUNT|DUES_AVAILABLE|LIMIT_FLAG" or "ERR|message"
  -- ===========================================================
  PROCEDURE DETAIL_PREVIEW_SINGLE (
      P_REQ_ID NUMBER, P_EMP_NO NUMBER, P_REQ_AMOUNT NUMBER DEFAULT 0,
      P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ST NUMBER; V_TYPE NUMBER; V_CALC NUMBER; V_PCT NUMBER; V_MONTH NUMBER;
    V_MASTER_PT NUMBER; V_LV NUMBER; V_HV NUMBER;
    V_MONTH2 NUMBER; V_AMT NUMBER; V_PT NUMBER; V_DA NUMBER;
    V_LF VARCHAR2(3); V_MSG VARCHAR2(4000);
    V_DUES_AVAIL NUMBER; V_323 NUMBER;
  BEGIN
    SELECT STATUS, REQ_TYPE, CALC_METHOD, PERCENT_VAL, THE_MONTH, PAY_TYPE, L_VALUE, H_VALUE
      INTO V_ST, V_TYPE, V_CALC, V_PCT, V_MONTH, V_MASTER_PT, V_LV, V_HV
      FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID;

    -- نوع 5: بدون حساب مبلغ — بس الاسم
    IF V_TYPE = C_REQ_TYPE_BENEFITS THEN
      P_MSG_OUT := '0|0||0|' || NVL(EMP_PKG.GET_EMP_NAME(P_EMP_NO), '');
      RETURN;
    END IF;

    PREPARE_REQUEST_VALUES(P_EMP_NO, V_MONTH, V_TYPE,
        V_CALC, V_PCT, P_REQ_AMOUNT, V_MASTER_PT,
        NULL, P_REQ_ID, V_LV, V_HV,
        V_MONTH2, V_AMT, V_PT, V_DA, V_LF, V_MSG);

    IF V_MSG IS NOT NULL THEN
      P_MSG_OUT := 'ERR|' || V_MSG;
    ELSE
      -- رصيد المستحقات الطبيعي (بدون طرح المحجوز — المحجوز فقط بعد الاعتماد)
      V_DUES_AVAIL := GREATEST(GET_EMP_DUES_BASE(P_EMP_NO)
                        + GET_EMP_DUES_ADD(P_EMP_NO)
                        - GET_EMP_DUES_DED(P_EMP_NO), 0);
      BEGIN
        SELECT NVL(SUM(S.VALUE),0) INTO V_323
          FROM DATA.SALARY S WHERE S.EMP_NO = P_EMP_NO AND S.CON_NO = C_SALARY_CON_DUES AND S.MONTH = V_MONTH;
      EXCEPTION WHEN OTHERS THEN V_323 := 0;
      END;
      -- FORMAT: CALC_AMOUNT|DUES_AVAILABLE|LIMIT_FLAG|SAL_323|EMP_NAME
      P_MSG_OUT := TO_CHAR(NVL(V_AMT,0)) || '|' || TO_CHAR(NVL(V_DUES_AVAIL,0)) || '|' || NVL(V_LF, '') || '|' || TO_CHAR(NVL(V_323,0)) || '|' || NVL(EMP_PKG.GET_EMP_NAME(P_EMP_NO), '');
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'ERR|الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := 'ERR|' || SQLERRM;
  END;


  -- ===========================================================
  -- PAYMENT_REQ_UNAPPROVE — إلغاء الاعتماد (رجوع لمسودة)
  -- ===========================================================
  PROCEDURE PAYMENT_REQ_UNAPPROVE (P_REQ_ID NUMBER, P_NOTE VARCHAR2 DEFAULT NULL, P_MSG_OUT OUT VARCHAR2) IS
    V_ST NUMBER; V_USER NUMBER; V_BATCH_CNT NUMBER;
  BEGIN
    SELECT STATUS INTO V_ST FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = P_REQ_ID FOR UPDATE NOWAIT;

    -- فحص: مش مصروف
    IF V_ST = C_REQ_STATUS_PAID THEN P_MSG_OUT := 'لا يمكن إلغاء اعتماد طلب مصروف'; RETURN; END IF;

    -- فحص: مش محتسب بدفعة
    SELECT COUNT(1) INTO V_BATCH_CNT
      FROM GFC.PAYMENT_BATCH_LINK_TB L
      JOIN GFC.PAYMENT_BATCH_TB B ON B.BATCH_ID = L.BATCH_ID
      JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
     WHERE D.REQ_ID = P_REQ_ID AND B.STATUS <> 9;
    IF V_BATCH_CNT > 0 THEN P_MSG_OUT := 'الطلب محتسب ضمن دفعة — يجب فك الاحتساب أولاً'; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;

    -- إرجاع كل الديتيل المعتمدة لمسودة
    UPDATE GFC.PAYMENT_REQ_DETAIL_TB
       SET DETAIL_STATUS = C_REQ_STATUS_DRAFT
     WHERE REQ_ID = P_REQ_ID AND DETAIL_STATUS = C_REQ_STATUS_APPROVED;

    -- تحديث حالة الماستر
    UPDATE GFC.PAYMENT_REQ_TB SET
        STATUS = C_REQ_STATUS_DRAFT,
        APPROVE_USER = NULL, APPROVE_DATE = NULL,
        UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE,
        NOTE = CASE WHEN P_NOTE IS NOT NULL THEN P_NOTE ELSE NOTE END
     WHERE REQ_ID = P_REQ_ID;

    LOG_ACTION(P_REQ_ID, 'UNAPPROVE', V_ST, C_REQ_STATUS_DRAFT, NVL(P_NOTE, 'إلغاء اعتماد'));
    P_MSG_OUT := '1';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الطلب غير موجود';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;

  -- BATCH_CANCEL, BATCH_REVERSE_PAY, BATCH_HISTORY_LIST, BATCH_HISTORY_GET
  -- moved to DISBURSEMENT_BATCH_PKG (04_batch_pkg_body.sql)


END DISBURSEMENT_PKG;
/
