CREATE OR REPLACE PACKAGE BODY GFC_PAK.DISBURSEMENT_BATCH_PKG AS

  -- ============================================================
  -- Alias للـ DISBURSEMENT_PKG functions
  -- ============================================================


  -- ============================================================
  -- BATCH PREVIEW — معاينة الاحتساب حسب البنك
  -- ============================================================
  PROCEDURE PAYMENT_REQ_BATCH_PREVIEW (
      P_REQ_IDS      IN  VARCHAR2,
      P_REF_CUR_OUT  OUT SYS_REFCURSOR,
      P_MSG_OUT      OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT
          D.DETAIL_ID, D.REQ_ID, M.REQ_NO, D.EMP_NO,
          EMP_PKG.GET_EMP_NAME(D.EMP_NO)                AS EMP_NAME,
          EMP_PKG.GET_EMP_BRANCH(D.EMP_NO)              AS BRANCH_NO,
          EMP_PKG.GET_EMP_BRANCH_NAME(D.EMP_NO)         AS BRANCH_NAME,
          M.THE_MONTH, M.REQ_TYPE,
          SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(538, M.REQ_TYPE) AS REQ_TYPE_NAME,
          D.PAY_TYPE, D.REQ_AMOUNT,
          NVL(E.BANK, 0)                                AS BANK_NO,
          DISBURSEMENT_PKG.GET_BANK_NAME(E.BANK)         AS BANK_NAME,
          E.ACCOUNT                                      AS BANK_ACCOUNT,
          E.IBAN,
          NVL(E.MASTER_BANKS_EMAIL, 0) AS MASTER_BANK_NO,
          DISBURSEMENT_PKG.GET_MASTER_BANK_NAME(D.EMP_NO)  AS MASTER_BANK_NAME,
          NVL(E.BANK, 0)                                 AS BANK_BRANCH_NO,
          E.ACCOUNT                                      AS ACCOUNT_BANK_EMAIL,
          CASE WHEN NVL(E.BANK, 0) = 0 THEN 1 ELSE 0 END AS NO_BANK_FLAG
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M  ON M.REQ_ID = D.REQ_ID
      JOIN DATA.EMPLOYEES E      ON E.NO     = D.EMP_NO
      WHERE INSTR(',' || P_REQ_IDS || ',', ',' || TO_CHAR(D.REQ_ID) || ',') > 0
        AND M.STATUS IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_APPROVED, C_REQ_STATUS_PARTIAL_PAID)
        AND D.DETAIL_STATUS = C_REQ_STATUS_APPROVED
      ORDER BY D.EMP_NO, M.THE_MONTH;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- BATCH CONFIRM — اعتماد الاحتساب (إنشاء دفعة)
  -- ============================================================
  PROCEDURE PAYMENT_REQ_BATCH_CONFIRM (
      P_REQ_IDS             IN  VARCHAR2,
      P_EXCLUDE_DETAIL_IDS  IN  VARCHAR2 DEFAULT NULL,
      P_MSG_OUT             OUT VARCHAR2
  ) IS
    V_USER       NUMBER := USER_PKG.GET_USER_ID;
    V_BATCH_ID   NUMBER;
    V_TOTAL_AMT  NUMBER := 0;
    V_EMP_CNT    NUMBER := 0;
  BEGIN
    V_BATCH_ID := PAYMENT_BATCH_SEQ.NEXTVAL;
    INSERT INTO GFC.PAYMENT_BATCH_TB (
        BATCH_ID, BATCH_NO, BATCH_DATE, TOTAL_AMOUNT, EMP_COUNT,
        REQ_IDS, STATUS, ENTRY_USER, ENTRY_DATE
    ) VALUES (
        V_BATCH_ID, 'PB-' || LPAD(V_BATCH_ID, 5, '0'), SYSDATE, 0, 0,
        SUBSTR(P_REQ_IDS, 1, 4000), 0, V_USER, SYSDATE
    );

    INSERT INTO GFC.PAYMENT_BATCH_LINK_TB (BATCH_ID, DETAIL_ID)
      SELECT V_BATCH_ID, D.DETAIL_ID
        FROM GFC.PAYMENT_REQ_DETAIL_TB D
        JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
       WHERE INSTR(',' || P_REQ_IDS || ',', ',' || TO_CHAR(M.REQ_ID) || ',') > 0
         AND D.DETAIL_STATUS = C_REQ_STATUS_APPROVED
         AND (P_EXCLUDE_DETAIL_IDS IS NULL
              OR INSTR(',' || P_EXCLUDE_DETAIL_IDS || ',', ',' || TO_CHAR(D.DETAIL_ID) || ',') = 0);

    FOR E IN (
      SELECT D.EMP_NO, SUM(D.REQ_AMOUNT) AS TOTAL_AMOUNT,
             NVL((SELECT EE.BANK FROM DATA.EMPLOYEES EE WHERE EE.NO = D.EMP_NO), 0) AS BANK_NO,
             NVL((SELECT EE.MASTER_BANKS_EMAIL FROM DATA.EMPLOYEES EE WHERE EE.NO = D.EMP_NO), 0) AS MASTER_BANK_NO
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.DETAIL_ID = D.DETAIL_ID AND L.BATCH_ID = V_BATCH_ID
      WHERE D.DETAIL_STATUS = C_REQ_STATUS_APPROVED
      GROUP BY D.EMP_NO
    ) LOOP
      INSERT INTO GFC.PAYMENT_BATCH_DETAIL_TB (
          BATCH_DETAIL_ID, BATCH_ID, EMP_NO, BANK_NO, MASTER_BANK_NO, TOTAL_AMOUNT
      ) VALUES (
          PAYMENT_BATCH_DETAIL_SEQ.NEXTVAL, V_BATCH_ID, E.EMP_NO,
          E.BANK_NO, E.MASTER_BANK_NO, E.TOTAL_AMOUNT
      );
      V_TOTAL_AMT := V_TOTAL_AMT + E.TOTAL_AMOUNT;
      V_EMP_CNT := V_EMP_CNT + 1;
    END LOOP;

    UPDATE GFC.PAYMENT_BATCH_TB SET TOTAL_AMOUNT = V_TOTAL_AMT, EMP_COUNT = V_EMP_CNT
     WHERE BATCH_ID = V_BATCH_ID;

    IF V_EMP_CNT = 0 THEN
      DELETE FROM GFC.PAYMENT_BATCH_TB WHERE BATCH_ID = V_BATCH_ID;
      P_MSG_OUT := '0|0|0';
    ELSE
      -- تحديث حالة الـ details المربوطة بالدفعة → PARTIAL_PAID حتى ما تظهر مرة ثانية بالاحتساب
      UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET DETAIL_STATUS = C_REQ_STATUS_PARTIAL_PAID
       WHERE DETAIL_ID IN (SELECT DETAIL_ID FROM GFC.PAYMENT_BATCH_LINK_TB WHERE BATCH_ID = V_BATCH_ID)
         AND DETAIL_STATUS = C_REQ_STATUS_APPROVED;
      -- تحديث حالة الماستر
      FOR R IN (SELECT DISTINCT M.REQ_ID FROM GFC.PAYMENT_REQ_DETAIL_TB D
                JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
                JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.DETAIL_ID = D.DETAIL_ID AND L.BATCH_ID = V_BATCH_ID)
      LOOP
        UPDATE GFC.PAYMENT_REQ_TB SET STATUS = DISBURSEMENT_PKG.CALC_MASTER_STATUS(R.REQ_ID) WHERE REQ_ID = R.REQ_ID;
      END LOOP;

      P_MSG_OUT := TO_CHAR(V_BATCH_ID) || '|' || TO_CHAR(V_EMP_CNT) || '|0';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    P_MSG_OUT := '0|0|1|' || SUBSTR(SQLERRM, 1, 200);
  END;


  -- ============================================================
  -- BATCH PAY — تنفيذ الصرف (ترحيل لجدول المستحقات)
  -- ============================================================
  PROCEDURE PAYMENT_REQ_BATCH_PAY (
      P_BATCH_ID IN  NUMBER,
      P_MSG_OUT  OUT VARCHAR2
  ) IS
    V_USER NUMBER := USER_PKG.GET_USER_ID;
    V_OK NUMBER := 0; V_ERR NUMBER := 0;
    V_SERIAL NUMBER; V_OLD_ST NUMBER; V_NEW_ST NUMBER;
    V_FAIL_LIST VARCHAR2(4000) := '';
    V_BATCH_ST NUMBER; V_REQ_IDS VARCHAR2(4000);
  BEGIN
    BEGIN
      SELECT STATUS, REQ_IDS INTO V_BATCH_ST, V_REQ_IDS
        FROM GFC.PAYMENT_BATCH_TB WHERE BATCH_ID = P_BATCH_ID;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      P_MSG_OUT := '0|0|1|الدفعة غير موجودة'; RETURN;
    END;
    IF V_BATCH_ST = 2 THEN P_MSG_OUT := '0|0|1|الدفعة مصروفة مسبقاً'; RETURN; END IF;

    FOR D IN (
      SELECT D.DETAIL_ID, D.EMP_NO, D.REQ_AMOUNT, D.PAY_TYPE, D.NOTE,
             M.THE_MONTH, M.REQ_ID, M.REQ_TYPE
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
      JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.DETAIL_ID = D.DETAIL_ID AND L.BATCH_ID = P_BATCH_ID
      WHERE D.DETAIL_STATUS IN (C_REQ_STATUS_APPROVED, C_REQ_STATUS_PARTIAL_PAID)
      ORDER BY D.EMP_NO, D.DETAIL_ID
    ) LOOP
      BEGIN
        IF D.REQ_TYPE <> C_REQ_TYPE_BENEFITS THEN
          V_SERIAL := SALARY_DUES_TB_SEQ.NEXTVAL;
          INSERT INTO GFC.SALARY_DUES_TB (
              SERIAL, EMP_NO, THE_MONTH, PAY_TYPE, PAY, THE_DATE, NOTE, ENTRY_USER, STATUS, BATCH_ID
          ) VALUES (
              V_SERIAL, D.EMP_NO, D.THE_MONTH, D.PAY_TYPE, D.REQ_AMOUNT, SYSDATE,
              SUBSTR('REQ=' || D.REQ_ID || ' ' || NVL(D.NOTE,''), 1, 200),
              V_USER, 1, P_BATCH_ID
          );
        ELSE
          V_SERIAL := NULL;
        END IF;

        UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET
            DETAIL_STATUS = C_REQ_STATUS_PAID, POST_SERIAL_DUES = V_SERIAL,
            DUES_AMOUNT = CASE WHEN D.REQ_TYPE = C_REQ_TYPE_BENEFITS THEN 0 ELSE REQ_AMOUNT END
         WHERE DETAIL_ID = D.DETAIL_ID;

        UPDATE GFC.PAYMENT_BATCH_LINK_TB SET DUES_SERIAL = V_SERIAL
         WHERE BATCH_ID = P_BATCH_ID AND DETAIL_ID = D.DETAIL_ID;

        V_OK := V_OK + 1;
      EXCEPTION WHEN OTHERS THEN
        V_ERR := V_ERR + 1;
        IF LENGTH(V_FAIL_LIST) < 3500 THEN
          V_FAIL_LIST := V_FAIL_LIST || D.EMP_NO || ': ' || SQLERRM || CHR(10);
        END IF;
      END;
    END LOOP;

    UPDATE GFC.PAYMENT_BATCH_TB SET STATUS = 2, PAY_USER = V_USER, PAY_DATE = SYSDATE
     WHERE BATCH_ID = P_BATCH_ID;

    FOR MR IN (
      SELECT DISTINCT D.REQ_ID
      FROM GFC.PAYMENT_REQ_DETAIL_TB D
      JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.DETAIL_ID = D.DETAIL_ID AND L.BATCH_ID = P_BATCH_ID
    ) LOOP
      BEGIN
        SELECT STATUS INTO V_OLD_ST FROM GFC.PAYMENT_REQ_TB WHERE REQ_ID = MR.REQ_ID;
        V_NEW_ST := DISBURSEMENT_PKG.CALC_MASTER_STATUS(MR.REQ_ID);
        UPDATE GFC.PAYMENT_REQ_TB SET
            STATUS = V_NEW_ST,
            PAY_USER = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_PAID, C_REQ_STATUS_PARTIAL_PAID) THEN V_USER ELSE PAY_USER END,
            PAY_DATE = CASE WHEN V_NEW_ST IN (C_REQ_STATUS_PAID, C_REQ_STATUS_PARTIAL_PAID) THEN SYSDATE ELSE PAY_DATE END,
            UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
         WHERE REQ_ID = MR.REQ_ID;
        DISBURSEMENT_PKG.SYNC_MASTER_AMOUNT(MR.REQ_ID);
        DISBURSEMENT_PKG.LOG_ACTION(MR.REQ_ID, 'BATCH_PAY', V_OLD_ST, V_NEW_ST, 'BATCH=' || P_BATCH_ID);
      EXCEPTION WHEN OTHERS THEN NULL;
      END;
    END LOOP;

    IF V_OK = 0 AND V_ERR = 0 THEN P_MSG_OUT := '0|0|0';
    ELSE
      P_MSG_OUT := TO_CHAR(P_BATCH_ID) || '|' || TO_CHAR(V_OK) || '|' || TO_CHAR(V_ERR);
      IF V_ERR > 0 THEN P_MSG_OUT := P_MSG_OUT || '|' || SUBSTR(V_FAIL_LIST, 1, 3000); END IF;
    END IF;
  EXCEPTION WHEN OTHERS THEN
    P_MSG_OUT := '0|0|1|' || SUBSTR(SQLERRM, 1, 200);
  END;


  -- ============================================================
  -- BATCH CANCEL — فك اعتماد الاحتساب
  -- ============================================================
  PROCEDURE BATCH_CANCEL (
      P_BATCH_ID NUMBER, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ST NUMBER; V_NO VARCHAR2(20); V_NEW_ST NUMBER;
  BEGIN
    SELECT STATUS, BATCH_NO INTO V_ST, V_NO
      FROM GFC.PAYMENT_BATCH_TB WHERE BATCH_ID = P_BATCH_ID FOR UPDATE NOWAIT;
    IF V_ST = 2 THEN P_MSG_OUT := 'لا يمكن فك دفعة مصروفة — استخدم عكس الصرف'; RETURN; END IF;

    -- إرجاع حالة الـ details إلى APPROVED
    UPDATE GFC.PAYMENT_REQ_DETAIL_TB SET DETAIL_STATUS = C_REQ_STATUS_APPROVED
     WHERE DETAIL_ID IN (SELECT DETAIL_ID FROM GFC.PAYMENT_BATCH_LINK_TB WHERE BATCH_ID = P_BATCH_ID)
       AND DETAIL_STATUS = C_REQ_STATUS_PARTIAL_PAID;
    -- إعادة حساب حالة الماستر
    FOR R IN (SELECT DISTINCT D.REQ_ID FROM GFC.PAYMENT_REQ_DETAIL_TB D
              JOIN GFC.PAYMENT_BATCH_LINK_TB L ON L.DETAIL_ID = D.DETAIL_ID AND L.BATCH_ID = P_BATCH_ID)
    LOOP
      V_NEW_ST := DISBURSEMENT_PKG.CALC_MASTER_STATUS(R.REQ_ID);
      UPDATE GFC.PAYMENT_REQ_TB SET STATUS = V_NEW_ST WHERE REQ_ID = R.REQ_ID;
    END LOOP;

    DELETE FROM GFC.PAYMENT_BATCH_LINK_TB   WHERE BATCH_ID = P_BATCH_ID;
    DELETE FROM GFC.PAYMENT_BATCH_DETAIL_TB WHERE BATCH_ID = P_BATCH_ID;
    DELETE FROM GFC.PAYMENT_BATCH_TB        WHERE BATCH_ID = P_BATCH_ID;
    P_MSG_OUT := '1';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الدفعة غير موجودة';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- BATCH REVERSE PAY — عكس صرف دفعة
  -- ============================================================
  PROCEDURE BATCH_REVERSE_PAY (
      P_BATCH_ID NUMBER, P_MSG_OUT OUT VARCHAR2
  ) IS
    V_ST NUMBER; V_NO VARCHAR2(20); V_USER NUMBER;
    V_REVERSED NUMBER := 0; V_ERRORS NUMBER := 0; V_NEW_ST NUMBER;
  BEGIN
    SELECT STATUS, BATCH_NO INTO V_ST, V_NO
      FROM GFC.PAYMENT_BATCH_TB WHERE BATCH_ID = P_BATCH_ID FOR UPDATE NOWAIT;
    IF V_ST <> 2 THEN P_MSG_OUT := 'العكس متاح فقط للدفعات المصروفة'; RETURN; END IF;

    V_USER := USER_PKG.GET_USER_ID;

    -- أرشفة ثم حذف سجلات المستحقات المرتبطة بالدفعة
    INSERT INTO GFC.SALARY_DUES_ARCHIVE_TB
      SELECT T.*, V_USER, SYSDATE FROM GFC.SALARY_DUES_TB T
       WHERE T.BATCH_ID = P_BATCH_ID;

    DELETE FROM GFC.SALARY_DUES_TB WHERE BATCH_ID = P_BATCH_ID;

    FOR L IN (SELECT L.DETAIL_ID, L.DUES_SERIAL, D.EMP_NO, D.REQ_ID
                FROM GFC.PAYMENT_BATCH_LINK_TB L
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
               WHERE L.BATCH_ID = P_BATCH_ID)
    LOOP
      BEGIN
        UPDATE GFC.PAYMENT_REQ_DETAIL_TB
           SET DETAIL_STATUS = C_REQ_STATUS_APPROVED, POST_SERIAL_DUES = NULL
         WHERE DETAIL_ID = L.DETAIL_ID;

        UPDATE GFC.PAYMENT_BATCH_LINK_TB SET DUES_SERIAL = NULL
         WHERE BATCH_ID = P_BATCH_ID AND DETAIL_ID = L.DETAIL_ID;

        V_REVERSED := V_REVERSED + 1;
      EXCEPTION WHEN OTHERS THEN V_ERRORS := V_ERRORS + 1;
      END;
    END LOOP;

    FOR R IN (SELECT DISTINCT D.REQ_ID
                FROM GFC.PAYMENT_BATCH_LINK_TB L
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
               WHERE L.BATCH_ID = P_BATCH_ID)
    LOOP
      V_NEW_ST := DISBURSEMENT_PKG.CALC_MASTER_STATUS(R.REQ_ID);
      UPDATE GFC.PAYMENT_REQ_TB SET STATUS = V_NEW_ST,
          PAY_USER = NULL, PAY_DATE = NULL,
          UPDATE_USER = V_USER, UPDATE_DATE = SYSDATE
       WHERE REQ_ID = R.REQ_ID;
      DISBURSEMENT_PKG.SYNC_MASTER_AMOUNT(R.REQ_ID);
      DISBURSEMENT_PKG.LOG_ACTION(R.REQ_ID, 'BATCH_REVERSE', 2, V_NEW_ST, 'BATCH=' || V_NO);
    END LOOP;

    UPDATE GFC.PAYMENT_BATCH_TB SET STATUS = 9, PAY_USER = V_USER, PAY_DATE = SYSDATE
     WHERE BATCH_ID = P_BATCH_ID;

    IF V_ERRORS > 0 THEN
      P_MSG_OUT := '1|تم عكس ' || V_REVERSED || ' سجل — فشل ' || V_ERRORS;
    ELSE
      P_MSG_OUT := '1|تم عكس صرف الدفعة ' || V_NO || ' (' || V_REVERSED || ' موظف)';
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN P_MSG_OUT := 'الدفعة غير موجودة';
    WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- BATCH HISTORY LIST
  -- ============================================================
  PROCEDURE BATCH_HISTORY_LIST (
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT B.BATCH_ID, B.BATCH_NO, B.BATCH_DATE, B.TOTAL_AMOUNT, B.EMP_COUNT,
             (SELECT COUNT(1) FROM GFC.PAYMENT_BATCH_LINK_TB L WHERE L.BATCH_ID = B.BATCH_ID) AS MOVEMENT_COUNT,
             B.STATUS, B.REQ_IDS,
             SETTING_PKG.CONSTANT_DETAILS_TB_GET_NAME(542, B.STATUS) AS STATUS_NAME,
             USER_PKG.GET_USER_NAME(B.ENTRY_USER) AS ENTRY_USER_NAME,
             B.ENTRY_DATE,
             USER_PKG.GET_USER_NAME(B.PAY_USER) AS PAY_USER_NAME,
             B.PAY_DATE
        FROM GFC.PAYMENT_BATCH_TB B
       ORDER BY B.BATCH_ID DESC;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- BATCH HISTORY GET — تفاصيل دفعة
  -- ============================================================
  PROCEDURE BATCH_HISTORY_GET (
      P_BATCH_ID NUMBER,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT BD.BATCH_DETAIL_ID, BD.BATCH_ID, BD.EMP_NO,
             E.NAME AS EMP_NAME,
             EMP_PKG.GET_EMP_BRANCH_NAME(BD.EMP_NO) AS BRANCH_NAME,
             BD.BANK_NO,
             DISBURSEMENT_PKG.GET_BANK_NAME(BD.BANK_NO) AS BANK_NAME,
             DISBURSEMENT_PKG.GET_MASTER_BANK_NAME(BD.EMP_NO) AS MASTER_BANK_NAME,
             BD.TOTAL_AMOUNT,
             BD.MASTER_BANK_NO,
             EMP_PKG.GET_EMP_BRANCH(BD.EMP_NO) AS EMP_BRANCH_NO,
             (SELECT LISTAGG(M.REQ_NO, ', ') WITHIN GROUP (ORDER BY M.REQ_ID)
                FROM GFC.PAYMENT_BATCH_LINK_TB L
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D ON D.DETAIL_ID = L.DETAIL_ID
                JOIN GFC.PAYMENT_REQ_TB M ON M.REQ_ID = D.REQ_ID
               WHERE L.BATCH_ID = BD.BATCH_ID AND D.EMP_NO = BD.EMP_NO) AS REQ_NOS,
             -- مبالغ حسب نوع الطلب
             NVL((SELECT SUM(D2.REQ_AMOUNT) FROM GFC.PAYMENT_BATCH_LINK_TB L2
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D2 ON D2.DETAIL_ID = L2.DETAIL_ID
                JOIN GFC.PAYMENT_REQ_TB M2 ON M2.REQ_ID = D2.REQ_ID
               WHERE L2.BATCH_ID = BD.BATCH_ID AND D2.EMP_NO = BD.EMP_NO AND M2.REQ_TYPE = 1), 0) AS AMT_TYPE1,
             NVL((SELECT SUM(D2.REQ_AMOUNT) FROM GFC.PAYMENT_BATCH_LINK_TB L2
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D2 ON D2.DETAIL_ID = L2.DETAIL_ID
                JOIN GFC.PAYMENT_REQ_TB M2 ON M2.REQ_ID = D2.REQ_ID
               WHERE L2.BATCH_ID = BD.BATCH_ID AND D2.EMP_NO = BD.EMP_NO AND M2.REQ_TYPE = 2), 0) AS AMT_TYPE2,
             NVL((SELECT SUM(D2.REQ_AMOUNT) FROM GFC.PAYMENT_BATCH_LINK_TB L2
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D2 ON D2.DETAIL_ID = L2.DETAIL_ID
                JOIN GFC.PAYMENT_REQ_TB M2 ON M2.REQ_ID = D2.REQ_ID
               WHERE L2.BATCH_ID = BD.BATCH_ID AND D2.EMP_NO = BD.EMP_NO AND M2.REQ_TYPE IN (3,4)), 0) AS AMT_TYPE3,
             NVL((SELECT SUM(D2.REQ_AMOUNT) FROM GFC.PAYMENT_BATCH_LINK_TB L2
                JOIN GFC.PAYMENT_REQ_DETAIL_TB D2 ON D2.DETAIL_ID = L2.DETAIL_ID
                JOIN GFC.PAYMENT_REQ_TB M2 ON M2.REQ_ID = D2.REQ_ID
               WHERE L2.BATCH_ID = BD.BATCH_ID AND D2.EMP_NO = BD.EMP_NO AND M2.REQ_TYPE = 5), 0) AS AMT_TYPE4
        FROM GFC.PAYMENT_BATCH_DETAIL_TB BD
        JOIN DATA.EMPLOYEES E ON E.NO = BD.EMP_NO
       WHERE BD.BATCH_ID = P_BATCH_ID
       ORDER BY BD.EMP_NO;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


  -- ============================================================
  -- BATCH BANK EXPORT — تصدير بيانات الدفعة للبنك
  -- ============================================================
  PROCEDURE BATCH_BANK_EXPORT (
      P_BATCH_ID NUMBER,
      P_MASTER_BANK_NO NUMBER DEFAULT NULL,
      P_REF_CUR_OUT OUT SYS_REFCURSOR, P_MSG_OUT OUT VARCHAR2
  ) IS
  BEGIN
    OPEN P_REF_CUR_OUT FOR
      SELECT * FROM GFC.PAYMENT_BATCH_BANK_VW
       WHERE BATCH_ID = P_BATCH_ID
         AND (P_MASTER_BANK_NO <= 0 OR MASTER_BANK_NO = P_MASTER_BANK_NO)
       ORDER BY MASTER_BANK_NO, BANK_NO, EMP_NO;
    P_MSG_OUT := '1';
  EXCEPTION WHEN OTHERS THEN P_MSG_OUT := SQLERRM;
  END;


END DISBURSEMENT_BATCH_PKG;
/
