-- ============================================================
-- ⚠️ RESET ALL PAYMENT_REQ DATA — للتطوير/الاختبار فقط ⚠️
-- ============================================================
-- يحذف كل بيانات صرف الرواتب ويعيد الـ sequences للصفر.
-- ⚠️ تشغيل من PL/SQL Developer كمستخدم GFC_PAK فقط
-- ⚠️ خذ backup قبل التشغيل — DDL لا يمكن التراجع عنه
-- ⚠️ غير منشورة في الـ UI ولا متاحة للمستخدمين
-- ============================================================

CREATE OR REPLACE PROCEDURE GFC_PAK.PAYMENT_REQ_RESET_ALL
    AUTHID CURRENT_USER  -- ⭐ يشتغل بصلاحيات اللي ينفّذها (لو روح أنا GFC_PAK = كل صلاحياتي)
AS
    V_REQ_CNT     NUMBER := 0;
    V_DETAIL_CNT  NUMBER := 0;
    V_BATCH_CNT   NUMBER := 0;
    V_BD_CNT      NUMBER := 0;
    V_LOG_CNT     NUMBER := 0;
    V_LINK_CNT    NUMBER := 0;
    V_SPLIT_CNT   NUMBER := 0;
    V_DUES_CNT    NUMBER := 0;
    V_ARCH_CNT    NUMBER := 0;
BEGIN
    -- ═══ المرحلة 1: حذف البيانات بترتيب يحترم FK ═══
    DELETE FROM GFC.PAYMENT_REQ_DETAIL_SPLIT_TB; V_SPLIT_CNT  := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_BATCH_LINK_TB;       V_LINK_CNT   := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_BATCH_DETAIL_TB;     V_BD_CNT     := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_BATCH_TB;            V_BATCH_CNT  := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_REQ_LOG_TB;          V_LOG_CNT    := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_REQ_DETAIL_TB;       V_DETAIL_CNT := SQL%ROWCOUNT;
    DELETE FROM GFC.PAYMENT_REQ_TB;              V_REQ_CNT    := SQL%ROWCOUNT;

    -- المستحقات المرتبطة بدفعات
    DELETE FROM GFC.SALARY_DUES_ARCHIVE_TB WHERE BATCH_ID IS NOT NULL; V_ARCH_CNT := SQL%ROWCOUNT;
    DELETE FROM GFC.SALARY_DUES_TB         WHERE BATCH_ID IS NOT NULL; V_DUES_CNT := SQL%ROWCOUNT;

    COMMIT;  -- صريح قبل الـ DDL

    -- طباعة عدّاد الحذف
    DBMS_OUTPUT.PUT_LINE('═══════════ DML تم ═══════════');
    DBMS_OUTPUT.PUT_LINE('PAYMENT_REQ_TB:               ' || V_REQ_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_REQ_DETAIL_TB:        ' || V_DETAIL_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_REQ_LOG_TB:           ' || V_LOG_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_BATCH_TB:             ' || V_BATCH_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_BATCH_DETAIL_TB:      ' || V_BD_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_BATCH_LINK_TB:        ' || V_LINK_CNT);
    DBMS_OUTPUT.PUT_LINE('PAYMENT_REQ_DETAIL_SPLIT_TB:  ' || V_SPLIT_CNT);
    DBMS_OUTPUT.PUT_LINE('SALARY_DUES_TB (batch):       ' || V_DUES_CNT);
    DBMS_OUTPUT.PUT_LINE('SALARY_DUES_ARCHIVE_TB:       ' || V_ARCH_CNT);

    -- ═══ المرحلة 2: إعادة الـ sequences ═══
    -- DDL inside PL/SQL needs EXECUTE IMMEDIATE
    -- نُغلّف كل DROP بـ exception handler عشان ما توقف العملية لو واحد فشل
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_REQ_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_REQ_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_REQ_DETAIL_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_REQ_DETAIL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_REQ_LOG_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_REQ_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_REQ_DETAIL_SPLIT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_REQ_DETAIL_SPLIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_BATCH_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_BATCH_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE GFC_PAK.PAYMENT_BATCH_DETAIL_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE GFC_PAK.PAYMENT_BATCH_DETAIL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';

    -- ═══ المرحلة 3: Re-grants للـ PUBLIC ═══
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_REQ_SEQ              TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_REQ_DETAIL_SEQ       TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_REQ_LOG_SEQ          TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_REQ_DETAIL_SPLIT_SEQ TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_BATCH_SEQ            TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON GFC_PAK.PAYMENT_BATCH_DETAIL_SEQ     TO PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;

    DBMS_OUTPUT.PUT_LINE('═══════════ Sequences تم إعادتها ═══════════');
    DBMS_OUTPUT.PUT_LINE('✓ DONE');
END PAYMENT_REQ_RESET_ALL;
/


-- ============================================================
-- طريقة الاستخدام (من PL/SQL Developer كـ GFC_PAK):
-- ============================================================
/*
SET SERVEROUTPUT ON;
BEGIN
    GFC_PAK.PAYMENT_REQ_RESET_ALL;
END;
/
*/
