-- ============================================================
-- اكتشاف: هل في BRANCH_ID مكرر لـ "دير البلح" مع LEGACY_BANK_NO مختلف؟
-- ============================================================

-- 1) كل الـ branches في PAYMENT_BANK_BRANCHES_TB لـ بنك فلسطين
--    شو الفروع الموجودة وكم BRANCH_ID فيه لكل فرع؟
SELECT BR.BRANCH_ID, BR.BRANCH_NAME, BR.LEGACY_BANK_NO,
       DISBURSEMENT_PKG.GET_BANK_NAME(BR.LEGACY_BANK_NO) AS LEGACY_NAME_RESULT,
       BR.IS_ACTIVE
  FROM GFC.PAYMENT_BANK_BRANCHES_TB BR
 WHERE BR.PROVIDER_ID = 108   -- بنك فلسطين
 ORDER BY BR.BRANCH_NAME, BR.BRANCH_ID;
-- توقع نشوف:
--   BRANCH_ID=12 "فلسطين دير البلح" LEGACY_BANK_NO=460  → LEGACY_NAME_RESULT = NULL (الخطأ)
--   BRANCH_ID=??? "بنك فلسطين - فرع دير البلح" LEGACY_BANK_NO=??? → LEGACY_NAME_RESULT = صحيح


-- 2) أي BRANCH_ID يستخدمه الـ 61 موظف في فرع دير البلح؟
SELECT PA.BRANCH_ID, BR.BRANCH_NAME, BR.LEGACY_BANK_NO,
       DISBURSEMENT_PKG.GET_BANK_NAME(BR.LEGACY_BANK_NO) AS LEGACY_NAME,
       COUNT(DISTINCT BD.EMP_NO) AS EMP_COUNT,
       SUM(BD.TOTAL_AMOUNT) AS TOTAL
  FROM GFC.PAYMENT_BATCH_DETAIL_TB BD
  JOIN GFC.PAYMENT_ACCOUNTS_TB PA ON PA.ACC_ID = BD.ACC_ID
  LEFT JOIN GFC.PAYMENT_BANK_BRANCHES_TB BR ON BR.BRANCH_ID = PA.BRANCH_ID
 WHERE BD.BATCH_ID = 1
   AND BD.MASTER_BANK_NO = 81  -- بنك فلسطين
 GROUP BY PA.BRANCH_ID, BR.BRANCH_NAME, BR.LEGACY_BANK_NO
 ORDER BY EMP_COUNT DESC;
-- هاي راح تعرض كل الـ BRANCH_ID المستخدمة + اسم الفرع + اللي بيرجع من GET_BANK_NAME


-- 3) خاصة فرع دير البلح: كل الـ branches في PAYMENT_BANK_BRANCHES_TB يحوي اسمه "دير البلح"
SELECT BR.BRANCH_ID, BR.PROVIDER_ID, PP.PROVIDER_NAME, BR.BRANCH_NAME,
       BR.LEGACY_BANK_NO,
       DISBURSEMENT_PKG.GET_BANK_NAME(BR.LEGACY_BANK_NO) AS LEGACY_NAME
  FROM GFC.PAYMENT_BANK_BRANCHES_TB BR
  JOIN GFC.PAYMENT_PROVIDERS_TB PP ON PP.PROVIDER_ID = BR.PROVIDER_ID
 WHERE BR.BRANCH_NAME LIKE '%دير البلح%'
 ORDER BY PP.PROVIDER_NAME, BR.BRANCH_ID;


-- 4) كم حساب مربوط بـ BRANCH_ID=12 (الخاطئ)؟
SELECT COUNT(*) AS ACCOUNTS_LINKED_TO_BR12
  FROM GFC.PAYMENT_ACCOUNTS_TB
 WHERE BRANCH_ID = 12;
